package.json
packages/Badge/package.json
packages/Button/package.json
packages/Checkbox/package.json
packages/Portal/package.json
packages/RadioBoxGroup/package.json
packages/RadioGroup/package.json
packages/Toggle/package.json

These updates should allow `npm run release` or `lerna publish` to publish all packages to the public NPM.

Update package.json files for publishing to public NPM

---

packages/Icon/src/createIconComponent.js
packages/Icon/src/index.js
packages/theme/src/index.js

Previously, the following import didn't work:
```JS
import Icon, {glyphs, createIconComponent} from '@leafygreen-ui/Icon'
```
This pull request fixes this issue.

PD-237: Fix Icon / theme build

---

package-lock.json
packages/RadioBoxGroup/README.md
packages/RadioBoxGroup/src/index.js
packages/RadioGroup/README.md
packages/RadioGroup/src/index.js

- Changed export pattern for RadioGroup and RadioBox Group
- Can now be imported as: 
- import RadioBox, { RadioBoxGroup } from '@leafygreen-ui/RadioBoxGroup'
- import Radio, { RadioGroup } from '@leafygreen-ui/RadioGroup'
- Updated README to reflect pattern change 
- Tested in MMS

Changed export pattern for RadioGroup and RadioBoxGroup

---

packages/Popover/src/Popover.tsx
packages/Popover/src/index.ts

Export Popover props in Popover.tsx and index.ts to be used in Menu
Also removed defaultProps in favor of object defaults

Chore: export popover props and clean object defaults

---

packages/button/src/Button.story.tsx
packages/button/src/Button.tsx

Fixes an issue where buttons not rendered as a button element would have disappearing text on hover.
Additionally, this PR makes it less likely an issue like this will arise in the future.
🎟 _Jira ticket:_ [Component: Update buttons to new palette](https://jira.mongodb.org/browse/PD-341)

PD-341: Button palette update fix

---

packages/menu/src/Menu.tsx
packages/popover/src/Popover.tsx

Popover required the use of all of its props, which was causing errors in Menu and other components that use it as a dependency. PR to make some of these props optional.
🎟 _Jira ticket:_ [Name of ticket](https://my.jira/ticket)

fix: make popover props optional where necc

---

packages/icon/src/index.ts
packages/icon/typings/svgr.d.ts
typings/images.d.ts

Right now, users of the Icon component within a TypeScript project receive an error regarding a broken reference to the SVGR namespace. This fixes that broken reference.
🎟 _Jira ticket:_ [Fix SVGR typing issue](https://jira.mongodb.org/browse/PD-373)

PD-373: Fix broken reference to SVGR namespace

---

.svgrrc.js
packages/icon/README.md
packages/icon/tsconfig.json

Updated Icon component such that fill styling now uses currentColor, and thus CSS color rules can be used to style glyphs. 
🎟 _Jira ticket:_ [PD-355](https://jira.mongodb.org/browse/PD-355)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] I have added necessary documentation (if appropriate)

fix(icon): PD-355 Use currentcolor to set glyph fills

---

packages/button/src/Button.tsx

A fix for a bug that was reported directly to me.
The recently introduced span element in button has a z-index assigned that was being applied in a global stacking context. This change makes the button root element a new stacking context to avoid this issue.

Make the root button element a new stacking context

---

packages/icon/README.md
packages/icon/src/createIconComponent.tsx
packages/palette/README.md

Add a `small` variant to the `Icon` component
🎟 _Jira ticket:_ [PD-378](https://jira.mongodb.org/browse/PD-378)
Some small README fixes included here

PD-378: Add a 'small' size variant to the Icon component

---

.changeset/fresh-foxes-hang/changes.json
.changeset/fresh-foxes-hang/changes.md
.changeset/itchy-hotels-pretend/changes.json
.changeset/itchy-hotels-pretend/changes.md
.changeset/silver-jokes-turn/changes.json
.changeset/silver-jokes-turn/changes.md
.prettierignore

Adds changesets for several recent PRs.
Additionally, this ignores the `.changeset` directory when validating formatting with prettier.

Adds changesets for the Card, Button, and Icon updates

---

.changeset/slimy-insects-lie/changes.json
.changeset/slimy-insects-lie/changes.md
packages/tabs/src/Tab.tsx

Updating Tabs component to be more accessible based on bugs detected with the Storybook accessibility add-on. 
* Want to note that the color contrast on the non-active Tabs is not sufficient, so this PR does not make Tabs fully compliant.
🎟 _Jira ticket:_ [PD-393](https://jira.mongodb.org/browse/PD-393?workflowName=Product+Design+Workflow&stepId=54)

PD-393: Make Tabs more accessible

---

.changeset/spicy-dolphins-juggle/changes.json
.changeset/spicy-dolphins-juggle/changes.md
packages/checkbox/src/Checkbox.tsx

This fixes the bug logged at https://jira.mongodb.org/browse/CHARTS-2938. It happens because the hidden input is positioned out side of the boundary box of the parent label. Fix it by move the input inside the bounding box and also set its width and height to 0 for added safety.
🎟 _Jira ticket:_ [CHARTS-2938](https://jira.mongodb.org/browse/CHARTS-2938)

position input inside the boundary of parent label

---

.changeset/blue-falcons-love/changes.json
.changeset/blue-falcons-love/changes.md
packages/radio-box-group/src/RadioBoxGroup.tsx

Added role="group" and aria-label to containing RadioBoxGroup div to make component accessible by a11y standards.
🎟 _Jira ticket:_ [PD-391](https://jira.mongodb.org/browse/PD-391)

PD-391: Make RadioBoxGroup accessible

---

.changeset/shaggy-camels-nail/changes.json
.changeset/shaggy-camels-nail/changes.md
packages/menu/src/Menu.spec.js
packages/menu/src/MenuGroup.tsx

Removed role='menu' from MenuGroup component, based on accessibility guidelines. And removed associated test (which was testing that MenuGroup had that role).
🎟 _Jira ticket:_ [PD-295](https://jira.mongodb.org/browse/PD-295)

PD-295: Make Menu accessible

---

.changeset/blue-falcons-love/changes.json
.changeset/tough-hounds-cheer/changes.json
.changeset/tough-hounds-cheer/changes.md
packages/radio-box-group/README.md
packages/radio-group/README.md
packages/radio-group/src/RadioGroup.tsx

Added group role to RadioGroup container div and supplied aria-label to ensure component is accessible
🎟 _Jira ticket:_ [PD-392](https://jira.mongodb.org/browse/PD-392)

PD-392: Make RadioGroup accessible

---

.changeset/silly-trees-approve/changes.md
.changeset/tidy-buckets-pretend/changes.md
packages/hooks/src/index.ts
packages/hooks/src/useEscapeKey.ts
packages/menu/src/Menu.tsx
packages/modal/src/Modal.tsx

- Renamed useEscapeHandler to useEscapeKey
- Updated instances in use and changeset to reflect new name
- Removed `immediateProp` in favor of `stopProp`

PD-409: useEscapeKey

---

.changeset/silent-mangos-yawn/changes.json
.changeset/silent-mangos-yawn/changes.md
packages/portal/package.json
webpack.config.js

This pull request adds `react-dom` to our list of external dependencies noted in our webpack config, dramatically reducing the portal component's bundle size.
🎟 _Jira ticket:_ [PD-421](https://jira.mongodb.org/browse/PD-421)

PD-421: Exclude react-dom from bundles

---

CONTRIBUTING.md

In an effort to make contributing to LeafyGreen as seamless as possible, I've updated our contributing guidelines. (Thank you for all of the feedback @matt-d-rat 👋)
Upgrade our contributing documentation. New sections: 
- Can I contribute?
- Roadmap
- Getting Started (Typescript, Emotion, React Design Patterns)
Please let me know if I missed anything, or if there's anything else worth mentioning here! Thank you!
🎟 _Jira ticket:_ [PD-453](https://jira.mongodb.org/browse/PD-453)
Tooling

PD-453: Update Contributing Documentation

---

.changeset/fresh-pumpkins-change.md
packages/palette/src/palette.story.tsx

- Fixed bug in Palette storybook such that hex values and color names are now displayed
🎟 _Jira ticket:_ [PD-455](https://jira.mongodb.org/browse/PD-455)

PD-455: Fix bug in storybook to display hex values

---

.changeset/witty-goats-mate.md
packages/menu/package.json
packages/menu/src/Menu.spec.js
packages/menu/src/MenuItem.tsx

- Make MenuItem props extend HTML element based on whether it's being rendered as a button or an anchor tag
- Allow consumers to customize `target` and `rel` props
- Added test to prove that fix works
🎟 _Jira ticket:_ [PD-457](https://jira.mongodb.org/browse/PD-457)

PD-457: Allow target/rel props to be passed to MenuItem

---

.changeset/clean-tables-eat.md
.changeset/five-socks-jam.md
packages/button/src/Button.tsx
packages/menu/src/MenuItem.tsx
packages/mongo-menu/src/MongoMenu.tsx

This updates the styles specifically for focus/active states for anchors in Menu and MongoMenu with rules that are already inherited but need to be specifically included in order to avoid third party libraries from overwriting these with values set on `a` tags specifically. This was found during [library upgrades for the quarter](https://jira.mongodb.org/browse/CLOUDP-49387), and we figured we needed to address this soon anyway for the work we're doing on the Account app.
🎟 _Jira ticket:_ [Update MongoMenu and MenuItem styles for Cloud usage](https://jira.mongodb.org/browse/PD-461)

PD-461: Update anchor styles for Menu and MongoMenu components

---

.changeset/dirty-apples-type.md
.vscode/settings.json
packages/menu/src/Menu.spec.js
packages/menu/src/MenuItem.tsx
packages/mongo-menu/src/MongoMenu.tsx

- Change MenuItem default from target="_blank" to "_self"
- Support ability of consumer to change target and rel props
- Make sure that MongoMenu still defaults to "_blank"
🎟 _Jira ticket:_ [PD-459](https://jira.mongodb.org/browse/PD-459)

PD-459: Fix MenuItem target/rel props

---

.changeset/pink-berries-teach.md
packages/button/src/Button.tsx

- Setting `color: inherit` on :hover, :focus broke some states of the component, so updated property values to be explicitly set with each state
🎟 _Jira ticket:_ [PD-470](https://jira.mongodb.org/browse/PD-470)
Before:
After:
Before:
After:

PD-470: Fix bug with color in Button component 

---

.changeset/empty-bobcats-teach.md
packages/icon/src/glyphs/index.ts
packages/icon/typings/svg.d.ts
packages/icon/typings/svgr.d.ts

This fixes an issue where the module definition for SVGs was overriding the typing for SVG modules in consuming applications.
🎟 _Jira ticket:_ [Fix SVG module definition issue](https://jira.mongodb.org/browse/PD-484)

[PD-484] Fix TypeScript issue in Webpack projects using an SVG loader

---

packages/root/src/Root.spec.tsx
packages/root/src/Root.tsx

This isn't necessary to be approved, but I wanted to provide a changeset that updates the tests for this component so they better handle scoping, cleanup tasks, data-id consistency, etc. If you're interested, we can merge these changes into your branch (this PR is pointing at PD-492 for a base, not master). If not, you can just go through it and get from it whatever you like / take whatever is helpful

PD-492: Optional Test Changes

---

.changeset/afraid-cougars-shake.md
.changeset/flat-seas-learn.md
packages/menu/README.md
packages/menu/package.json
packages/menu/src/Menu.spec.js
packages/menu/src/Menu.story.js
packages/menu/src/MenuItem.tsx
packages/menu/src/MenuSeparator.tsx
packages/menu/src/SubMenu.tsx
packages/menu/src/styles.tsx
packages/mongo-menu/package.json
packages/mongo-nav/src/mongo-select/MongoSelect.spec.tsx
packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
packages/mongo-nav/src/user-menu/UserMenu.tsx
yarn.lock

- Combined PD-536: Add `glyph` and `size` prop to MenuItem component with PD-501, add User Feedback to UserMenu
- Add `glyph` and `size` prop to MenuItem
- Change `glyph` from accepting `string` to accepting `React.ReactElement` in SubMenu
- Add User Feedback item to UserMenu
🎟 _Jira ticket:_ [PD-536](https://jira.mongodb.org/browse/PD-536)
🎟 _Jira ticket:_ [PD-501](https://jira.mongodb.org/browse/PD-501)

PD-536: Add `glyph` and `size` prop to MenuItem, add UserFeedback to UserMenu

---

.changeset/long-tools-clap.md
packages/mongo-nav/src/types.ts
packages/mongo-nav/src/user-menu/README.md
packages/mongo-nav/src/user-menu/UserMenu.tsx

- University needs a Menu to use ASAP, and we've deprecated MongoMenu, so we need to make UserMenu resilient when used in environments outside of the MongoNav component
- Only blocker here is that the Hosts/URLs are currently required for the entire MongoNav component, so suggested changes.. 
- Hosts/URLs are no longer required props
- Duplicated logic for creating defaults for Hosts and URLs from MongoNav, as if this component is to be used outside of the MongoNav component, it will need this logic implemented
- To Note: I know there is a PR floating around out there made by @seanmhanson which moves some of this URL logic outside of the <MongoNav /> component, so I didn't want to duplicate this work right now and was thinking we could merge without the more generalized defaults and then …

PD-545: Add new types such that usermenu can be used without mongonav

---

.changeset/blue-timers-explode.md
packages/mongo-nav/src/MongoNav.tsx
packages/mongo-nav/src/data.ts

This corrects the default project url to put the hash after the projectId. It also corrects a similar issue in the fixture data, though it does not appear to be used in testing.
🎟 _Jira ticket:_ [PD-553](https://jira.mongodb.org/browse/[PD-553])

PD-553: Fix typo in project links

---

.changeset/yellow-socks-yell.md
packages/mongo-nav/README.md
packages/mongo-nav/src/MongoNav.spec.tsx
packages/mongo-nav/src/MongoNav.story.tsx
packages/mongo-nav/src/MongoNav.tsx

- Add loadData prop to MongoNav

Add loadData prop to MongoNav

---

.changeset/stupid-poets-melt.md
packages/mongo-nav/src/data.ts
packages/mongo-nav/src/mongo-select/MongoSelect.tsx

- Room for scrollbars displaying unnecessarily in OrgSelect and ProjectSelect components
- Made overflow logic more specific to overflow-y, and conditionally applying the CSS rule based on the number of MenuItems that will appear in the Select components 
- To test locally, update OS preferences to always display scroll bars and add varying levels of orgs/projects to the data.ts file
- With 5 MenuItems: ![Screen Shot 2020-03-09 at 9 46 02 AM](https://user-images.githubusercontent.com/26016393/76218907-605ae580-61eb-11ea-9310-ed57940f3c71.png)
- With 5+: ![Screen Shot 2020-03-09 at 9 46 10 AM](https://user-images.githubusercontent.com/26016393/76218958-723c8880-61eb-11ea-960a-107b5b4e6d15.png)
🎟 _Jira ticket:_ [PD-569](https://jira.mongodb.org/browse/PD-569)

PD-569: Hide Scrollbars in MongoSelect

---

packages/mongo-nav/src/MongoNav.tsx

Super small tweak, encountered when updating tests in mms. Better to be safe and check that it exists before trying to filter on it so MongoNav doesn't fail hard.

Prevent against possible undefined value

---

.changeset/kind-beans-fly.md
packages/mongo-nav/src/MongoNav.tsx

While debugging Realm's integration of MongoNav, it appears that async await syntax is being polyfilled with regenerator runtime, but it wasn't being required in the build. Rather than adding a rather large polyfill (+50% to the MongoNav build file size, IIRC), this PR switches use of the syntax to more traditional Promise API.

Remove async await syntax from MongoNav

---

.changeset/silent-boxes-brush.md
.changeset/tall-deers-exist.md
packages/menu/src/styles.tsx
packages/mongo-nav/src/user-menu/UserMenu.tsx

- Makes Cloud section of UserMenu clickable, even if Cloud is not the active product
also fixes bug in MenuItem, which removes text-decoration from the focused style when MenuItem is rendered as an anchor tag
cc: @nellem23 
🎟 _Jira ticket:_ [PD-628](https://jira.mongodb.org/browse/PD-628)

PD-628: Makes Cloud section of UserMenu clickable, even if Cloud is not the active product

---

.changeset/honest-bulldogs-confess.md
packages/text-input/README.md
packages/text-input/src/TextInput.spec.tsx
packages/text-input/src/TextInput.story.tsx
packages/text-input/src/TextInput.tsx
packages/text-input/src/index.ts

Allows consumers to override type prop in Input component
🎟 _Jira ticket:_ [PD-662](https://jira.mongodb.org/browse/PD-662)

PD-662: Allows consumers to override type prop in Input component

---

.changeset/cyan-plums-grow.md
packages/menu/package.json
packages/menu/src/SubMenu.tsx
packages/modal/package.json
packages/modal/src/Modal.tsx
packages/popover/package.json
packages/popover/src/Popover.tsx
yarn.lock

- Upgrade to react-transition-group 4.4.x which fixes StrictMode warnings
- Validates that animations still work
- Validates that strict mode console warnings no longer appear
🎟 _Jira ticket:_ [PD-665](https://jira.mongodb.org/browse/PD-665)

PD-665: Upgrade to react-transition-group 4.4.x which fixes StrictMode warnings

---

scripts/package-builder.js

- Changes export pattern in index
- Removes cleanup from spec and adds jest-dom/extend-expect by default

PD-670: Clean up package-builder script

---

.changeset/wicked-socks-camp.md
packages/banner/src/Banner.tsx

PD-680: Wrap Banner children in div tags rather than span tags
🎟 _Jira ticket:_ [PD-680](https://jira.mongodb.org/browse/PD-680)

PD-680: Wrap Banner children in div tags rather than span tags

---

.changeset/many-cougars-wait.md
packages/modal/README.md
packages/modal/src/Modal.spec.tsx
packages/modal/src/Modal.story.tsx
packages/modal/src/Modal.tsx

- Addresses: Cannot prevent closing modal when clicking backdrop by adding `closeOnBackdropClick` prop
🎟 _Jira ticket:_ [PD-616](https://jira.mongodb.org/browse/PD-616)

PD-616: Adds closeOnBackdropClick prop

---

.changeset/tasty-ways-design.md
packages/icon/src/Icon.spec.tsx
packages/icon/src/template.ts

Changes the generated icon code from:
```Edit.displayName = Edit;```
to
```Edit.displayName = 'Edit';```
This could technically be a breaking change, but I doubt anyone would be depending on the previous behavior.

Fix glyph `displayName`s

---

.changeset/eight-spiders-unite.md
packages/mongo-nav/src/helpers/OnPremUserMenu.tsx

Description: `OnPremUserMenu` that is exported currently, does not support `Logout` functionality. As a result, when it's consumed inside the external component, click on the Logout does not do anything. `UserMenu` does support `onLogout` prop which can be used to provide overrides for `Logout` click. This PR replicates the same functionality of `onLogout` prop to `OnPremUserMenu`. 
In addition to that, the type definition for `urls` in `OnPremUserMenu` has `Required<URLSInterface` which actually expects all the properties of `URLSInterface` to be there in `urls` prop that is supplied. For `OnPremUserMenu` the `urls` would just only have `onPrem` property from `URLSInterface`. This PR fixes that typescript definition as well. 
🎟 _Jira ticket:_ [Logout functionality is missing from …

PD-701 Add onLogput prop to OnPremUserMenu

---

.changeset/tough-countries-remain.md
packages/mongo-nav/README.md
packages/mongo-nav/src/MongoNav.spec.tsx
packages/mongo-nav/src/helpers/OrgNavLink.tsx
packages/mongo-nav/src/on-element-click-provider/OnElementClick.spec.tsx
packages/mongo-nav/src/org-nav/OrgNav.spec.tsx
packages/mongo-nav/src/org-nav/OrgNav.tsx
packages/mongo-nav/src/types.ts

- Removes href from Access Manager in OrgNav, and instead clicking Access Manager triggers the dropdown
- Removes IconButton wrapping around Access Manager dropdown
cc: @nellem23 
🎟 _Jira ticket:_ [PD-698](https://jira.mongodb.org/browse/PD-698)

PD-698: Change behavior of Access Manager dropdown in MongoNav

---

packages/tooltip/CHANGELOG.md

Changes `Poopover` to `Popover` 😂

Fix typo in Tooltip CHANGELOG

---

.changeset/four-timers-smile.md
.changeset/hungry-bananas-promise.md
packages/lib/src/index.spec.ts
packages/menu/src/Menu.tsx
packages/menu/src/MenuItem.tsx
packages/popover/src/Popover.tsx
packages/popover/src/types.ts
packages/portal/src/Portal.tsx
packages/tooltip/src/Tooltip.tsx
scripts/jestSetup.js

Usages of Menu and Popover were breaking SSR contexts due to the usage of `Element`. within their PropTypes. This PR conditionally uses Element based on the build target, and otherwise uses `PropTypes.any`.
Additionally, this PR restores the compatibility of some components with TypeScript <3.8 by removing usages of the `import type` syntax introduced in 3.8.
🎟 _Jira ticket:_ [PD-741](https://jira.mongodb.org/browse/PD-741)

PD-741: SSR fixes, TypeScript <3.8 compatibility fix

---

.changeset/dull-insects-itch.md
packages/tooltip/src/Tooltip.tsx

Adds enabled prop to Tooltip proptypes
🎟 _Jira ticket:_ [PD-761](https://jira.mongodb.org/browse/PD-761)

PD-761: Adds enabled prop to Tooltip proptypes

---

.changeset/brown-frogs-film.md
packages/mongo-nav/src/types.ts
packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
packages/mongo-nav/src/user-menu/UserMenu.tsx

UserMenu should accept the URLS as-is from OrgNav or simply an object of the relevant URLS to UserMenu when used independently of MongoNav.

Fix Types for UserMenu

---

.changeset/quick-planes-relax.md
packages/tabs/src/Tabs.tsx

Fix TypeError caused by conditionally rendered tabs
🎟 _Jira ticket:_ [PD-865](https://jira.mongodb.org/browse/PD-865)

PD-865: Fix TypeError caused by conditionally rendered tabs

---

.changeset/big-llamas-exist.md
package.json
packages/tabs/package.json
packages/tabs/src/Tabs.spec.tsx
packages/tabs/src/Tabs.story.tsx
packages/tabs/src/Tabs.tsx
packages/tabs/tsconfig.json
yarn.lock

- Fixes keyboard navigation bug in Tabs component: Previously, if multiple `<Tabs />` were rendered, only the first on the page would be navigable via keyboard. Now, the currently focused `<Tabs />` will be navigable via keyboard, regardless of location on page.
🎟 _Jira ticket:_ [PD-918](https://jira.mongodb.org/browse/PD-918)

PD-918: Fixes keyboard navigation bug in Tabs component

---

.github/workflows/release.yml

Running our formatter against the PR was flakey to begin with. I think until we find a more robust solution we should omit and leave the Release action as it was.

Fix GitHub Action

---

packages/copyable/src/Copyable.tsx
website/components/CodeDocs.tsx

- Makes label optional (since InlineCode is not a form element, this shouldn't break any rules of accessibility)
- Makes Component scrollable on the x-axis
- Removes explicitly setting z-index which was causing problems with stacking contexts in .design
- Updates CodeDocs to use Copyable component
Note: didn't create a changeset yet, because we didn't release Copyable yet (right?) so was hoping we could just publish these with the initial release
🎟 _Jira ticket:_ [PD-940](https://jira.mongodb.org/browse/PD-940)

PD-940: Copyable Updates

---

.changeset/stupid-books-tease.md
packages/tooltip/src/Tooltip.tsx

Wraps text when content overflows Tooltip container

---

.changeset/selfish-eels-grab.md
packages/typography/src/Typography.tsx

`H1`, `H2`, `H3` and `Subtitle` components now accept an `as` prop, such that we can keep styles consistent via `Component`, but the actual heading level that should be rendered can change based on context. This was done to support making MongoDB an accessible platform, as headings should only decrease by one level (i.e. from `<h1>` to `<h2>`) but the styles don't always need to appear as such.

PD-975: Adds as prop to h1, h2, h3 and subtitle

---

.changeset/hip-impalas-live.md
packages/mongo-nav/src/org-nav/OrgNav.tsx

A regression in the `OrgNav` component causes the `data-testid` attribute to be missing from the `All Clusters` link and the `Admin` link. This is resulting in test failures for anything that was looking up these `data-testid` attributes.
🎟 _Jira ticket:_ [CLOUDP-78527](https://jira.mongodb.org/browse/CLOUDP-78527)

CLOUDP-78527: Add missing data-testid attributes to OrgNav

---

.changeset/heavy-tools-lay.md
packages/copyable/src/Copyable.tsx

Updates border radius from 0px to 4px
Before:
After:

PD-983: Copyable border radius polish

---

.changeset/twelve-melons-grow.md
README.md
packages/text-input/src/TextInput.tsx

I ran into an issue where a `TextInput`'s error text was exceeding the hard-coded 20px height allotted to it.  Converting the `height` to a `min-height` still reduces how much the form height will bounce around, while still allowing for elasticity in extreme cases like the one I'm up against.
🎟 _Jira ticket: [CLOUDP-79746](https://jira.mongodb.org/browse/CLOUDP-79746)
I also did a drive-by to update the docs to reference the correct minimum version of Node required for this project.

CLOUDP-79746: Allowing text input error message to expand its container

---

.changeset/calm-cobras-cough.md
packages/text-input/src/TextInput.tsx

Preserve right padding when icons are visible in a disabled text input
🎟 _Jira ticket:_ [PD-1002](https://jira.mongodb.org/browse/PD-1002)

PD-1002: Preserve right padding when icons are visible in a disabled text input

---

.changeset/rude-goats-tell.md
packages/confirmation-modal/src/ConfirmationModal.tsx

Updates visual heading from div to h1 tag in ConfirmationModal component
🎟 _Jira ticket:_ [PD-1033](https://jira.mongodb.org/browse/PD-1033)

PD-1033: Visual heading text is not marked as heading in Confirmation Modal

---

website/.babelrc
website/components/Grid.tsx
website/package.json
website/pages/_document.tsx
website/pages/component/palette/example.tsx
website/utils/renderer.ts
yarn.lock

I did a lot of research to try and understand how to prevent the flash of unstyled content that's currently occurring with .design. Ultimately, I based my solution off of a PR to vercel's Next.js repo where they feature examples of using Next with all different libraries/frameworks (see here: https://github.com/vercel/next.js/pull/20228/files). I'm not convinced that this is 100%, but I do think it's a step in the right direction. I'm finding that it works better on dev than prod (`yarn dev` v. `yarn build && yarn start`) and that it works better in Chrome/Safari than Firefox. 
Let me know what you think and if you have ideas at a better approach here. I know for sure that whatever solution will require modifying the`_document.tsx` file as that's explicitly called out in the `emotion` …

Attempts to prevent FOUC in .design

---

.changeset/proud-rockets-return.md
packages/tabs/src/Tab.tsx

Duplicately applying `onClick` prop to `TabTitle` and `Tab` components. This PR removes extraneous function call on `Tab` component.

Fixes bug in Tab component

---

.changeset/nasty-readers-travel.md
packages/select/src/Option.tsx

When a non-centered Option is clicked, the Select component will scroll to center that element instead of being selected.
🎟 _Jira ticket:_ [PD-1084](https://jira.mongodb.org/browse/PD-1084)

PD-1084: When a non-centered Option is clicked, the Select component will scroll to center that element instead of being selected.

---

.changeset/fluffy-gorillas-wave.md
packages/tabs/src/TabTitle.tsx

🎟 _Jira ticket:_ [PD-1131](https://jira.mongodb.org/browse/PD-1131)

PD-1131: Removes hover state from currently selected Tabs

---

.changeset/nine-trees-jog.md
packages/tabs/src/Tabs.tsx
packages/tabs/src/index.ts

This PR exports the types used by `Tabs` so that consumers can use it. It exports AccessibleTabsProps aliased as TabsProps as that is the true type use by Tabs. Lmk if that sounds right or if we should just export the plain `TabsProps` as defined in Tabs or not do the alias.
Since this is a simple export I don't think we need unit tests. LMK if you think otherwise. I'm happy to add something.
This change can be tested by building the Tabs package and using the newly exported type.

export props used by Tabs

---

.changeset/rich-suits-warn.md
packages/code/src/Code.spec.tsx
packages/code/src/Code.tsx
packages/code/src/Panel.tsx

Fixes bug in Code component, empty panel rendering without copyable

---

.changeset/eight-colts-cheat.md
packages/radio-box-group/src/RadioBox.tsx
packages/radio-box-group/src/RadioBoxGroup.spec.tsx
packages/radio-box-group/src/RadioBoxGroup.tsx
packages/radio-box-group/src/context.ts

`RadioBoxGroup` using `cloneElement` to communicate with its child `RadioBox` elements means that those `RadioBox` elements have to be direct children, and it's not possible for consumers to make their own wrapper components. Communicating through context instead removes this limitation and allows the `RadioBox` to be deeper in the React tree.
🎟 _Jira ticket:_ Tangentially related to [CLOUDP-90548](https://jira.mongodb.org/browse/CLOUDP-90548)
This is as much a discussion-starter as a specific proposed change. I've argued against `cloneElement` for a while, so we don't have to rehash all of that, but I do think that using context allows us to use React more naturally, without having to worry about the additional constraints brought on by a parent component meddling with its children's …

Use context instead of cloneElement in RadioBox

---

.changeset/cyan-turkeys-run.md
packages/copyable/README.md
packages/copyable/src/Copyable.tsx

Resolves Tooltip presentation issues when using a Copyable within a Modal
🎟 _Jira ticket:_ [PD-1418](https://jira.mongodb.org/browse/PD-1418)
Use a Copyable within a Modal with `z-index > 0`:
Create a temporary Story within `Copyable.story.tsx` 
```js
.add('Within Modal', () => {
const darkMode = boolean('Dark mode', false)
return (
<Modal
open={true}
size='default'
darkMode={darkMode}
style={{ zIndex: 1 }}
>
<Copyable
label={text('Label', 'Label')}
description={text('Description', '') || undefined}
darkMode={darkMode}
shouldTooltipUsePortal={false}
>
{text('Text', 'npm install @leafygreen-ui/copyable')}
</Copyable>
</Modal>
)
})
```

PD-1418: Updates Tooltip within Copyable

---

.changeset/proud-ants-design.md

Prevents default when tooltips contained within an anchor tag would be clicked. This fixes an issue where clicking tooltips would navigate you to a different page.
Also removes the cursor: pointer for the gov banner.
Changes can be viewed here: https://github.com/10gen/leafygreen-ui-mongo-nav/pull/25
🎟 _Jira ticket:_ [PD-1514](https://jira.mongodb.org/browse/PD-1514)
Hover on the logo, Project Alerts, Activity Feed, and Invite User links. Clicking the tooltips that appear should not cause you to navigate. Clicking on the links themselves should continue to navigate the user.

PD-1514 : Fix issue in MongoNav when clicking tooltips

---

.changeset/beige-trains-relax.md
packages/portal/src/Portal.tsx

In Portal v2.2.0, there was a change made to support SSR by not rendering until the second render (using `useEffect`). Unfortunately, this had the effect of breaking a bunch of tests in mms when I tried to update the library, because it made multiple components downstream async that had previously been synchronous. This PR fixes the issue by using `useLayoutEffect`, which still allows rendering it in SSR to be a no-op, but triggers the second render immediately while still in the same thread, so it acts as a synchronous render in tests.
🎟 _Jira ticket:_ _none_ (should I file one?)

Have Portal render synchronously while still not breaking SSR

---

.changeset/shiny-tips-flash.md
packages/card/src/Card.tsx

🎟 _Jira ticket:_ No ticket, but I can open one if needed. Change based on this [slack discussion](https://mongodb.slack.com/archives/CFFA5BS79/p1638898731232900?thread_ts=1638787473.222300&cid=CFFA5BS79)
Aligns focuscolor and transition timing to match other components in the repo
You can run the storybook locally, make Card focusable and look at the new style color.
This is how it looks now

chore(card): Update focus ring color and animation timing to match other leafygreen components

---

packages/callout/tsconfig.json

Currently, we can't build TS for the repo because there's a missing tsconfig reference for callout, since we added a dependency on Typography.

Fix missing reference in Callout's tsconfig.json

---

.github/workflows/release.yml
package.json

Using `yarn changeset version` instead of `yarn version` (which just outputs the version of yarn)

Fixes changeset version script

---

.changeset/tiny-comics-sell.md
packages/button/src/styles.ts

We noticed an issue where the Button should be using the same font color between normal and hover/active states, but our CSS is overriding the intended behavior here because the color isn't explicitly being called out. I noticed this because the linked ticket uses a `default` button which did not call this out, but using a `primary` button worked as expected.
Thus, we have css globally like
```
a,
a:hover,
a:active {
color: blue;
}
```
which is sometimes unintentionally applying to LeafyGreen Button Variants that do not specify the hover and active states. This should not change anything else about how the button looks or behaves.
🎟 _Jira ticket:_ [CLOUDP-123279](https://jira.mongodb.org/browse/CLOUDP-123279)
Check that the button still is looking good for hover/active states.
Please try …

CLOUDP-123279: Call out font colors for Button Variant hover/active states

---

.changeset/odd-ants-cheat.md
packages/select/src/MenuButton.tsx
packages/select/src/Select.story.tsx

Fixes a bug where long values, when selected, would overflow outside the Select trigger.
🎟 _Jira ticket:_ [PD-1900](https://jira.mongodb.org/browse/PD-1900)
Select the long value in the "Uncontrolled" Select story

PD-1900 Select truncation

---

.changeset/poor-bears-press.md
packages/select/src/Option.tsx
packages/select/src/Select.tsx

🎟 _Jira ticket:_ [PD-2361](https://jira.mongodb.org/browse/PD-2361:)
This prop was not being used inside `Option` so it was included in `...rest` and then passed to an `Li` element cause react to show a warning.

PD-2361: Remove isDeselection

---

.changeset/new-dots-fix.md
packages/combobox/src/Combobox.story.tsx
packages/combobox/src/Combobox.styles.ts
packages/combobox/src/Combobox.tsx

Fixes a bug where the combobox text input content would overflow the container. 
Note: this is hard to write a test for. This is something Chromatic would catch
🎟 _Jira ticket:_ [LG-2489](https://jira.mongodb.org/browse/LG-2489)

LG-2489 Combobox overflow

---

.github/workflows/release.yml

Only send a trigger, without a payload to the .design repo. 
In the other repo we'll determine what packages were updated
See also: https://github.com/mongodb/design/pull/197

Remove payload from Repository Dispatch job

---

.changeset/odd-ravens-refuse.md
packages/polymorphic/README.md
packages/polymorphic/src/Example/examples.spec.tsx

Adds a test, and documents how to use `emotion/styled` with Polymorphic.
Since Polymorphic components are strictly typed, to use styled props with Typescript you will need to define the additional props you expect to use within styled, and pass these into styled as generic type.
See a generic example here: https://codesandbox.io/s/wizardly-mayer-ktynkt?file=/src/App.tsx
```tsx
interface StyledProps {
color: string;
}
const MyStyledComponent = styled(MyComponent)<StyledProps>`
color: ${props => props.color};
` as PolymorphicComponentType;
```

Document Polymorphic styled support

---

.changeset/itchy-phones-punch.md
packages/typography/src/Link/Link.styles.ts
packages/typography/src/Link/Link.tsx

🎟 _Jira ticket:_ [LG-3020](https://jira.mongodb.org/browse/LG-3020)

LG-3020: Unset text-decoration in Link component

---

.changeset/hot-adults-whisper.md
.changeset/silent-tools-share.md
packages/hooks/src/useIdAllocator.ts

useIdAllocator not compat with React 18 in current version
Repro case here (install Modal locally versus from NPM): https://codesandbox.io/s/green-moon-0j46x2?file=/src/App.tsx

Removes call to use React's useId if found

---

.changeset/nervous-geese-wink.md
packages/segmented-control/src/SegmentedControl/SegmentedControl.tsx

Per React standard, null should be allowed to be passed as children to React components. https://legacy.reactjs.org/blog/2014/07/17/react-v0.11.html#rendering-to-null
🎟 _Jira ticket:_ [LG-3213](https://jira.mongodb.org/browse/LG-3213)

LG-3213: Allows null to be passed to SegmentedControl 

---

packages/search-input/src/SearchResultsMenu/SearchResultsMenu.story.tsx

The Search Results Menu snapshot is flaky (popover placement at the time of snapshot is inconsistent)
See https://mongodb.chromatic.com/test?appId=642700aa3e49e32bdbf0b0fc&id=649215455914b03356db629b
Disabling snapshot to reduce test noise

Disable Search Menu snapshot

---

.changeset/seven-bananas-serve.md
tools/cli/src/index.ts
tools/test/src/index.ts
tools/test/src/test.spec.ts

Adds pass-through arguments to `lg test` command. You can now pass through any command accepted by the `jest` cli 
```bash
> lg test <any cli option>
```
Jest CLI options: https://jestjs.io/docs/cli

Pass through test options

---

.github/workflows/release.yml

Our slackbot command won't run if we don't build the cli.
This updates our config to restore the build cache before attempting to run the slackbot

Build CLI on release

---

.changeset/gentle-masks-greet.md
tools/build/src/typescript/build-ts.spec.ts
tools/build/src/typescript/build-ts.ts

Fixes an issue where TS errors would not cause the build to fail.
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3516
Make a blatant TS error. Run `yarn build` expect the build to fail

`tsc` exit code [LG-3561]

---

packages/lib/src/consoleOnce.ts
packages/lib/src/index.ts
packages/lib/src/validateChildren.tsx

No functional changes. Resolves circular dependency
`validateChildren.tsx` imported methods from `index.ts`.
while `index.ts` re-exported `validateChildren` method

Resolve `lib` Circular Dependency

---

packages/table/README.md

LG-3523: Update Table README

---

.changeset/funny-rivers-look.md
.changeset/fuzzy-roses-heal.md
package.json
packages/search-input/src/SearchResultsMenu/SearchResultsMenu.tsx
packages/search-input/src/SearchResultsMenu/SearchResultsMenu.types.ts
yarn.lock

🎟 _Jira ticket:_ [LG-3592](https://jira.mongodb.org/browse/LG-3592)

LG-3592: SearchResultsMenu popoverProps; `footerSlot` prop

---

.github/workflows/react17.yml

Globally installs node-gyp when running CI for React 17

yarn global add node-gyp

---

.changeset/proud-doors-smoke.md
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.spec.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.tsx
packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.spec.tsx
packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
packages/lib/src/createSyntheticEvent/createSyntheticEvent.ts
packages/lib/src/helpers/index.ts
packages/lib/src/helpers/rollover/index.ts
packages/lib/src/helpers/rollover/rollover.spec.ts

[LG-3771](https://jira.mongodb.org/browse/LG-3771) - When incrementing/decrementing a segment with up/down arrows, the focus moves to the next segment instead of staying focused on the segment you're incrementing/decrementing.
[LG-3774](https://jira.mongodb.org/browse/LG-3774) - Tabbing into the datepicker and pressing the up arrow shows random number
[LG-3768](https://jira.mongodb.org/browse/LG-3768) - keypresses in the input opens the menu and the input focus is hijacked

DatePicker [LG-3771, LG-3774] up/down arrows

---

.changeset/little-melons-beam.md
.changeset/proud-doors-smoke.md
.changeset/tall-mice-ring.md
packages/date-picker/package.json
packages/date-picker/src/DatePicker/DatePicker.spec.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.spec.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.spec.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.types.ts
packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.spec.tsx
packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.types.ts
packages/date-picker/src/shared/components/DateInput/DateInputSegment/index.ts
packages/date-picker/src/shared/hooks/useDateSegments/DateSegments.types.ts
packages/date-picker/src/shared/utils/index.ts
packages/date-picker/src/shared/utils/isSameUTCDay/isSameUTCDay.spec.ts
packages/date-picker/src/shared/utils/isSameUTCMonth/isSameUTCMonth.spec.ts
packages/date-picker/src/shared/utils/setUTCMonth/setUTCMonth.spec.ts
packages/lib/src/createSyntheticEvent/createSyntheticEvent.ts
packages/lib/src/helpers/index.ts
packages/lib/src/helpers/rollover/index.ts
packages/lib/src/helpers/rollover/rollover.spec.ts

Ensures arrow keys move the cursor, or update focused segment
[LG-3756](https://jira.mongodb.org/browse/LG-3756) - L/R arrow keys should move focused segment
[LG-3771](https://jira.mongodb.org/browse/LG-3771) - When incrementing/decrementing a segment with up/down arrows, the focus should stay on the segment you're incrementing/decrementing.
[LG-3774](https://jira.mongodb.org/browse/LG-3774) - Tabbing into the datepicker and pressing the up arrow should set the value to the min value
[LG-3768](https://jira.mongodb.org/browse/LG-3768) - keyboard input should not open the menu

Date Picker [LG-3756, LG-3771, LG-3774, LG-3768] Arrow keys in Date Input

---

packages/date-picker/src/DatePicker/DatePicker.spec.tsx
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.spec.tsx
packages/date-utils/src/getSimulatedTZDate/getSimulatedTZDate.spec.ts
packages/date-utils/src/getSimulatedTZDate/getSimulatedTZDate.ts
packages/date-utils/src/getSimulatedUTCDate/getSimulatedUTCDate.spec.ts
packages/date-utils/src/getSimulatedUTCDate/getSimulatedUTCDate.ts
packages/date-utils/src/getSimulatedUTCDate/index.ts
packages/date-utils/src/getUTCDateString/getUTCDateString.spec.ts
packages/date-utils/src/getUTCDateString/getUTCDateString.ts
packages/date-utils/src/index.ts
packages/date-utils/src/types.ts

[LG-3894](https://jira.mongodb.org/browse/LG-3894)

Date picker [LG-3894] Local date strings

---

packages/date-picker/src/DatePicker/DatePicker.spec.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.spec.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx

Date Picker [LG-3897] backspace

---

packages/date-picker/src/DatePicker.stories.tsx
packages/date-picker/src/DatePicker/DatePicker.spec.tsx
packages/date-picker/src/DatePicker/DatePickerContext/DatePickerContext.tsx
packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.tsx
packages/date-picker/src/shared/context/SharedDatePickerContext.tsx
packages/date-picker/src/shared/utils/getSegmentStateFromRefs/getSegmentStateFromRefs.spec.ts
packages/date-picker/src/shared/utils/getSegmentStateFromRefs/getSegmentStateFromRefs.ts
packages/date-picker/src/shared/utils/getSegmentStateFromRefs/index.ts
packages/date-picker/src/shared/utils/index.ts

- Enter '1996-02-29' > press up/down on year. Results in an invalid date ('1995-02-29' not a leap year)
- Enter '2021-03-31' > down on month > Results in "2021-02-31" (not valid)
- Enter '2020-02-29' > up on day > Results in "2020-02-30" (not valid)
- Pressing up/down on a month or year input that results in an invalid date will show an error message
- Pressing up/down on a date input will roll-over the date value (e.g. Sep 30 -> up -> Sep 1)

DatePicker [LG-3899] arrow key errors

---

.changeset/bright-walls-glow.md
.changeset/fast-bananas-watch.md
.changeset/healthy-needles-learn.md
.changeset/khaki-lies-carry.md
.changeset/strange-scissors-prove.md
packages/a11y/src/A11y.spec.tsx
packages/hooks/src/hooks.spec.tsx
packages/hooks/src/useControlledValue/useControlledValue.spec.ts
packages/hooks/src/useDynamicRefs/useDynamicRefs.spec.tsx
packages/leafygreen-provider/src/PopoverContext/PopoverContext.spec.tsx
packages/testing-lib/package.json
packages/testing-lib/src/RTLOverrides.ts
packages/testing-lib/src/index.ts
packages/testing-lib/src/renderHookOverride.ts
packages/testing-lib/src/waitForState.ts
packages/testing-lib/tsconfig.json
packages/toast/src/ToastContext/ToastReducer/useToastReducer.spec.ts
packages/toast/src/ToastContext/ToastReducer/useToastReducer.ts
packages/toast/src/ToastContext/useToast/useToast.spec.tsx
tools/test/package.json
tools/validate/src/dependencies/config.ts
tools/validate/src/dependencies/utils/globToRegex.ts
tools/validate/src/dependencies/utils/index.ts
tools/validate/src/dependencies/validateListedDependencies.ts
yarn.lock

Attempts to make usage of `renderHook` consistent between R17 & R18 test environments
To do this I needed to:
1. Re-export a version `renderHook` from `@leafygreen-ui/testing-lib`, either originating from `@testing-library/react` or `@testing-library/react-hooks`, depending on what packages we have installed (concept lifted from [react-spectrum](https://github.com/adobe/react-spectrum/blob/main/packages/dev/test-utils/src/renderOverride.js))
2. Update imports for all test files that use `renderHook`
3. Update tests to ensure they work using both the `/react-hooks` and `/react` versions of `renderHook`
a. Update `toastReducer` logic to ensure we return the correct value from `updateToast`
4. Add `@leafygreen-ui/testing-lib` to `@lg-tools/test` dependencies
5. Exclude …

React 17 `renderHook`

---

.changeset/popular-hats-travel.md
.changeset/stale-bikes-smoke.md
package.json
packages/popover/package.json
packages/popover/src/Popover.types.ts
packages/popover/src/Popover/Popover.spec.tsx
yarn.lock

Resolves: https://jira.mongodb.org/browse/LG-3797
Popover now require `@types/react-transition-group` so components extending `PopoverProps` use the correct types.
Duplicates https://github.com/mongodb/leafygreen-ui/pull/2159

Popover Props [LG-3797]

---

.changeset/four-vans-tickle.md
packages/table/README.md
packages/table/src/useLeafyGreenTable/useLeafyGreenTable.tsx
packages/table/src/useLeafyGreenTable/useLeafyGreenTable.types.ts

We would like to expose the `scrollToIndex` method in the @leafygreen-ui/table virtualization library to allow the table to programmatically scroll to a certain row. 

Expose scroll to index functionality in table

---

.changeset/strange-pumpkins-invent.md
.changeset/tricky-games-worry.md
packages/marketing-modal/src/MarketingModal/MarketingModal.tsx
packages/modal/src/Modal/Modal.types.ts

Fixes a bug and sets the default `closeIconColor` to 'default'
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3957

Updates default MarketingModal `closeIconColor` prop

---

.changeset/fifty-turkeys-battle.md
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.stories.tsx

🎟 _Jira ticket:_ [LG-3943](https://jira.mongodb.org/browse/LG-3943)

LG-3943:  remove todays date from DatePickerMenu.stories

---

.changeset/old-singers-kneel.md
.changeset/wicked-impalas-battle.md
packages/table/src/Cell/Cell.styles.ts
packages/table/src/Cell/Cell.tsx
packages/table/src/Cell/Cell.types.ts
packages/table/src/Cell/HeaderCell/HeaderCell.tsx
packages/table/src/Cell/InternalCell.tsx
packages/table/src/ExpandedContent/ExpandedContent.tsx
packages/table/src/Table.story.tsx
packages/table/src/utils/makeData.testutils.tsx

Adds `overflow` prop to `Cell` component. By default there is no change. When `overflow === 'truncate'`, the styling of the cell is updated (if necessary) to be aligned to the top, with an ellipsis after 2 lines of text.
🎟 _Jira ticket:_ 
[LG-3952](https://jira.mongodb.org/browse/LG-3952)

Table cell overflow [LG-3952]

---

.changeset/tough-goats-jam.md
packages/date-picker/src/DatePicker/DatePicker.testutils.tsx
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.spec.tsx
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.stories.tsx
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.spec.tsx
packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.tsx
packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.spec.tsx

🎟 _Jira ticket:_ [LG-3878](https://jira.mongodb.org/browse/LG-3878)
Currently, when navigating with VoiceOver, VoiceOver does not announce the current selection for the year and month selects. This happens because we pass a static `aria-label` to the `Select` component. My solution is to make the `aria-label` dynamic by appending the current selection to the `aria-label` string.

LG-3878: Date Picker add current year/month selection to aria-label

---

.changeset/nice-crabs-sniff.md
.changeset/wicked-donuts-search.md
tools/link/src/link.ts
tools/link/src/utils/createLinkFrom.spec.ts
tools/link/src/utils/createLinkFrom.ts
tools/link/src/utils/install.spec.ts
tools/link/src/utils/install.ts
tools/link/src/utils/linkPackageTo.spec.ts
tools/link/src/utils/linkPackageTo.ts
tools/link/src/utils/linkPackagesForScope.spec.ts
tools/link/src/utils/linkPackagesForScope.ts
tools/link/src/utils/mocks.testutils.ts
tools/meta/src/getPackageManager.spec.ts
tools/meta/src/getPackageManager.ts
tools/meta/src/index.ts

Previously the `lg link` script would only install & link packages using yarn. Now it will check the destination app's package manager (via lock file) and link packages using the correct package manager.
Additionally, this PR tests for many `link` utils

Adds multiple package managers to `link` script

---

.changeset/cuddly-wasps-float.md
packages/combobox/src/Combobox/Combobox.spec.tsx
packages/combobox/src/Combobox/Combobox.tsx

Combobox incorrectly makes selection on "Enter" key press
🎟 _Jira ticket:_ [LG-3954](https://jira.mongodb.org/browse/LG-3954)
- [] I have added necessary documentation (if appropriate)

LG-3954: Combobox incorrectly makes selection on "Enter" key press

---

.changeset/early-coins-fry.md
packages/expandable-card/src/ExpandableCard.story.tsx

Updates live example so that `title` does not look like an optional prop

LG-3355: Updates ExpandableCard Live Example

---

.changeset/short-games-double.md
packages/number-input/src/Arrows/Arrow.tsx
packages/number-input/src/Arrows/Arrows.tsx
packages/number-input/src/Arrows/Arrows.types.ts
packages/number-input/src/Input/Input.tsx
packages/number-input/src/NumberInput.story.tsx
packages/number-input/src/NumberInput/NumberInput.spec.tsx
packages/number-input/src/NumberInput/NumberInput.types.ts

In the `NumberInput` component, the `onBlur` callback was not being invoked when the arrow buttons were clicked. The `onBlur` was being passed in with the rest of the props directly to the input, and this change will now pass it to both the input and the arrows.
🎟 _Jira ticket:_ [LG-3940](https://jira.mongodb.org/browse/LG-3940)
_Linked to_: [BAAS-27278](https://jira.mongodb.org/browse/BAAS-27278) 
I added storybook changes, so this can be tested by adding/removing focus on the arrow buttons and reviewing the console log entries.
https://github.com/mongodb/leafygreen-ui/assets/52300529/b3050fb6-565d-4c4d-bf4c-1781f969d999

LG-3940: NumberInput onBlur runs with arrow buttons

---

packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.stories.tsx

`DatePickerMenu` snapshots are flaky. Disabling them until we can make them more reliable

Disable DatePickerMenu Chromatic snapshots

---

.changeset/few-geckos-think.md
packages/popover/src/Popover.stories.tsx
packages/popover/src/Popover.types.ts
packages/popover/src/Popover/Popover.spec.tsx
packages/popover/src/Popover/Popover.tsx
packages/portal/src/Portal/Portal.spec.tsx
packages/portal/src/Portal/Portal.tsx
packages/portal/src/Portal/Portal.types.ts

- expose manual fwdref from `Portal`
- expose `portalRef` from `Popover` 
🎟 _Jira ticket:_ [LG-3988](https://jira.mongodb.org/browse/LG-3988)
[Part 1](https://github.com/mongodb/leafygreen-ui/pull/2239) | [Part 2](https://github.com/mongodb/leafygreen-ui/pull/2241)

LG-3988: expose portalRef from Popover and Portal props

---

.changeset/chilled-seahorses-pay.md
packages/text-area/src/TextArea/TextArea.spec.tsx
packages/text-area/src/TextArea/TextArea.tsx

Currently, the way `uncontrolledValue` is handled prevents `defaultValue` from working. I added `defaultValue` as the initial state for `uncontrolledValue` so that an initial value can be set while also allowing future edits from the user.
Not sure if I should have used `rest?.defaultValue` instead of just adding it, but since `className` is also not in `packages/text-area/src/TextArea/TextArea.types.ts` I thought it might be ok. Let me know if you want me to change that :D 
🎟 _Jira ticket:_ N/A

Allow `defaultValue` to be used in `TextArea`

---

.gitignore
package.json
yarn.lock

Resolves: https://jira.mongodb.org/browse/LG-4183
Fixes a bug where adding new packages via the command line would update `yarn.lock` in a way that would break Storybook & Jest.
By adding this resolution, we ensure only one version of `wrap-ansi` is installed.]
See [this issue in the storybook repo](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) for more
Run the following in `main` and `adam/fix-wrap-ansi-cjs` to see the bug and fix, respectively
```bash
yarn workspace @lg-tools/storyook-addon add @leafygreen-ui/banner
```
Then, to see the errors run 
```bash
yarn test
```
or
```bash
yarn build-storybook
```

Add yarn resolution for `jackspeak`[LG-4183]

---

.changeset/early-buttons-agree.md
.changeset/pretty-toes-tan.md
chat/message-feedback/src/InlineMessageFeedback/InlineMessageFeedback.styles.ts
chat/message-feedback/src/InlineMessageFeedback/InlineMessageFeedback.tsx
packages/text-area/package.json
packages/text-area/src/TextArea/TextArea.spec.tsx
packages/text-area/src/TextArea/TextArea.styles.ts
packages/text-area/src/TextArea/TextArea.tsx
packages/text-area/src/TextArea/TextArea.types.ts
packages/text-area/src/constants.ts
packages/text-area/src/utils/getTestUtils/getTestUtils.spec.tsx
packages/text-area/src/utils/getTestUtils/getTestUtils.ts
packages/text-area/tsconfig.json
yarn.lock

`TextArea`
- `FormField` styling applies to `TextArea`
- passes aria props to `FormField`
- adds `successMessage` prop
- adds default state messages
🎟 _Jira ticket:_ [LG-4144](https://jira.mongodb.org/browse/LG-4144) | [LG-4192](https://jira.mongodb.org/browse/LG-4192)
- Figma: https://www.figma.com/file/8M2FIDohVwZhC05jn0z17K/LG-2103%3A-Text-input-error-state?type=design&node-id=14674-86000&mode=design&t=RVhTpuWS4QhysQAO-4
- Review storybook and chromatic

LG-4144 | LG-4192: [CCP] TextArea

---

packages/tooltip/src/Tooltip/Tooltip.types.ts

It took me a while to debug that a Tooltip `trigger` component needed to render `children` in order to actually render the tooltip. Adding documentation for this.
A potential-runtime warning could be the following:
```tsx
// Tooltip.tsx L294
// track a ref to an invisible element
const didRenderChildrenRef = useRef<HTMLDivElement>(null);
useEffect(() => {
// log a warning if our invisible element did not render (signaling that our tooltip won't render either)
if (!didRenderChildrenRef.current) {
console.warn('Tooltip trigger element did not render children. To render a tooltip, the `trigger` element must accept and render `children`',
);
}
});
return React.cloneElement(trigger, {
children: (
<>
{trigger.props.children}
{tooltip}
<DidRender ref={didRenderChildrenRef} /> // render an …
```

Update Tooltip type docs

---

.changeset/violet-cougars-nail.md
packages/tokens/src/color/color.ts
packages/tokens/src/color/color.types.ts
packages/tokens/src/color/darkModeColors.ts
packages/tokens/src/color/lightModeColors.ts

Adds `satisfies` to ensure consistent & correct `colors` token structure

`color` token use `satistfies`

---

packages/tabs/README.md
packages/tabs/src/Tab/Tab.tsx
packages/tabs/src/TabPanel/TabPanel.styles.ts
packages/tabs/src/TabPanel/TabPanel.tsx
packages/tabs/src/TabPanel/TabPanel.types.ts
packages/tabs/src/TabTitle/TabTitle.tsx
packages/tabs/src/TabTitle/TabTitle.types.ts
packages/tabs/src/Tabs.spec.tsx
packages/tabs/src/Tabs.stories.tsx
packages/tabs/src/Tabs/Tabs.tsx
packages/tabs/src/Tabs/Tabs.types.ts
packages/tabs/src/context/TabsContext.ts
packages/tabs/src/context/index.ts
packages/tabs/src/utils/getTestUtils/getTestUtils.spec.tsx
packages/tabs/src/utils/getTestUtils/getTestUtils.ts
packages/tabs/src/utils/getTestUtils/getTestUtils.types.ts

`Tabs` changes
- adds `forceRenderAllTabPanels` prop with default value of `false` to `Tabs` component
`Tab` changes
- adds private `_shouldRender` prop to `Tab` component
- in `Tab`, conditionally renders entire `tabpanel` instead of `children`
- `_shouldRender` is true if:
- tab is not disabled, and
- either `forceRenderAllTabPanels` is propagated to children or tab is selected. if the former, tab is hidden with css
Test utils changes
- adds `getAllTabPanelsInDOM test util
- updates how `getSelectedPanel` queries for selected tab panel
Will make final changeset after all tabs changes are merged to integration branch
🎟 _Jira ticket:_ [LG-4147](https://jira.mongodb.org/browse/LG-4147)

LG-4147: forceRenderAllTabPanels prop

---

package.json

add .turbo to clean script

---

.changeset/strange-hounds-change.md
packages/testing-lib/package.json
packages/testing-lib/src/index.ts
packages/testing-lib/src/waitForTransition/index.ts
packages/testing-lib/src/waitForTransition/waitForTransition.spec.tsx
packages/testing-lib/src/waitForTransition/waitForTransition.ts
yarn.lock

Creates a `waitForTransition` test utility. Fires the `transitionend` event on a given element to ensure event handlers are called after CSS transitions complete. 
This is useful for testing `onEntered` or `onExited` callbacks on `Transition` or `Popover` elements.

Creates `waitForTransition` test utility

---

.changeset/honest-buses-explode.md
packages/copyable/src/Copyable.stories.tsx
packages/copyable/src/Copyable/Copyable.spec.tsx
packages/copyable/src/Copyable/Copyable.tsx

LG-4325: Exposes `onCopy` callback so that consuming applications can respond to successful clipboard events
🎟 _Jira ticket:_ [LG-4325](https://jira.mongodb.org/browse/[LG-4325)

LG-4325: Exposes `onCopy` callback so that consuming applications can respond to clipboard events

---

.changeset/sweet-rice-unite.md
packages/tokens/src/Tokens.stories.tsx
packages/tokens/src/spacing.ts

🎟 _Jira ticket:_ [LG-4341](https://jira.mongodb.org/browse/LG-4341)

LG-4341: Add 72px spacing token

---

.changeset/five-donkeys-fix.md
packages/polymorphic/src/InferredPolymorphic/InferredPolymorphic.types.spec.tsx
packages/polymorphic/src/InferredPolymorphic/InferredPolymorphic.types.ts
packages/polymorphic/src/Polymorphic/Polymorphic.types.ts

- `PolymorphicRef` extends `null`
- `PolymorphicProps` extends `ComponentPropsWithRef`
- Adds type specs for refs and event handlers

 Polymorphic patches

---

.changeset/afraid-ravens-build.md
packages/icon-button/package.json
packages/icon-button/src/styles.tsx

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/LG-4289)

LG-4289: Updates IconButton hover state

---

.changeset/moody-dancers-refuse.md
packages/modal/src/Modal/ModalView.tsx

[LG-4338](https://jira.mongodb.org/browse/LG-4338)

LG-4338: Normalizes Modal size property

---

.changeset/three-jobs-behave.md
packages/palette/src/Palette.stories.tsx
packages/palette/src/palette.ts

Adds `transparent` key to `palette`. Ensures a consistent `transparent` color across browsers
Notes:
Previously did not support this since `#rrggbbaa` format is not supported in IE11. We no longer need to support this browser 
https://caniuse.com/css-rrggbbaa

`palette.transparent`

---

.changeset/young-years-jog.md
packages/menu/src/MenuItem/MenuItem.spec.tsx
packages/menu/src/MenuItem/MenuItem.tsx
packages/menu/src/SubMenu/SubMenu.spec.tsx
packages/menu/src/SubMenu/SubMenu.tsx

Fixes a bug where click handlers on MenuItem or SubMenu would still fire when disabled

Disabled menu tests

---

.changeset/proud-avocados-burn.md
packages/toast/src/ControlledToast/ControlledToast.spec.tsx
packages/toast/src/ControlledToast/ControlledToast.tsx
packages/toast/src/ControlledToast/useStableControlledToastProps.tsx

The `ControlledToast` component was using a `props` object that was newly-created on every render, and then including it in a dependencies array for a `useEffect`. The `useEffect`'s cleanup callback was calling `popToast`, which triggers a re-render, so any time a component with an open controlled toast had a second render it would trigger an infinite render loop. This change is one possible way to avoid this, using `updateToast` instead of pop and push, storing some objects in refs (with deep `isEqual` comparisons to detect updates) to avoid triggering unnecessary re-renders, and separating the "unmount" effect from the "update" one.
🎟 _Jira ticket:_ [LG-4361](https://jira.mongodb.org/browse/LG-4361)
I added a simple unit test that would hang forever with the existing code, that should …

LG-4361 : Avoid most infinite render loops in ControlledToast

---

.changeset/mean-pandas-learn.md
.changeset/sour-kangaroos-sit.md
.changeset/swift-points-sip.md
packages/descendants/README.md
packages/descendants/src/Descendants.stories.tsx
packages/descendants/src/Descendants/Descendants.spec.tsx
packages/descendants/src/Descendants/useInitDescendants.tsx
packages/descendants/src/Highlight/Highlight.stories.tsx
packages/descendants/test/components.testutils.tsx
packages/descendants/test/renderDescendantsTestContext.testutils.tsx
packages/menu/src/Menu/Menu.tsx
packages/tabs/src/Tabs/Tabs.tsx

Updates `useInitDescendants` signature to require a Context value, and return a `Provider` component.
Eliminates the need to destructure `descendants` and `dispatch` from the hook's return value just to pass into the provider. Instead, the hook will construct a pre-populated provider unique to the Context value given.
Note: `descendants`, `dispatch` and `getDescendants` are still returned by the hook for use in the parent component if necessary.
Before:
```tsx
const MyDescendantContext = createDescendantsContext();
const { descendants, dispatch } = useInitDescendants();
return (
<DescendantsProvider
context={MyDescendantContext}
descendants={descendants}
dispatch={dispatch}
>
<MyDescendantItem />
</DescendantsProvider>
)
```
After:
```tsx
const MyDescendantContext = …
```

Descendants DX

---

.changeset/angry-donkeys-cross.md
.changeset/itchy-bikes-hear.md
packages/descendants/src/Highlight/index.ts
packages/descendants/src/index.ts
packages/menu/src/HighlightReducer/HighlightReducer.ts
packages/menu/src/HighlightReducer/highlight.types.ts
packages/menu/src/HighlightReducer/index.ts
packages/menu/src/Menu/Menu.tsx
packages/menu/src/MenuContext/GroupContext.tsx
packages/menu/src/MenuContext/MenuContext.tsx
packages/menu/src/MenuContext/SubMenuContext.tsx
packages/menu/src/MenuContext/index.ts
packages/menu/src/MenuItem/MenuItem.stories.tsx
packages/menu/src/MenuItem/MenuItem.types.ts
packages/menu/src/SubMenu/index.ts
packages/menu/src/index.ts
packages/menu/src/styles.ts
packages/menu/src/testUtils/withMenuContextDecorator.testutils.tsx
packages/menu/src/types.ts

Exports the following from `Menu`:
- `MenuDescendantsContext`
- Used to register and consume Menu descendants
- This context value allows you to register and track custom menu items
- Context hooks `useMenuContext`, `useMenuGroupContext`, & `useSubMenuContext`, along with types types `MenuContextData`, `MenuGroupContextData`, & `SubMenuContextData`,
- use these to read context data from custom menu item components
- `menuColor`: Custom color tokens used within `Menu` and related components
- `MenuInteractionState`: Enumerates interaction states on a menu item
- `LGIDs`: Unique ids for menu elements
- `menuItemClassName`: The unique class name for menu item components
- `subMenuContainerClassName` & `subMenuToggleClassName`
- Unique classnames for submenu elements
Also, adds missing …

Menu exports

---

packages/icon/package.json
yarn.lock

`Icon` builds currently freeze when running the Yarn `build` script if you don't have `ts-node` installed globally. This is because `ts-node` is run via `npx` instead of being stalled as a dependency. This PR fixes this by adding the `ts-node` dev dep to the `Icon` package.
1. Verify `ts-node` is not installed globally.
2. Re-run the `build` script via `yarn build`.

Fix `build` script

---

.changeset/honest-drinks-change.md
packages/hooks/src/hooks.spec.tsx
packages/hooks/src/useViewportSize.ts
packages/select/src/Select/Select.tsx

- Initialize viewport size with value instead of setting it in `useEffect` callback to prevent additional re-render.
🎟 _Jira ticket:_ [LG-3327](https://jira.mongodb.org/browse/LG-3327)
- Checked all live examples using the `useViewportSize()` hook
- Checked all live examples using the `useAvailableSpace()` hook, which uses `useViewportSize()`
- All previous tests passing

LG-3327: Prevent re-render in `useViewportSize`

---

.changeset/twenty-pans-promise.md
packages/hooks/src/useDynamicRefs/index.ts

Makes `prefix` argument optional for `useDynamicRefs`.
🎟 _Jira ticket:_ [LG-3553](https://jira.mongodb.org/browse/[LG-3553])

LG-3553: Make `prefix` argument optional for `useDynamicRefs`

---

.changeset/tough-trees-trade.md
packages/toast/src/ToastContainer/utils/useToastHeights.ts
packages/toast/src/ToastContainer/utils/useToastTransitions.ts

There are a number of `debounce` functions that are not currently cancelled on unmount. This PR cancel those.
🎟 _Jira ticket:_ [LG-4335](https://jira.mongodb.org/browse/LG-4335)

LG-4335: Clean up running tasks in `Toast`

---

tools/test/README.md

Added to README:
In CI we test our components using React 17.
To do this manually, first run the [init script](./scripts/install-react17.ts) in order to install the specific testing dependencies needed for React 17. (`yarn init17` from the repo root)
```bash
> yarn init17
```
Next, run your tests with the `--react17` flag. This ensures that the tests are run with specific Jest config for React 17.
```bash
> yarn test --react17
```
To go back to the default version of React you'll need to clear your packages and re-build:
```
> yarn clean:modules && yarn run init
```

Updates `tools/test` README

---

.changeset/dull-pianos-rest.md
packages/skeleton-loader/README.md
packages/skeleton-loader/src/TableSkeleton/TableSkeleton.types.ts

- Extends `TableSkeleton` component's `columnLabels` prop type from `Array<string | undefined>` to `Array<React.ReactNode>`
🎟 _Jira ticket:_ [LG-4604](https://jira.mongodb.org/browse/LG-4604)

LG-4604: extend TableSkeleton component columnLabels prop type

---

.changeset/quick-insects-smash.md
tools/validate/src/dependencies/config.ts

Updates `@lg-tools/validate` with the following change:
Updates `devFilePatterns`, and will exclude all files in `test/` `testing/` or `test-utilities/` directories from explicit dep. checks. i.e. Files in these directories will only need to have their imports listed s `devDependencies` in the `package.json`

Validate test file dev deps

---

.changeset/silly-jars-cheat.md
charts/core/README.md
charts/core/src/XAxis/XAxis.tsx
charts/core/src/XAxis/XAxis.types.ts
charts/core/src/YAxis/YAxis.tsx
charts/core/src/YAxis/YAxis.types.ts
charts/core/src/core.stories.tsx

- Replace `unit` prop of `XAxis` and `YAxis` with `formatter` prop.
🎟 _Jira ticket:_ [LG-4659](https://jira.mongodb.org/browse/LG-4659)
- Use it in Storybook

LG-4659: Replace axes `unit` prop with `formatter`

---

.changeset/red-goats-doubt.md
packages/tabs/src/Tabs/Tabs.types.ts

🎟 _Jira ticket:_ [LG-4680](https://jira.mongodb.org/browse/[LG-4680])

LG-4680:  `Tabs` removes `setSelectedd` prop

---

.changeset/grumpy-dogs-crash.md
charts/core/README.md
charts/core/src/Chart.stories.tsx
charts/core/src/Chart/Chart.tsx
charts/core/src/Chart/Chart.types.ts
charts/core/src/Chart/hooks/useChart.ts
charts/core/src/Chart/hooks/useChart.types.ts

Adds the ability to synchronize tooltips across charts
🎟 _Jira ticket:_ [LG-4577](https://jira.mongodb.org/browse/LG-4577)
Check 'With Same Group Ids' story in Storybook

LG-4577: Implement syncing tooltips across charts

---

.changeset/six-berries-dance.md
charts/core/README.md
charts/core/src/Chart.stories.tsx
charts/core/src/Chart/Chart.tsx
charts/core/src/Chart/Chart.types.ts
charts/core/src/Chart/hooks/useChart.ts
charts/core/src/Chart/hooks/useChart.types.ts

It was an ask from consumers that they be able to optionally turn zoom selection on and off for axis. This change primarily adds that.
Note, this also updates the component's props. Previously we decided to just allow the handler to turn off and on the select-ability. Since now there is an option to enable it by axis, it made sense to just create a `zoomSelect` prop, that configures zoom selection. I like this approach better as a) the name `zoomSelect` clearer communicates that we're not actually zooming on data, and b) it removes the implied enablement of the previous design that none of us were crazy about.
🎟 _Jira ticket:_ [LG-4698](https://jira.mongodb.org/browse/LG-4698)
Added to storybook so it can now be tested there.

LG-4698: Allow choosing of axis for zoom selection 

---

.changeset/perfect-cups-film.md
charts/core/src/ChartCard/ChartCard.stories.tsx
charts/core/src/Tooltip/Tooltip.tsx

Appends the `Tooltip` to `body` in order to prevent the cutoff, as proposed in solution here: https://github.com/apache/echarts/issues/5955
🎟 _Jira ticket:_ [LG-4703](https://jira.mongodb.org/browse/LG-4703)
I have added more lines to all `ChartCard` stories to show that it's working

LG-4703: Fix large `Tooltip` being cutoff by `ChartCard`

---

packages/date-utils/src/getDaysInUTCMonth/getDaysInUTCMonth.spec.ts

I got this failure when running tests locally.
I suspect this is because `Date` objects constructed from numeric values will depend on the computers locale settings: I'm on a computer with locale set as "Danish / Denmark".
🎟 _Jira ticket:_ Not tracked on Jira.
☝️ doesn't seem appropriate as this is changing only tests.

Make tests locale independent

---

.changeset/tame-panthers-knock.md
packages/split-button/src/Menu/Menu.tsx
packages/split-button/src/SplitButton/SplitButton.spec.tsx

I propose removing a check for the `open` prop (`controlledOpen` internally) of the `SplitButton`'s internal `Menu` component to unconditionally call any `setOpen` function passed via props.
I've also included a few (hopefully not too controversial) improvements to the tests, now I was there. Let me know if I should split those into a separate PR 👍
🎟 _Jira ticket:_ [LG-4714](https://jira.mongodb.org/browse/LG-4714)
I've added a failing test which pass after applying the fix.

LG-4714: Fix using `SplitButton` as a managed component

---

.changeset/chilled-hounds-laugh.md
packages/split-button/src/SplitButton/SplitButton.types.ts

As per my suggestion in https://github.com/mongodb/leafygreen-ui/pull/2601, future regressions could be avoided if the types derived from `MenuProps` intended for pass-through is allow-listed via a `Pick` instead of deny-listed via `Omit`.
This change is breaking, since it's removing a lot of props from the `SplitButton` which were never actually passed through to the `Menu`.
- Add the `@leafygreen-ui/split-button` to a project
- Observe how the `onEnter` prop are available on the `SplitButton`.
- Apply this patch.
- Observe how the `onEnter` prop are no longer available on the `SplitButton`.

Refactored SplitButton (breaking - take 2)

---

.changeset/grumpy-moose-exercise.md
packages/card/src/Card/Card.tsx
packages/card/src/Card/types.ts
packages/input-option/src/InputOption/InputOption.tsx
packages/input-option/src/InputOption/InputOption.types.ts
packages/menu/src/MenuItem/InternalMenuItemContent.tsx
packages/menu/src/MenuItem/MenuItem.tsx
packages/menu/src/MenuItem/MenuItem.types.ts
packages/menu/src/SubMenu/SubMenu.tsx
packages/menu/src/SubMenu/SubMenu.types.ts
packages/search-input/src/SearchResult/SearchResult.tsx
packages/search-input/src/SearchResult/SearchResult.types.ts
packages/split-button/src/Menu/Menu.tsx
packages/split-button/src/SplitButton/SplitButton.tsx
packages/split-button/src/SplitButton/SplitButton.types.ts

This PR is a re-creation of https://github.com/mongodb/leafygreen-ui/pull/2609 (using a branch on the repo instead of from my personal fork).
I went through the codebase to find uses of the "polymorphic" types and replicated the pattern already established for the `SubMenu` component:
- Prepended the `*Props` type name with "Internal".
- Updated the internal use of ☝️ to match the new name.
- Added a new type in-place of the type which was previously exported, wrapping the internal type in either `PolymorphicProps` or `InferredPolymorphicProps` (depending on which was used by the implementation of the component).
I'm marking this as a patch, since it's extending the existing prop types and therefore shouldn't cause downstream breakage. If a consumer is wrapping these types already this …

LG-4724: Export prop types which are already wrapped in the polymorphic types (re-created)

---

charts/core/CHANGELOG.md
charts/core/package.json

Bump down charts from v1.0.0 to v0.9.0 after accidental bump

Bump down charts from v1.0.0 to v0.9.0

---

.changeset/sour-bottles-sip.md
charts/core/src/Echart/useEchart.ts

Resizing didn't trigger a resize of the chart because the echart instance was null from the callback.
Creates the callback inside of the initialization hook to make sure it is accessible from the callback.
🎟 _Jira ticket:_ [LG-4743](https://jira.mongodb.org/browse/LG-4743)
- Test in storybook by resizing the browser and confirming that the chart resizes correctly and that there are no errors in the console.

LG-4743: Fix resize bug in charts

---

.changeset/sour-tables-wonder.md
charts/core/src/Echart/useEchart.ts

Actually fix blurriness, at least on the large monitor I'm viewing it on. It appears there's an ongoing issue about [charts appearing blurry on canvas in echarts](https://github.com/apache/echarts/issues/13504). I also see that in the [echarts examples](https://echarts.apache.org/examples/en/editor.html?c=data-transform-filter), if I set the `lineStyle` of a series to a width of 1, I see the same level of "not perfectly smooth" as I see in our chart. 
Ensures that the the canvas is being sized correctly to the container and the correct pixel ratio is being used. There was a report of line blurriness occurring intermittently when users would return to their chart. I have yet to see this or be able to reproduce this. By making this change we're hopefully doing everything we can to ensure …

LG-4634: Ensure canvas is sized to container with correct pixel ratio

---

.changeset/fuzzy-moons-sneeze.md
charts/core/src/Chart/hooks/useChart.spec.ts
charts/core/src/Chart/hooks/useChart.ts
charts/core/src/Echart/useEchart.ts

- Removes chart groups when chart unmounts
- Drive-by: Prevents unneeded group connecting if group already exists on instance
🎟 _Jira ticket:_ [LG-4770](https://jira.mongodb.org/browse/LG-4770)
- In storybook, run through reproduction steps in attached ticket and confirm duplicate tooltips aren't seen

LG-4770: Fix duplicate tooltip in remounted chart groups

---

.github/workflows/release.yml

This should be fine since the only files that could possibly be changed in ci are: `pnpm-lock` , `*/dist` and `.npmrc` . We want the `*/dist` to change, and we guard against lockfile changes with the `--frozen-lockfile` flag

Release with no git checks

---

.changeset/big-drinks-thank.md
packages/split-button/src/Menu/Menu.tsx
packages/split-button/src/SplitButton/SplitButton.spec.tsx
packages/split-button/src/SplitButton/SplitButton.tsx
packages/split-button/src/SplitButton/SplitButton.types.ts
packages/split-button/src/constants.ts
packages/split-button/src/index.ts

In an effort to make out tests more robust to future changes, I suggest adding a `data-testid` attribute so the `SplitButton` trigger button can be targeted directly.

Add `data-testid` attribute to `SplitButton`'s menu trigger element

---

.changeset/big-tables-carry.md
packages/table/src/useLeafyGreenTable/useLeafyGreenTable.spec.tsx
packages/table/src/useLeafyGreenTable/useLeafyGreenTable.tsx

Merging this PR will:
1. Add a failing test to demonstrate the issue and prevent future regressions.
2. Move the `state` value below the `...rest` spread in `useLeafyGreenTable` when passing values to the `useReactTable`.
🎟 _Jira ticket:_ [LG-4796](https://jira.mongodb.org/browse/LG-4796)
I've added a test:
```bash
pnpm test packages/table/src/useLeafyGreenTable
```

LG-4796: Fix expanding when passing `state` to `useLeafyGreenTable`

---

.changeset/slimy-paws-listen.md
charts/core/README.md
charts/core/package.json
charts/core/src/Chart.stories.tsx
charts/core/src/Chart/Chart.styles.ts
charts/core/src/Chart/Chart.tsx
charts/core/src/Chart/Chart.types.ts
charts/core/src/Chart/index.ts
charts/core/src/index.ts
charts/core/tsconfig.json
pnpm-lock.yaml

- Adds a loading state to the `Chart` component
- [Designs](https://www.figma.com/design/GA4jw1p4unetIzbamqahkD/DS_Metrics?node-id=1607-28780&m=dev&focus-id=467-51724)
🎟 _Jira ticket:_ [LG-4622](https://jira.mongodb.org/browse/LG-4622)
Test via `isLoading` prop in storybook

LG-4622: Adds a loading state to the `Chart` component

---

.changeset/fifty-bears-clap.md
chat/message-feed/package.json
chat/message-feed/src/MessageFeed.stories.tsx
chat/message-feed/src/MessageFeed/MessageFeed.styles.ts
chat/message-feed/src/MessageFeed/MessageFeed.tsx
pnpm-lock.yaml

🎟 _Jira ticket:_ [LG-4789](https://jira.mongodb.org/browse/LG-4789)
https://github.com/user-attachments/assets/8b4276e7-917a-4ff7-aa69-bbfb1527735f

LG-4789: Chat MessageFeed Scroll to Latest Button

---

.changeset/happy-sheep-kick.md
charts/core/src/Chart.stories.tsx
charts/core/src/Chart/Chart.styles.ts
charts/core/src/Chart/Chart.tsx
charts/core/src/Chart/hooks/useChart.ts
charts/core/src/Echart/Echart.types.ts
charts/core/src/Echart/useEchart.spec.ts
charts/core/src/Echart/useEchart.ts

- Currently, resizing only works if the browser resizes. However, if the container gets dynamically resized, such as when a sidebar opens, it doesn't currently resize. This PR switches to instead using a `ResizeObserver` on the chart container to trigger resize.
🎟 _Jira ticket:_ [LG-4797](https://jira.mongodb.org/browse/LG-4797)
- New story added for "Resizing with container" where you can dynamically resize the container and make sure the chart shrinks and expands correctly
- Can also test that browser resizing also still works on the live example

LG-4797: Fix charts not resizing when container dynamically changes

---

.changeset/ten-spies-breathe.md
charts/core/package.json
charts/core/src/Chart.stories.tsx
charts/core/src/Chart/Chart.styles.ts
charts/core/src/Chart/Chart.tsx
pnpm-lock.yaml

This had 2 issues:
1. Lottie is currently breaking SSR components in updated LTS versions of Node.
2. Lottie is very heavy for what it's doing. This bloated the package size significantly.
It was decided to just remove the spinner altogether from now from this state.
- Verify in Storybook by updating the `ChartState` prop to "loading"

Remove `loading-indicator` / `lottie` dependency from `@lg-charts/core`

---

.changeset/forty-steaks-wash.md
packages/menu/src/Menu/utils/useMenuHeight.ts

I believe this was a mostly incorrect claim. We only have one import of `lodash` that isn't importing the module directly. The confusion might be due to the existence of `lodash-es` which is a more modern alternative with ESM support, providing treeshaking out of the box, but there shouldn't be a significant bundle size decrease using it compared to just importing the module.
🎟 _Jira ticket:_ [LG-4737](https://jira.mongodb.org/browse/LG-4737)

LG-4737: Remove full `lodash` import from `Menu`

---

.changeset/cold-tables-jam.md
packages/combobox/src/Combobox/Combobox.spec.tsx
packages/combobox/src/Combobox/Combobox.tsx

Fix option highlighting on re-open after selection by reseting the highlight back to the first option whenever the menu closes.
🎟 _Jira ticket:_ [LG-3955](https://jira.mongodb.org/browse/LG-3955)
- New tests passing (were failing on old logic)
- Everything working as expected in Storybook

LG-3955: Combobox shows incorrect highlight after making selection

---

.changeset/angry-mice-return.md
packages/number-input/src/Input/Input.spec.tsx
packages/number-input/src/Input/Input.types.ts
packages/number-input/src/NumberInput/NumberInput.tsx
packages/number-input/src/NumberInput/NumberInput.types.ts

🎟 _Jira ticket:_ [LG-4833](https://jira.mongodb.org/browse/LG-4833)

LG-4833: Remove `errorMessage` from native input

---

.changeset/tricky-points-design.md
packages/popover/src/Popover/Popover.styles.ts

- remove unused `@starting-style` rule from `Popover` styles
- this will also address console errors due to `js-dom` not being able to parse `@starting-style`
🎟 _Jira ticket:_ [LG-4844](https://jira.mongodb.org/browse/LG-4844)

Remove unused @starting-style rule from Popover

---

.changeset/calm-hounds-roll.md
packages/typography/src/Typography.stories.tsx

Changes Storybook name for Typography Live Example to properly render on .design

---

.changeset/witty-llamas-rest.md
chat/message/src/Message/Message.stories.tsx
chat/message/src/Message/Message.styles.ts
chat/message/src/Message/Message.tsx

- Properly sets dark mode font color when `sourceType` is `text`
🎟 _Jira ticket:_ [LG-4736](https://jira.mongodb.org/browse/LG-4736)
- Check storybook `?path=/story/chat-message--text&args=darkMode:!true` to verify working as expected
- Check other `?path=/story/chat-message--*` stories in both dark and light modes to verify all is still working as expected
- Chromatic tests are passing

LG-4736: Fix colors of LG Chat Messages in dark mode

---

.changeset/funny-moons-share.md
packages/text-area/src/TextArea.stories.tsx
packages/text-area/src/TextArea/TextArea.spec.tsx
packages/text-area/src/TextArea/TextArea.tsx
packages/text-input/src/TextInput.stories.tsx
packages/text-input/src/TextInput/TextInput.spec.tsx

🎟 _Jira ticket:_ [LG-4866](https://jira.mongodb.org/browse/LG-4866)

LG-4866: pass readOnly to textarea

---

packages/icon/turbo.json
turbo.json

- Adds inputs/outputs to `icon` prebuild step. This allows caching of the generated icons
- Adds "prebuild" as a dependency of running ts builds
Build only: no changeset needed

Update turbo configs

---

packages/icon/turbo.json

I just pulled `main`, did a `git clean` and `pnpm install` and now when running `pnpm run build` I'm getting:
```
@leafygreen-ui/icon:build: 
@leafygreen-ui/icon:build: > @leafygreen-ui/icon@13.1.2 prebuild /Users/kraen.hansen/Repositories/leafygreen-ui/packages/icon
@leafygreen-ui/icon:build: > ts-node ./scripts/prebuild.ts --files
@leafygreen-ui/icon:build: 
@leafygreen-ui/toggle:tsc: 
@leafygreen-ui/toggle:tsc: > @leafygreen-ui/toggle@11.0.2 tsc /Users/kraen.hansen/Repositories/leafygreen-ui/packages/toggle
@leafygreen-ui/toggle:tsc: > lg build-ts
@leafygreen-ui/toggle:tsc: 
@leafygreen-ui/icon:build: 
@leafygreen-ui/icon:build: > @leafygreen-ui/icon@13.1.2 build /Users/kraen.hansen/Repositories/leafygreen-ui/packages/icon
@leafygreen-ui/icon:build: > lg build-package …
```

Include `^tsc` of upstream deps as a depend task of icon's `prebuild` task

---

.github/workflows/release.yml

Updates `release.yml` to create a GH release on publish (`createGithubReleases`)
[LG-4973](https://jira.mongodb.org/browse/LG-4973)

Restore github releases on publish [LG-4973]

---

.changeset/build-cli-verbose.md
.changeset/icon-update-build.md
packages/icon/tsconfig.json
packages/icon/turbo.json
tools/build/src/typescript/build-ts.ts
turbo.json

Logs `tsconfig.json` path for `--verbose` flag in build script
Adds `glyphs/index.ts` to prebuild cache `turbo.json` 
Removes reference path `"@leafygreen-ui/icon/dist/*"` from `tsconfig.json`
🎟 _Jira ticket:_ [LG-5014](https://jira.mongodb.org/browse/LG-5014)

Update turbo configs [LG-5014]

---

.changeset/validate-build-package-json.md
tools/validate/src/builds/getModuleTypes.ts
tools/validate/src/builds/index.ts
tools/validate/src/index.ts

`@lg-tools/validate`: patch
---
Updates build validation to use the entry files defined in the package.json
Changing the entry point in the package.json  (e.g. `main`, `module` or `types`) can break the bundle.
This change ensures that the bundle files exist in the directory we say they'll be in

Validate builds based on `package.json`

---

.changeset/cold-planes-listen.md
charts/core/src/Chart/config/getDefaultChartOptions.ts
charts/core/src/ChartTooltip/ChartTooltip.tsx

Currently the vertical line that displays on hover, which also shows the colored points, only shows IF the ChartTooltip rendered. Instead we want that line to just always show on hover, even when the ChartTooltip isn't rendered.
🎟 _Jira ticket:_ [LG-5090](https://jira.mongodb.org/browse/LG-5090)
Charts > Core > Basic Storybook

Always show hover line on charts

---

.changeset/popover-ref-el.md
packages/popover/package.json
packages/popover/src/Popover/Popover.tsx
packages/popover/src/Popover/hooks/Popover.hooks.spec.ts
packages/popover/src/Popover/hooks/Popover.hooks.ts
packages/popover/src/Popover/hooks/index.ts
pnpm-lock.yaml

`@leafygreen-ui/popover`: patch
---
Updates reference element positioning logic to ensure the correct element is used as a reference in cases where the element `ref` or DOM node changes in between renders.
I believe this is the root cause of https://jira.mongodb.org/browse/LG-5066

Update Popover Reference element on rerender

---

charts/core/src/Chart.stories.tsx
charts/drag-provider/src/DragProvider.stories.tsx

Bumps the canvas threshold on charts in attempt to avoid false negatives that keep occurring.

chore(charts): adjust chromatic diffThreshold for charts

---

.changeset/todo-charts.md
.changeset/todo-polymorphic.md
charts/core/src/Echart/Echart.types.ts
charts/core/src/XAxis/XAxis.tsx
charts/core/src/XAxis/XAxis.types.ts
charts/core/src/YAxis/YAxis.tsx
charts/core/src/YAxis/YAxis.types.ts
packages/box/src/Box.tsx
packages/callout/src/Callout.stories.tsx
packages/callout/src/Callout/Callout.types.ts
packages/code/src/CopyButton/CopyButton.spec.tsx
packages/combobox/src/Combobox/Combobox.spec.tsx
packages/date-picker/src/DatePicker/DatePickerContext/useDatePickerComponentRefs.ts
packages/polymorphic/src/Polymorphic/Polymorph.tsx
packages/polymorphic/src/Polymorphic/Polymorphic.types.ts

[LG-5064](https://jira.mongodb.org/browse/LG-5064)
`@lg-charts/core`: patch
---
Updates axis `formatter` prop signature to match echarts.
```ts
{
formatter?: (value: number, index?: number) => string | string;
}
```
`@leafygreen-ui/polymorphic`: patch
---
Replace `ReactElement` with `ReactNode` in type definitions

LG-5064: resolve outstanding TS TODOs

---

.changeset/hip-goats-rule.md
packages/tooltip/src/Tooltip.stories.tsx
packages/tooltip/src/Tooltip/Tooltip.spec.tsx
packages/tooltip/src/Tooltip/Tooltip.tsx
packages/tooltip/src/Tooltip/Tooltip.types.ts

Originally, tooltip triggers passed as functions may have styles overwritten if they use class names. Tooltip triggers passed as functions are now called to get a reference to the component's original class names, which are then applied as a combination rather than an overwrite.
🎟 _Jira ticket:_ [Tooltip trigger requires implicit pass-through className](https://jira.mongodb.org/browse/LG-4217])

LG-4217: retain className styles for tooltip triggers passed as functions

---

packages/search-input/src/SearchResultsMenu/SearchResultsMenu.style.ts

Scroll behavior of search input dropdown now matches select dropdown - padding only exists at top and bottom, not while scrolling.
🎟 _Jira ticket:_ [LG-3568](https://jira.mongodb.org/browse/LG-3568)

LG-3568: search input dropdown cutoff

---

.changeset/descendants-missing-types.md
packages/descendants/src/Highlight/index.ts
packages/descendants/src/index.ts

`@leafygreen-ui/descendants`: patch
---
Exports missing `UseHighlightOptions` and `HighlightContextType` types

Exports missing descendants highlight type

---

.changeset/itchy-things-know.md
charts/core/README.md
charts/core/src/Chart.stories.tsx
charts/core/src/Line/Line.types.ts

- Updates types to allow `null` and `undefined` values in data points. This allows consumers to skip over points on the line which was a requested feature.
- Drive by fix to correct README examples.
🎟 _Jira ticket:_ [LG-5338](https://jira.mongodb.org/browse/LG-5338)
- Visual regression story added in Storybook for null values

LG-5338: Allow `null` and `undefined` values in data points

---

packages/drawer/src/DrawerToolbarLayout/DrawerWithToolbarWrapper/DrawerWithToolbarWrapper.tsx

There were some changes to the layout components in the resizable work, which accidentally introduced a flicker to an overlay drawer. This change prevents that flicker from happening.
Check out any Drawer/Toolbar/ overlay story and open the drawer. There should not be a flicker.
story with flicker: https://storybook.mongodb.design/?path=/story/sections-drawer-toolbar--overlay
story without flicker: https://642700aa3e49e32bdbf0b0fc-iaebwbrvoy.chromatic.com/?path=/story/sections-drawer-toolbar--overlay

refactor(DrawerWithToolbarWrapper): Fix overlay drawer flicker on open

---

.vscode/settings.json

At some point VSCode (and Cursor) started opening `.svg` files in the image preview. 
IMO we should set the default back to text editor (done here)
(if others disagree, I can close this ticket and just update my user settings)

chore(vscode) adds default .svg editor

---

.changeset/flat-carrots-change.md
packages/code/src/Code.stories.tsx
packages/code/src/Code/Code.spec.tsx
packages/code/src/LanguageSwitcher/LanguageSwitcherExample.tsx
packages/code/src/Panel/Panel.tsx
packages/code/src/testing/Code.testutils.tsx
packages/code/src/testing/getTestUtils.spec.tsx

Fixes a bug in the Code component that prevented the language select from rendering when the `displayName` and `language` properties differed in the language options. The issue was in the Panel component's logic for finding the current language, which only matched against `displayName` but not against the `language` property itself.
The fix updates the language matching logic to check both `displayName` and `language` properties, enabling proper rendering of the language selector in cases where these values differ (e.g., displayName: "macOS", language: "shell").
🎟️ _Jira ticket:_ [LG-5463](https://jira.mongodb.org/browse/LG-5463)
View the `With Language Switcher` story
1. Create a Code component with language options where `displayName` and `language` differ:
```tsx
const languageOptions …
```

[LG-5463] fix(code): fix language select rendering when displayName and language differ

---

.changeset/chart-card-import-layout-fixes.md
charts/chart-card/src/ChartCard.stories.tsx
charts/chart-card/src/ChartCard/ChartCard.styles.ts

This PR fixes import references and header layout issues in the ChartCard component. The changes update the component to use the correct `ChartHeaderProps` type from the core charts package instead of a local `HeaderProps` type, and adjusts the grid layout to properly position header elements.
[LG-5489](https://jira.mongodb.org/browse/LG-5489)
1. Navigate to the ChartCard Storybook stories
2. Verify that the component renders without TypeScript errors
3. Check that the header layout displays correctly with the title positioned on the left and additional content on the right
4. Confirm that all existing functionality remains intact

[LG-5489] fix(chart-card): fix header layout

---

packages/code-editor/src/CodeEditor.stories.tsx
packages/code-editor/src/ShortcutTable/ShortcutTable.styles.ts
packages/code-editor/src/ShortcutTable/ShortcutTable.tsx

- Adds `LeafyGreenProvider` to storybook so dark mode works as expected
- Fixes display of disclaimer plus signs in the shortcuts table
🎟 _Jira ticket:_ [LG-5516](https://jira.mongodb.org/browse/LG-5516)
- View storybook

[LG-5516] chore/bug(CodeEditor): Fixed darkmode in storybook and shortcuts table styling

---

.changeset/icy-bushes-lie.md
packages/emotion/src/version.ts
packages/icon-button/src/IconButton/IconButton.spec.tsx

Re-enables the TypeScript type check that was previously commented out to ensure the IconButton component requires either `aria-label` or `aria-labelledby` properties. This change enforces accessibility best practices by guaranteeing that interactive icon buttons have proper screen reader labels, preventing accessibility violations from reaching production.
1. **TypeScript compilation**: Try to use `<IconButton />` without `aria-label` or `aria-labelledby` props - TypeScript should now throw a compilation error
2. **Valid usage**: Verify that `<IconButton aria-label="Close" />` and `<IconButton aria-labelledby="button-label" />` compile successfully
3. **Existing tests**: Run the icon-button test suite to ensure no regressions: `pnpm test packages/icon-button`
4. **Accessibility …

Accessible Labels in IconButton component 

---

packages/code-editor/src/CodeEditor/hooks/extensions/useAutoCompleteExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useCodeFoldingExtension.spec.tsx
packages/code-editor/src/CodeEditor/hooks/extensions/useExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useExtensions.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useHighlightExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useHyperLinkExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useIndentExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useLanguageExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useLineNumbersExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useLineWrapExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/usePlaceholderExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useReadOnlyExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useThemeExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/extensions/useTooltipExtension.spec.ts
packages/code-editor/src/CodeEditor/hooks/formatting/formatters.ts
packages/code-editor/src/CodeEditor/hooks/formatting/useCodeFormatter.spec.ts
packages/code-editor/src/CodeEditor/hooks/formatting/useFormattingModuleLoaders.spec.ts
packages/code-editor/src/CodeEditor/hooks/useLazyModules.spec.ts
packages/code-editor/src/CodeEditor/hooks/useModuleLoaders.spec.ts

- The `as const` assertions were causing type issues when with `formatWithWasm` function.
- `renderHook` needs to be imported from `@leafygreen-ui/testing-lib` so the correct function is imported in R17.
- Verify CI build is passing successfully.

fix(CodeEditor): fix tests after R17 update

---

.changeset/sixty-trees-rescue.md
packages/table/src/ExpandedContent/ExpandedContent.spec.tsx
packages/table/src/ExpandedContent/ExpandedContent.tsx
packages/table/src/testing/getTestUtils.spec.tsx
packages/table/src/utils/stories.testutils.tsx

Merging this PR will:
- Add a type assert to `ExtendedContent` similar to the one already on the `Row`: https://github.com/mongodb/leafygreen-ui/blob/bda06c5d9901ebb06c71ebb078d4c9c33cf3a729/packages/table/src/Row/Row.tsx#L61
🎟 _Jira ticket:_ [LG-5589](https://jira.mongodb.org/browse/LG-5589)
I'm curious about [this comment in the tests](https://github.com/mongodb/leafygreen-ui/blob/bda06c5d9901ebb06c71ebb078d4c9c33cf3a729/packages/table/src/ExpandedContent/ExpandedContent.spec.tsx#L179):
> ExpandedContent is incorrectly generic
Does that mean the ExpandedContent needs a refactor to remove it's generic T all together?

[LG-5589] fix(table): add type assert to allow passing `row` to `ExtendedContent`
