mongodb/leafygreen-ui

- packages/Portal/package.json
Version 2.1.2 is not yet on NPM
> PD-233: Changing the Portal Component lib dependency

- packages/Checkbox/src/Checkbox.js
- packages/lib/src/emotion.js
- packages/lib/src/index.js
- packages/lib/src/index.ts
- tsconfig.json
- webpack.config.js
https://jira.mongodb.org/browse/PD-220
> PD-220: Migrate Checkbox to not use interpolated classNames

- .github/pull_request_template.md
Never again will PR descriptions look like this...
> PD-228: Add pull request template

- README.md
- package.json
- storybook/theme.js
Updates instances of `https://github.com/10gen/leafygreen-ui` to ``https://github.com/10gen/leafygreen-ui``
🎟 **Jira ticket:** [Update links to 10gen repository to point to mongodb/leafygreen-ui](https://jira.mongodb.org/browse/PD-240)
> Update instances of 10gen repository link to be 'mongodb'

- jest.config.js
- package-lock.json
- package.json
Previously, tests written in `ts` or `tsx` wouldn't run. This fixes that issue.
> Configure Jest for TypeScript tests

- .eslintrc
Eslint is getting angry about the .tsx file extension. This fixes that issue.
> Update eslintrc to include TSX as a valid JSX file extension

- packages/Badge/README.md
- packages/Button/README.md
- packages/Checkbox/README.md
- packages/Icon/README.md
- packages/Portal/README.md
- packages/RadioBoxGroup/README.md
- packages/RadioGroup/README.md
- packages/Toggle/README.md
This PR adds version badges to the README for each package.
> Add NPM version badges to README

- .eslintrc
- .prettierrc
- package.json
- packages/Badge/src/Badge.js
- packages/Checkbox/src/Checkbox.js
- packages/Portal/src/Portal.js
- webpack.config.js
Updated Prettier and Linter rules. Additionally added two new npm scripts, one to run both prettier and linter and one just to run and enforce the rules from our linter.
🎟 _Jira ticket:_ [PD-172](https://jira.mongodb.org/secure/RapidBoard.jspa?rapidView=977&view=detail&selectedIssue=PD-172)
- [ x] New feature (non-breaking change which adds functionality)
> PD-172: Updating Internal Linting/Prettier Rules

- packages/Button/src/Button.js
This one is much simpler than Toggle. Since we're rendering a single element, we can continue to rely on CSS pseudo-classes for disabled and such, and simply convert `ccClassName` to `cx`.
🎟 _Jira ticket:_ [Fix Emotion 10 console errors](https://jira.mongodb.org/browse/PD-220)
> PD-220: Convert ccClassName to cx in Button

- packages/RadioGroup/src/Radio.js
Small refactor of Radio to use JS state and cx to get rid of console errors.
🎟 _Jira ticket:_ [Fix Emotion 10 console errors](https://jira.mongodb.org/browse/PD-220)
> PD-220: Refactor Radio to use cx, and JS state

- packages/Badge/package.json
- packages/Button/package.json
- packages/Checkbox/package.json
- packages/Icon/package.json
- packages/Portal/package.json
- packages/RadioBoxGroup/package.json
- packages/RadioGroup/package.json
- packages/Toggle/package.json
- packages/lib/package.json
- packages/theme/package.json
Version bumps all around for our new package versions, now published on NPM.
> Publish icon

- packages/Checkbox/src/Checkbox.js
Updated Checkbox styles based on implementation needs in MMS.
🎟 _Jira ticket:_ [PD-255](https://jira.mongodb.org/browse/PD-255)
> style(checkbox): updated checkbox label styles

- package.json
- packages/Badge/package.json
- packages/Button/package.json
- packages/Checkbox/package.json
- packages/Icon/package.json
- packages/Portal/package.json
- packages/RadioBoxGroup/package.json
- packages/RadioGroup/package.json
- packages/Toggle/package.json
- packages/lib/package.json
- packages/theme/package.json
This bumps the Checkbox version because of two breaking changes that were necessary to convert the MMS checkboxes:
1. Updates the checkbox style to better accommodate certain elements passed through the `label` slot.
2. Properly applies inline styles to the outermost element of the component rather than the checkbox input.
This also disables commit linting when releasing packages with lerna.
> Publish checkbox

- packages/Badge/src/Badge.js
Make all badges same height regardless of outline
🎟 _Jira ticket:_ [Name of ticket](https://my.jira/ticket)
> fix(badge): make all badges same height

- packages/Badge/package.json
- packages/Button/package.json
- packages/Checkbox/package.json
- packages/Icon/package.json
- packages/Popover/package.json
- packages/Portal/package.json
- packages/RadioBoxGroup/package.json
- packages/RadioGroup/package.json
- packages/Toggle/package.json
- packages/lib/package.json
- packages/theme/package.json
Updated package.json files from `npm run release`
> Update package.json files from `npm run release`

- packages/Popover/src/Popover.tsx
reset pointer events in active state
> fix(popover): corrected pointer events in active state

- packages/Checkbox/src/Checkbox.js
Updates the alignment between the checkbox label and the input itself to be optically-aligned, and closer together.
🎟 **Jira ticket:** [Adjust Checkbox alignment and spacing](https://jira.mongodb.org/browse/PD-265)
> PD-265: Update checkbox alignment to be optically-aligned

- packages/Popover/src/Popover.tsx
- packages/Popover/src/hooks.ts
🎟 _Jira ticket:_ [Name of ticket](https://my.jira/ticket)
> fix(popover): correctly calculate rect values on first render

- packages/Badge/package.json
- packages/Button/package.json
- packages/Checkbox/package.json
- packages/Icon/package.json
- packages/Popover/package.json
- packages/Portal/package.json
- packages/RadioBoxGroup/package.json
- packages/RadioGroup/package.json
- packages/Toggle/package.json
- packages/lib/package.json
- packages/theme/package.json
- @leafygreen-ui/badge@1.0.6
- @leafygreen-ui/button@2.2.6
- @leafygreen-ui/checkbox@3.0.2
- @leafygreen-ui/icon@1.0.4
- @leafygreen-ui/popover@1.0.1
- @leafygreen-ui/portal@1.0.5
- @leafygreen-ui/radio-box-group@1.0.6
- @leafygreen-ui/radio-group@1.1.7
- @leafygreen-ui/toggle@2.0.4
- @leafygreen-ui/lib@2.1.7
- @leafygreen-ui/theme@1.1.7
🎟 _Jira ticket:_ [Name of ticket](https://my.jira/ticket)
> Released version bumps to all packages

- package-lock.json
- packages/Checkbox/README.md
- packages/Checkbox/src/Checkbox.js
- packages/Toggle/README.md
- packages/Toggle/src/Toggle.js
Added option to pass an id of type number or string to toggle component. Tested in storybook passing an id as a prop and not passing an id as a prop and both options worked, also test suite still passing 👍 
🎟 _Jira ticket:_ [PD-307](https://jira.mongodb.org/browse/PD-307)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have added necessary documentation (if appropriate)
> Fix: added option to pass an id to toggle component

- packages/Badge/package.json
- packages/Badge/src/Badge.spec.tsx
- packages/Badge/src/Badge.story.tsx
- packages/Badge/src/Badge.tsx
- packages/Badge/src/index.js
- packages/Badge/src/index.ts
- packages/Badge/tsconfig.json
🎟 _Jira ticket:_ [PD-298](https://jira.mongodb.org/browse/PD-298)
> PD-298: Port <Badge> to TypeScript

- packages/Badge/README.md
- packages/Button/README.md
- packages/Checkbox/README.md
- packages/Popover/README.md
- packages/Portal/README.md
- packages/RadioBoxGroup/README.md
- packages/RadioGroup/README.md
- packages/Toggle/README.md
Updated readmes to reflect proper importing patterns for all components.
🎟 _Jira ticket:_ [PD-312](https://jira.mongodb.org/browse/PD-312)
- [ x] I have added necessary documentation (if appropriate)
> docs: updated docs for correct import patterns

- packages/Portal/package.json
- packages/Portal/src/Portal.spec.tsx
- packages/Portal/src/Portal.story.tsx
- packages/Portal/src/Portal.tsx
- packages/Portal/src/index.js
- packages/Portal/src/index.ts
- packages/Portal/tsconfig.json
🎟 _Jira ticket:_ [PD-302](https://jira.mongodb.org/browse/PD-302)
> PD-302: Port <Portal> to TypeScript

- packages/Popover/src/Popover.story.tsx
- packages/Portal/src/Portal.tsx
- packages/hooks/src/useEventListener.ts
- packages/palette/src/palette.spec.ts
- packages/palette/src/palette.story.tsx
- packages/palette/src/uiColors.ts
- tsconfig.json
🎟 _Jira ticket:_ [PD-324: Enable noImplicitAny flag](https://jira.mongodb.org/browse/PD-324)
> PD-324: Enable noImplicitAny flag

- packages/badge/src/Badge.spec.tsx
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.tsx
- packages/checkbox/src/Checkbox.spec.tsx
- packages/icon/src/Icon.spec.tsx
- packages/lib/src/index.ts
- packages/lib/src/typeIs.ts
- packages/popover/src/Popover.spec.tsx
- packages/portal/src/Portal.spec.tsx
- packages/radio-box-group/src/RadioBoxGroup.spec.tsx
- packages/radio-group/src/Radio.spec.tsx
- packages/radio-group/src/RadioGroup.spec.tsx
- packages/toggle/src/Toggle.spec.tsx
🎟 _Jira ticket:_ [PD-313](https://jira.mongodb.org/browse/PD-313)
> PD-313: Extract common type utils and util types to lib

- packages/icon/README.md
Fixed typo in Icon component's read me file for an import statement. Also, added a usage section to have `npm install` command like the way it shows for Palette component. 
🎟 [PD-332](https://jira.mongodb.org/browse/PD-332)
- [X ] Bugfix (non-breaking change which fixes an issue)
> PD-332 Fix typo in icon read me

- packages/badge/package.json
- packages/button/package.json
- packages/checkbox/package.json
- packages/emotion/package.json
- packages/hooks/package.json
- packages/icon/package.json
- packages/lib/package.json
- packages/menu/package.json
- packages/palette/package.json
- packages/popover/package.json
- packages/portal/package.json
- packages/radio-box-group/package.json
- packages/radio-group/package.json
- packages/theme/package.json
- packages/toggle/package.json
> chore: publish all packages

- packages/button/package.json
- packages/button/src/Button.tsx
This pull request updates buttons according to updates made to our Sketch libraries, and takes us one step closer to eliminating the theme package.
Additionally, the buttons were reworked to use CSS pseudo elements containing the gradients for each state so that we can animate the gradients between states. In essence, they should feel smoother when interacting, and be functionally the same otherwise.
🎟 _Jira ticket:_ [Component: Update buttons to new palette](https://jira.mongodb.org/browse/PD-341)
> PD-341: Update buttons to reflect new palette

- packages/modal/README.md
- packages/modal/src/Modal.story.tsx
- packages/modal/src/index.ts
- Fixed Modal README
- Exported { ModalSize } enum
- [ x] I have added necessary documentation (if appropriate)
> Fix Modal README

- packages/modal/src/Modal.story.tsx
Updating modal storybook to feature interactive and scroll-able Modals.
🎟 _Jira ticket:_ [PD-366](https://jira.mongodb.org/browse/PD-336)
> PD-366: updated examples in modal storybook

- packages/badge/package.json
- packages/button/package.json
- packages/card/package.json
- packages/checkbox/package.json
- packages/code/package.json
- packages/emotion/package.json
- packages/hooks/package.json
- packages/icon/package.json
- packages/lib/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/palette/package.json
- packages/popover/package.json
- packages/portal/package.json
- packages/radio-box-group/package.json
- packages/radio-group/package.json
- packages/syntax/package.json
- packages/theme/package.json
- packages/toggle/package.json
Remove ts:emit scripts from child package.json files
🎟 _Jira ticket:_ [PD-374](https://jira.mongodb.org/browse/PD-374)
> Remove ts:emit scripts from child package.json files

- packages/hooks/CHANGELOG.md
- packages/menu/CHANGELOG.md
Separated changelog for hooks/menu
> updated changelog for menu and hooks

- .changeset/many-chairs-change/changes.json
- .changeset/many-chairs-change/changes.md
Adding initial changeset for Tabs component
> Tabs Changeset

- .changeset/old-bags-develop/changes.json
- .changeset/old-bags-develop/changes.md
- packages/radio-box-group/package.json
- packages/radio-box-group/src/RadioBox.tsx
- packages/radio-box-group/tsconfig.json
* Removed package dependency on theme
* Added palette as a dependency
* Updated colors to be consistent with new palette
🎟 _Jira ticket:_ [PD-384](https://jira.mongodb.org/browse/PD-384)
> PD-384: Update Radio Box Group to new palette

- package.json
- storybook/addons.js
- storybook/config.js
- yarn.lock
Bringing in Accessibility add-on from Storybook, to help keep accessibility concerns at forefront of development process.
> PD-390: Add accessibility add-on to storybook config

- .changeset/afraid-plums-admire/changes.json
- .changeset/afraid-plums-admire/changes.md
- .changeset/early-dryers-know/changes.json
- .changeset/early-dryers-know/changes.md
Adding Changesets for Menu and MongoMenu components
> Adding Changesets for Menu and MongoMenu components

- .github/pull_request_template.md
PR to make it easier to link to ticket in PR template 😏 
🎟 _Jira ticket:_ [PD-395](https://jira.mongodb.org/browse/PD-395)
> Update ticket link in PR template to improve DX

- .changeset/shaggy-chefs-carry/changes.json
- .changeset/shaggy-chefs-carry/changes.md
- packages/modal/src/Modal.tsx
Made Modal a focusable element, which caused issues before because Modals can be scrollable and scrollable content needs to be focusable.
🎟 _Jira ticket:_ [PD-396](https://jira.mongodb.org/browse/PD-396)
> PD-396: Make Modal component accessible

- packages/menu/README.md
- packages/modal/README.md
- packages/mongo-menu/README.md
Updated Modal and Menu readmes to reflect changes in HTML based on accessibility updates.
> Update Modal and Menu Readmes

- packages/mongo-menu/README.md
The badge for Mongo Menu was pointed at the wrong URL. This is a quick fix for that.
> Fix Mongo Menu badge

- .changeset/few-buckets-film/changes.json
- .changeset/few-buckets-film/changes.md
- packages/menu/src/Menu.story.js
- packages/menu/src/MenuItem.tsx
Two bug fixes for Menu component:
- Update disabled styles
- Update Storybook example
🎟 _Jira ticket:_ [PD-398](https://jira.mongodb.org/browse/PD-398)
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added necessary documentation (if appropriate)~
> PD-398: Update disabled styles and storybook

- packages/mongo-menu/README.md
Updating MongoMenu docs for accuracy
> Update MongoMenu Docs

- .changeset/happy-elephants-laugh/changes.json
- .changeset/happy-elephants-laugh/changes.md
- .eslintrc.js
- package.json
- packages/checkbox/src/Checkbox.tsx
- packages/modal/src/Modal.tsx
- packages/tabs/src/Tabs.tsx
- packages/toggle/src/Toggle.tsx
- yarn.lock
Bringing a11y linter into leafyGreen
To note: there are seven errors raised by this linter, but will address those in separate PRs and have disabled the lint rules in the interim. Doing this because I believe that there will be different levels of version-bumping the effected components, so did not want to batch all of these changes.
🎟 _Jira ticket:_ [PD-293](https://jira.mongodb.org/browse/PD-293)
- [x ] New feature (non-breaking change which adds functionality)
~[ ] I have added tests that prove my fix is effective or that my feature works~
~[ ] I have added necessary documentation (if appropriate)~
~[ ] I have run `yarn changeset` and documented my changes~
> PD-293: Adding a11y linter to leafyGreen

- README.md
Remove confusing language around publishing from our README
- [ x] I have added necessary documentation (if appropriate)
> PD-399: Update documentation for publishing

- .changeset/empty-llamas-fetch/changes.json
- .changeset/empty-llamas-fetch/changes.md
- packages/modal/src/Modal.tsx
Tested Leafygreen components with a screenreader, and the biggest thing that stood out to me was that the function of the close icon in Modal component was not obvious. So, added title prop to make more accessible to screenreaders.
🎟 _Jira ticket:_ [PD-294](https://jira.mongodb.org/browse/PD-294)
~[ ] I have added tests that prove my fix is effective or that my feature works~
~[ ] I have added necessary documentation (if appropriate)~
- [ x] I have run `yarn changeset` and documented my changes
> PD-294: Test Leafy components with Screenreader

- .changeset/silly-trees-approve/changes.json
- .changeset/silly-trees-approve/changes.md
- .changeset/tidy-buckets-pretend/changes.json
- .changeset/tidy-buckets-pretend/changes.md
- packages/hooks/src/index.ts
- packages/hooks/src/useEventListener.ts
- packages/hooks/src/useHandleEscape.ts
- packages/menu/src/Menu.tsx
- packages/modal/src/Modal.tsx
- Added useEscapeHandler hook to hooks folder
- Replaced existing instances of useEventListener (where listening for EscapeKey) to using new hook
🎟 _Jira ticket:_ [PD-409](https://jira.mongodb.org/browse/PD-409)
> PD-409: Add useEscapeHandler hook

- .changeset/chilly-buttons-wash/changes.json
- .changeset/chilly-buttons-wash/changes.md
- jest.config.js
- package.json
- packages/palette/README.md
- packages/palette/src/index.ts
- packages/palette/src/ui-colors.less
- packages/palette/src/uiColors.less
- webpack.config.js
- yarn.lock
- Palette package now includes palette.less file
- Added file_loader module (so that palette.less is included in dist)
🎟 _Jira ticket:_ [PD-406](https://jira.mongodb.org/browse/PD-406)
> PD-406: Add ui-colors.less file

- .changeset/clean-goats-trade/changes.json
- .changeset/clean-goats-trade/changes.md
- packages/mongo-menu/README.md
- packages/mongo-menu/src/MongoMenu.tsx
Add accountURL prop to MongoMenu so that consuming application can decide where this button links out to.
🎟 _Jira ticket:_ [PD-411](https://jira.mongodb.org/browse/PD-411)
> PD-411: add accountURL prop

- packages/hooks/README.md
- packages/hooks/src/useElementNode.ts
Add README to hooks package.
🎟 _Jira ticket:_ [PD-326](https://jira.mongodb.org/browse/PD-326)
~[ ] I have added tests that prove my fix is effective or that my feature works~
~[ ] I have run `yarn changeset` and documented my changes~
* Not running changeset, as this will be bundled with the minor version bump when we release useEscapeKey, and I'm not sure that adding this documentation requires a line on the changelog - but let me know if you feel otherwise
> PD-326: Add Hooks README

- .changeset/clean-goats-trade/changes.json
- .changeset/clean-goats-trade/changes.md
- .changeset/polite-hounds-carry/changes.json
- .changeset/polite-hounds-carry/changes.md
- .changeset/silent-mangos-yawn/changes.json
- .changeset/silent-mangos-yawn/changes.md
- .changeset/wicked-chefs-admire/changes.json
- .changeset/wicked-chefs-admire/changes.md
- packages/menu/CHANGELOG.md
- packages/menu/package.json
- packages/modal/CHANGELOG.md
- packages/modal/package.json
- packages/mongo-menu/CHANGELOG.md
- packages/mongo-menu/package.json
- packages/popover/CHANGELOG.md
- packages/popover/package.json
- packages/portal/CHANGELOG.md
- packages/portal/package.json
- packages/tooltip/CHANGELOG.md
- packages/tooltip/package.json
> Release Branch

- .changeset/wild-kings-dress.md
- packages/tabs/src/Tabs.spec.tsx
- packages/tabs/src/Tabs.tsx
- Use keyCode rather than key in Tabs keyboard navigation
🎟 _Jira ticket:_ [PD-430](https://jira.mongodb.org/browse/PD-430)
> PD-430: Use keyCode rather than Key for Tab keyboard navigation

- .changeset/fuzzy-apricots-invent.md
- packages/menu/README.md
- packages/menu/src/MenuItem.tsx
- Add border-box property to MenuItem
🎟 _Jira ticket:_ [PD-446](https://jira.mongodb.org/browse/PD-446)
> PD-446: Add border-box property to MenuItem

- .changeset/blue-vans-taste.md
- .changeset/bright-peaches-suffer.md
- packages/lib/src/index.ts
- packages/menu/src/Menu.tsx
- packages/tabs/src/Tabs.tsx
- Add keyMap to lib
- Menu/Tab now use exported keyMap object in useEventListener hooks
🎟 _Jira ticket:_ [PD-44](https://jira.mongodb.org/browse/PD-444)
> PD-444: Add keymap to lib

- README.md
- package.json
- Update our documentation and release script based on latest version of Changesets
- Changeset documentation can be found [here](https://github.com/atlassian/changesets/blob/master/packages/cli/README.md)
🎟 _Jira ticket:_ [PD-445](https://jira.mongodb.org/browse/PD-445)
> PD-445: Changeset modifications to documentation and release script

- .changeset/blue-vans-taste.md
- .changeset/bright-peaches-suffer.md
- .changeset/fuzzy-apricots-invent.md
- packages/lib/CHANGELOG.md
- packages/lib/package.json
- packages/menu/CHANGELOG.md
- packages/menu/package.json
- packages/mongo-menu/CHANGELOG.md
- packages/mongo-menu/package.json
- packages/tabs/CHANGELOG.md
- packages/tabs/package.json
> Generate Changelogs

- .changeset/six-tables-clean.md
- packages/mongo-menu/src/MongoMenu.tsx
- Truncate long emails in MongoMenu
🎟 _Jira ticket:_ [PD-441](https://jira.mongodb.org/browse/PD-441)
> PD-441: Long emails in MongoMenu aren't truncated

- .changeset/fair-lemons-bake.md
- .changeset/healthy-rice-learn.md
- packages/modal/package.json
- packages/tooltip/package.json
- Upgrade dependencies in Tooltip component
> Upgrade Dependencies in Tooltip Component

- .changeset/fair-lemons-bake.md
- .changeset/healthy-rice-learn.md
- .changeset/six-tables-clean.md
- packages/modal/CHANGELOG.md
- packages/modal/package.json
- packages/mongo-menu/CHANGELOG.md
- packages/mongo-menu/package.json
- packages/tooltip/CHANGELOG.md
- packages/tooltip/package.json
- Pre-release `changeset version`
> Changeset Version 

- .changeset/angry-dancers-do.md
- packages/tooltip/src/Tooltip.spec.tsx
- packages/tooltip/src/Tooltip.tsx
- Patch fix to Tooltip, to allow trigger to accept nested components
- Added test to prove that fix works
🎟 _Jira ticket:_ [PD-454](https://jira.mongodb.org/browse/PD-454)
> PD-454: Tooltip Trigger Accepts Nested Components

- .changeset/angry-dancers-do.md
- .changeset/curly-countries-call.md
- .changeset/fresh-pumpkins-change.md
- .changeset/thin-houses-cough.md
- packages/icon-button/CHANGELOG.md
- packages/icon-button/package.json
- packages/logo/CHANGELOG.md
- packages/logo/package.json
- packages/palette/CHANGELOG.md
- packages/palette/package.json
- packages/tooltip/CHANGELOG.md
- packages/tooltip/package.json
Pre-release changelog generation for:
- IconButton
- Logo
- Palette
- Tooltip
> Generate Changelog

- .changeset/slow-tools-pull.md
- packages/modal/README.md
- packages/modal/package.json
- packages/modal/src/Modal.tsx
- Move `className` prop to root `div`
- Add `contentClassName` prop to overlay `div`
🎟 _Jira ticket:_ [PD-456(https://jira.mongodb.org/browse/PD-456)
> PD-456: Adjust Modal className props

- .changeset/mean-games-study.md
- packages/icon-button/README.md
- packages/icon-button/src/IconButton.spec.tsx
- packages/icon-button/src/IconButton.story.tsx
- packages/icon-button/src/IconButton.tsx
- Add `ariaLabel` prop to IconButton to make component accessible
🎟 _Jira ticket:_ [PD-458](https://jira.mongodb.org/browse/PD-458)
> PD-458: make IconButton accessible

- .circleci/config.yml
We're running into memory usage issues on CircleCI. [See docs ticket](https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory).
The hope is that by upgrading to node 12, it has better memory consumption and helps reduce us going over our memory usage.
If this doesn't help [a future change would be to switch away from using CircleCI's docker](https://discuss.circleci.com/t/exited-with-code-137-on-free-plan/24038/2) which gives more memory by default.
> Update CircleCI node version to 12

- packages/icon-button/tsconfig.json
- tsconfig.json
Add Logo and IconButton components to root tsconfig
🎟 _Jira ticket:_ [PD-462](https://jira.mongodb.org/browse/PD-462)
> PD-462: Add Logo and IconButton to root tsconfig

- .github/pull_request_template.md
- Add tooling option to PR template
> PD-467: Add tooling option to github pr template

- .changeset/strong-spoons-explode.md
- packages/menu/src/Menu.tsx
- packages/menu/src/MenuItem.tsx
- Update Menu and MenuItem styles to fix bugs on Safari and Firefox 😬 
🎟 _Jira ticket:_ [PD-476](https://jira.mongodb.org/browse/PD-476)
> PD-476: Fix bugs on Safari and Firefox

- .changeset/thirty-months-sell.md
Adds the missing changeset for our new provider.
> Generate changeset for leafygreen-provider

- scripts/package-builder.js
- update lib version in our package-builder script
> PD-488: Update lib version in package-builder script

- .changeset/eight-planets-change.md
- webpack.config.js
As a part of the SSR update, we added server APIs for our custom emotion instance using the `create-emotion-server` package, but failed to include it as an external dependency in our Webpack configuration. This caused a massive inflation of the size of the `@leafygreen-ui/emotion` package, including adding a heavy Buffer polyfill to the bundle.
This PR adds that package to our externals array.
🎟 _Jira ticket:_ [Make create-emotion-server an external dependency of the emotion package](https://jira.mongodb.org/browse/PD-489)
> PD-489: Add create-emotion-server to Webpack externals array

- .github/pull_request_template.md
- README.md
- packages/badge/README.md
- packages/button/README.md
- packages/card/README.md
- packages/checkbox/README.md
- packages/code/README.md
- packages/emotion/README.md
- packages/hooks/README.md
- packages/icon-button/README.md
- packages/icon/README.md
- packages/leafygreen-provider/README.md
- packages/logo/README.md
- packages/menu/README.md
- packages/modal/README.md
- packages/mongo-menu/README.md
- packages/palette/README.md
- packages/pipeline/README.md
- packages/popover/README.md
- packages/portal/README.md
- packages/radio-box-group/README.md
- packages/radio-group/README.md
- packages/syntax/README.md
- packages/tabs/README.md
- packages/toggle/README.md
- packages/tooltip/README.md
- scripts/package-builder.js
- Add table of contents to global readme
- Update each package with installation instructions
- Add installation instructions to package-builder script
- Add checkboxes to PR template to add new package to global tsconfig and table of contents in read me
> PD-490: Update Documentation

- .changeset/large-zebras-exercise.md
- packages/modal/package.json
- packages/popover/package.json
- webpack.config.js
- yarn.lock
- Make react-transition-group an external dep
- Patch bump modal and popover
> PD-491: Make react-transition-group an external dep of the build

- .changeset/clever-dolls-know.md
- .changeset/eight-planets-change.md
- .changeset/empty-bobcats-teach.md
- .changeset/large-zebras-exercise.md
- packages/emotion/CHANGELOG.md
- packages/emotion/package.json
- packages/icon-button/CHANGELOG.md
- packages/icon-button/package.json
- packages/icon/CHANGELOG.md
- packages/icon/package.json
- packages/lib/CHANGELOG.md
- packages/lib/package.json
- packages/modal/CHANGELOG.md
- packages/modal/package.json
- packages/mongo-menu/CHANGELOG.md
- packages/mongo-menu/package.json
- packages/popover/CHANGELOG.md
- packages/popover/package.json
- packages/side-nav/CHANGELOG.md
- packages/side-nav/package.json
> Changeset Version

- .changeset/curly-meals-pay.md
- packages/side-nav/README.md
- packages/side-nav/src/SideNav.spec.tsx
- packages/side-nav/src/SideNavGroup.tsx
- packages/side-nav/src/SideNavItem.tsx
This increases the contrast of labels in the SideNav components, as well as improves handling of Aria roles.
> Improve SideNav Accessibility

- .changeset/yellow-crabs-appear.md
- package.json
- packages/modal/package.json
- packages/popover/package.json
Move react-transition-group back to dependencies of Modal and Popover
> Fix Yarn console warning

- .changeset/neat-lies-bathe.md
- packages/mongo-nav/README.md
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/index.ts
- packages/mongo-nav/src/mongo-menu/index.ts
- packages/mongo-nav/src/mongo-select/MongoSelect.spec.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/types.ts
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
- packages/mongo-nav/src/user-menu/UserMenuTrigger.tsx
- packages/mongo-nav/src/user-menu/index.ts
- Renamed MongoMenu in MongoNav to UserMenu
🎟 _Jira ticket:_ [PD-502](https://jira.mongodb.org/browse/PD-502)
~[ ] I have added tests that prove my fix is effective or that my feature works~
~[ ] I have added necessary documentation (if appropriate)~
> PD-502: Rename MongoMenu to UserMenu

- packages/mongo-nav/README.md
- Update README to reflect most up-to-date API for <MongoNav />
> Update Docs for MongoNav

- .changeset/cool-rules-shout.md
- packages/side-nav/src/SideNavGroup.tsx
- packages/side-nav/src/SideNavItem.tsx
As the title says – some quick spacing changes to the side nav to improve legibility, and bring it up to design specifications.
🎟 _Jira ticket:_ [Bring SideNav component spacing up to spec](https://jira.mongodb.org/browse/PD-515)
> PD-515: Bring SideNav up to design spec

- .changeset/small-files-pretend.md
- packages/button/package.json
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.story.tsx
- packages/button/src/Button.tsx
- packages/button/tsconfig.json
🎟 _Jira ticket:_ [PD-262](https://jira.mongodb.org/browse/PD-262)
> PD-262: Add Glyph Prop to Button Component

- .changeset/ten-beds-sin.md
- packages/menu/README.md
- packages/menu/src/Menu.story.js
- packages/menu/src/Menu.tsx
- Required for <MongoNav />
- Add spacing prop to <Menu /> component
🎟 _Jira ticket:_ [PD-537](https://jira.mongodb.org/browse/PD-537)
> PD-537: Add spacing prop to menu component

- .changeset/lemon-trees-stare.md
- packages/button/package.json
- packages/hooks/package.json
- packages/mongo-nav/package.json
- packages/mongo-nav/src/MongoNav.tsx
- packages/tooltip/package.json
- webpack.config.js
- Using lodash `defaultsDeep` to construct default URLs in MongoNav
> Cleaner construction of defaults in MongoNav

- packages/mongo-nav/src/helpers/InteractionRingWrapper.tsx
- packages/mongo-nav/src/helpers/OrgNavLink.tsx
- packages/mongo-nav/src/helpers/index.ts
- packages/mongo-nav/src/mongo-select/Trigger.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- Break out helper components for readability, I foresee there being some more, especially as the loader logic evolves
> Break Out Helper Components for Readability 

- .changeset/tidy-pumpkins-hug.md
- packages/mongo-nav/src/user-menu/UserMenu.tsx
> UserMenu TS Fix

- packages/icon-button/src/IconButton.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/breakpoints.ts
- packages/mongo-nav/src/mongo-select/Trigger.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/user-menu/UserMenuTrigger.tsx
- storybook/preview-head.html
Adds responsive nav styling to the existing style PR.
🎟 _Jira ticket:_ [Related to: EXPO-260](https://jira.mongodb.org/browse/EXPO-260)
> EXPO-260: Responsive MongoNav

- README.md
Just removes the CircleCI badge.
> Remove CircleCI Badge

- packages/text-input/package.json
switch devDependencies to dependencies in TextInput
> switch devDependencies to dependencies in TextInput

- .changeset/shaggy-walls-itch.md
> add changeset for TextInput

- .changeset/pink-singers-dream.md
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- Add preliminary Cloud Manager state to MongoNav (will be improved when proper Icons are in our repo)
- Added testids around ProjectNav and a test suite for the component
🎟 _Jira ticket:_ [PD-503](https://jira.mongodb.org/browse/PD-503)
> PD-503: Add Cloud Manager State to MongoNav

- .changeset/old-tables-flash.md
- packages/menu/src/Menu.tsx
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/MongoNav.story.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/OnElementClickProvider.tsx
- packages/mongo-nav/src/helpers/OnPremUserMenu.tsx
- packages/mongo-nav/src/index.ts
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/types.ts
- packages/mongo-nav/src/user-menu/UserMenu.tsx
Check each commit for description of that atomic change. 
- Unify OnElementClick and NavItem enums to one enum
- Revise exports from index.ts and also export NavItem type
- Rename NavItem to NavElement
- When clicking a project menu item close the menu
- move all useState calls in Menu into one location
- Add remaining activeNav values
> Harry mongo nav tweaks

- .changeset/young-oranges-give.md
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/mongo-select/MongoSelect.tsx
- Only display projects in ProjectSelect that have the same currentOrg as the currentProject
🎟 _Jira ticket:_ [PD-575](https://jira.mongodb.org/browse/PD-575)
> PD-575: Filter projects based on current org

- .changeset/warm-oranges-explode.md
- packages/mongo-nav/README.md
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/types.ts
> Fix charts link

- .changeset/itchy-students-jog.md
- .changeset/olive-schools-hammer.md
- packages/icon/package.json
- packages/typography/package.json
- Move lib from devDep to dep in Typography and Icon
> Move lib from devDep to dep in Typography and Icon

- .changeset/wild-pugs-bathe.md
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
This prevents full page refreshes in an Atlas project.
> Set Atlas tab link to the full URL

- .changeset/chilly-pianos-pump.md
- packages/mongo-nav/src/helpers/Icons.tsx
- packages/mongo-nav/src/mongo-select/Trigger.tsx
- The Building icon was too dark in the OrgNav
- The width/height of 18px on Realm icon looked larger than the 18px of Cloud/Charts, so artificially minimized.
> Style bugs

- .changeset/dull-news-peel.md
- .changeset/friendly-radios-jam.md
- .changeset/honest-fireants-cry.md
- .changeset/light-chairs-wash.md
- .changeset/shy-fans-relate.md
- package.json
- packages/mongo-nav/README.md
- packages/mongo-nav/src/MongoNav.story.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/mongo-select/MongoSelect.spec.tsx
- packages/mongo-nav/src/mongo-select/MongoSelect.tsx
- packages/mongo-nav/src/org-nav/OrgNav.spec.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/types.ts
- yarn.lock
> More tweaks

- .changeset/few-sloths-tie.md
- packages/mongo-nav/src/helpers/Icons.tsx
> Resizes all logos to fill their viewbox

- .changeset/clean-deers-remember.md
- packages/mongo-nav/src/helpers/OrgNavLink.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.spec.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/styles.tsx
- Fixes anchor style overrides
- Enables OrgTrigger in OrgSelect
🎟 _Jira ticket:_ [PD-601](https://jira.mongodb.org/browse/PD-601)
> PD-601: Addresses bugs in MongoNav

- .changeset/cyan-moons-tap.md
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
Changes color of IconButtons in ProjectNav when active 
cc: @nellem23 
🎟 _Jira ticket:_ [PD-602](https://jira.mongodb.org/browse/PD-602)
> PD-602: Changes color of active IconButton in ProjectNav

- .changeset/blue-balloons-agree.md
- packages/button/package.json
- packages/button/src/Button.tsx
- packages/button/tsconfig.json
🎟 _Jira ticket:_ [PD-608](https://jira.mongodb.org/browse/PD-608)
> PD-609: Adds leafygreen provider to button component

- .github/pull_request_template.md
Fixes a reference we missed to the old CONTRIBUTING.md, updating it to DEVELOPER.md
> Update reference to old CONTRIBUTING.md

- .changeset/real-trains-look.md
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
🎟 _Jira ticket:_ [PD-615](https://jira.mongodb.org/browse/PD-615)
cc: @nellem23
> PD-615: Change authorization to authentication 

- .changeset/eighty-timers-hunt.md
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
Fixes style bug in alerts badge
Before:
After:
🎟 _Jira ticket:_ [PD-618](https://jira.mongodb.org/browse/PD-618)
> PD-618: Style updates for Alerts badge

- .changeset/rotten-carrots-taste.md
Changeset to release mongonav at v1
> Release MongoNav at v1

- .changeset/fair-steaks-argue.md
- packages/mongo-nav/src/user-menu/UserMenu.tsx
- Changes "Atlas" to "Cloud" in UserMenu
- I know this addresses only half of the ticket, but I wanted to get this fix up ASAP while I understand the other work that remains to be done
cc: @nellem23 
🎟 _Jira ticket:_ [PD-628](https://jira.mongodb.org/browse/PD-628)
> PD-628: Changes "Atlas" to "Cloud" in UserMenu

- package.json
- storybook/addons.js
- storybook/config.js
- yarn.lock
Adds [this](https://github.com/atlassian-labs/storybook-addon-performance) to storybook.
Looks like this:
> Adds performance addon to Storybook

- .changeset/dull-paws-switch.md
- packages/mongo-nav/src/helpers/OnPremUserMenu.tsx
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
> PD-630: Changes Logout to Log out

- .changeset/sharp-feet-relate.md
- packages/mongo-nav/src/helpers/Icons.tsx
Replaces the existing Charts logo with a redesigned one.
> replace charts logo with redesigned mark

- .changeset/eleven-elephants-hang.md
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/MongoNav.story.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/types.ts
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
> Small refactor for data fetching and add support for accepting admin value from API endpoint

- .changeset/seven-masks-deliver.md
- packages/mongo-nav/src/types.ts
- packages/mongo-nav/src/user-menu/UserMenu.tsx
Admin no longer required in AccountInterface
account as activePlatform renders Cloud SubMenu is UserMenu
🎟 _Jira ticket:_ [PD-650](https://jira.mongodb.org/browse/PD-650)
> PD-650: Bug fixes in MongoNav

- .changeset/thirty-taxis-arrive.md
- packages/menu/src/Menu.tsx
- packages/mongo-nav/src/MongoNav.spec.tsx
- Fixes issue with SubMenu, setting open when Menu is open not closed.
> Fixes issue with SubMenu, setting open when Menu is open not closed.

- .changeset/fresh-cars-warn.md
- packages/mongo-nav/src/org-nav/OrgNav.tsx
🎟 _Jira ticket:_ [PD-667](https://jira.mongodb.org/browse/PD-667)
> PD-667: When selecting Org Access Manager in MongoNav we don't close the menu

- .gitignore
- Add a comment for the line that ignores the `.tsbuildinfo` file
> Add comment to .gitignore

- .github/pull_request_template.md
> Fix minor typo in pull request template

- .changeset/seven-plants-punch.md
- packages/banner/package.json
- scripts/package-builder.js
- Change devDep to dep in banner and script
> Change devDep to dep in banner and script

- .changeset/six-carrots-raise.md
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- Change host URL from 'stitch.mongodb.com' to 'realm.mongodb.com'
🎟 _Jira ticket:_ [PD-690](https://jira.mongodb.org/browse/PD-690)
> PD-690: Change host URL in MongoNav

- .changeset/three-jokes-shave.md
- packages/icon/scripts/build.ts
Glyphs that are currently being transpiled to ES Modules seem to be breaking some contexts – in particular, unit tests running in a node-like environment.
🎟 _Jira ticket:_ [PD-687](https://jira.mongodb.org/browse/PD-687)
> PD-687: Transpile individual glyph files to ES5

- webpack.config.js
🎟 _Jira ticket:_ [Prevent build errors when switching between branches](https://jira.mongodb.org/browse/PD-685)
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added necessary documentation (if appropriate)~
- ~[ ] I have run `yarn changeset` and documented my changes~
- ~[ ] I have added my new package to the global tsconfig~
- ~[ ] I have added my new package to the Table of Contents on the global README~
> Ignore package directories that do not have a package.json file

- .changeset/tough-bears-thank.md
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
Removes Stitch/Realm display logic
🎟 _Jira ticket:_ [PD-693](https://jira.mongodb.org/browse/PD-693)
> PD-693: Removes Stitch/Realm display name logic

- jest.config.js
- packages/banner/src/Banner.spec.tsx
- packages/box/src/Box.spec.tsx
- packages/checkbox/src/Checkbox.spec.tsx
- packages/icon-button/src/IconButton.spec.tsx
- packages/logo/src/Logo.spec.tsx
- packages/menu/src/Menu.spec.tsx
- packages/modal/src/Modal.spec.tsx
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.spec.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.spec.tsx
- packages/mongo-nav/src/on-element-click-provider/OnElementClick.spec.tsx
- packages/mongo-nav/src/org-nav/OrgNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/popover/src/Popover.spec.tsx
- packages/radio-group/src/Radio.spec.tsx
- packages/side-nav/src/SideNav.spec.tsx
- packages/tabs/src/Tabs.spec.tsx
- packages/text-input/src/TextInput.spec.tsx
- packages/tooltip/src/Tooltip.spec.tsx
- scripts/package-builder.js
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added necessary documentation (if appropriate)~
- ~[ ] I have run `yarn changeset` and documented my changes~
- ~[ ] I have added my new package to the global tsconfig~
- ~[ ] I have added my new package to the Table of Contents on the global README~
> Automatically import @testing-library/jest-dom/extend-expect

- packages/badge/README.md
- packages/banner/README.md
- packages/box/README.md
- packages/button/README.md
- packages/callout/README.md
- packages/card/README.md
- packages/checkbox/README.md
- packages/code/README.md
- packages/icon-button/README.md
- packages/icon/README.md
- packages/logo/README.md
- packages/menu/README.md
- packages/modal/README.md
- packages/mongo-nav/README.md
- packages/palette/README.md
- packages/pipeline/README.md
- packages/popover/README.md
- packages/portal/README.md
- packages/radio-box-group/README.md
- packages/radio-group/README.md
- packages/side-nav/README.md
- packages/syntax/README.md
- packages/tabs/README.md
- packages/text-input/README.md
- packages/toggle/README.md
- packages/tooltip/README.md
- packages/typography/README.md
- scripts/package-builder.js
- Adds respective storybook link to all readmes
- Adds generic link to package builder script
cc: @matt-d-rat
> Add storybook link to readme

- .changeset/khaki-buses-cover.md
- packages/modal/src/Modal.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-710](https://jira.mongodb.org/browse/PD-710)
> PD-710: Hides Modal focus state

- .changeset/red-ladybugs-double.md
- packages/radio-group/README.md
- packages/radio-group/src/Radio.spec.tsx
- packages/radio-group/src/Radio.tsx
🎟 _Jira ticket:_ [PD-706](https://jira.mongodb.org/browse/PD-706)
> PD-706: Radio no longer adds className to label and input

- .changeset/khaki-grapes-visit.md
- packages/button/README.md
- packages/button/package.json
- packages/menu/README.md
- packages/menu/package.json
- packages/mongo-nav/package.json
- packages/radio-box-group/README.md
- packages/radio-box-group/package.json
- packages/side-nav/README.md
- packages/side-nav/package.json
- packages/text-input/README.md
- packages/text-input/package.json
- packages/typography/README.md
- packages/typography/package.json
Makes `@leafygreen-ui/leafygreen-provider` a peerDependency of all dependent packages.
🎟 _Jira ticket:_ [PD-613](https://jira.mongodb.org/browse/PD-613)
> PD-613: Make leafygreen-provider a peerDependency in all dependent packages

- .changeset/bright-pants-search.md
- .changeset/cold-lobsters-drum.md
- packages/box/src/Box.spec.tsx
- packages/box/src/Box.tsx
- packages/button/src/Button.tsx
- packages/menu/src/MenuItem.tsx
- packages/menu/src/SubMenu.tsx
- Update extendable box to accept a default that's not "div"
🎟 _Jira ticket:_ [PD-720](https://jira.mongodb.org/browse/PD-720)
> PD-720: Fix TS errors in components inheriting from Box

- .changeset/kind-points-buy.md
- packages/text-input/README.md
- packages/text-input/src/TextInput.spec.tsx
- packages/text-input/src/TextInput.tsx
🎟 _Jira ticket:_ [PD-646](https://jira.mongodb.org/browse/PD-646)
> PD-646: Conditionally render label tag on TextInput

- .changeset/famous-candles-drop.md
- README.md
- jest.config.js
- package.json
- packages/testing-lib/package.json
- packages/testing-lib/src/context.spec.ts
- packages/testing-lib/src/context.ts
- packages/testing-lib/src/index.ts
- packages/testing-lib/src/jest-dom.ts
- packages/testing-lib/src/jest.ts
- packages/testing-lib/tsconfig.json
- tsconfig.json
🎟 _Jira ticket:_ [Enable code sharing between tests](https://jira.mongodb.org/browse/PD-723)
> Add testing library package

- .changeset/silver-bananas-joke.md
- .changeset/two-sloths-vanish.md
- packages/icon-button/src/IconButton.tsx
- packages/icon/src/glyphs/Copy.svg
- Removes duplicative `id` from Copy glyph
- Adds `aria-label` to LeafyGreen icons/glyphs when we remove title coming from IconButton
> Accessibility Audit

- .github/workflows/release.yml
In action: https://github.com/brookescarlett/leafygreen-ui/actions/runs/171842834
🎟 _Jira ticket:_ [PD-726](https://jira.mongodb.org/browse/PD-726)
> PD-726: Update Release workflow

- storybook/preview-body.html
Fixes missing `__TARGET__` variable running storybook locally.
> Fix missing __TARGET__ variable in storybook

- .changeset/rich-sloths-serve.md
- packages/box/src/Box.spec.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.spec.tsx
- packages/mongo-nav/src/on-element-click-provider/OnElementClick.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/tsconfig.json
- packages/radio-box-group/src/RadioBoxGroup.spec.tsx
- packages/stepper/src/Stepper.tsx
- packages/stepper/src/styles.ts
- packages/testing-lib/src/jest-dom.ts
- packages/testing-lib/src/jest.ts
- packages/text-input/src/TextInput.spec.tsx
🎟 _Jira ticket:_ [Clean up console errors from tests](https://jira.mongodb.org/browse/PD-712)
~- [x] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added necessary documentation (if appropriate)~
~- [ ] I have run `yarn changeset` and documented my changes~
~- [ ] I have added my new package to the global tsconfig~
~- [ ] I have added my new package to the Table of Contents on the global README~
> Remove console warnings in tests

- packages/button/src/Button.story.tsx
The name of the story is plural for no apparent reason.
> Fix name of button story

- packages/testing-lib/src/jest-dom.ts
> Remove unneeded variable from JestDOM testing lib

- .changeset/sour-fans-tap.md
- packages/box/src/Box.spec.tsx
- packages/box/src/Box.tsx
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.tsx
- packages/menu/src/MenuItem.tsx
- packages/menu/src/SubMenu.tsx
- Make existence checks include null
= This means that if a user passes in null it'll be treated as not existing.
🎟 _Jira ticket:_ [PD-751](https://jira.mongodb.org/browse/PD-751)
> PD-751: Make existence checks include null

- .changeset/spicy-waves-greet.md
- packages/mongo-nav/src/org-nav/OrgNav.spec.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
🎟 _Jira ticket:_ [PD-621](https://jira.mongodb.org/browse/PD-621])
> PD-621: Remove See Product Tour from OrgNav

- .changeset/slimy-laws-add.md
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.tsx
> Fix non-admin search for project and organization

- .changeset/long-seahorses-rule.md
- packages/lib/package.json
> Remove testing-library dependency from lib

- .changeset/shaggy-impalas-march.md
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
- yarn.lock
> Remove MFA MenuItem from UserMenu when environment is gov

- .changeset/short-vans-unite.md
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.tsx
> Ensures that `children` prop is not required by Button component

- .github/workflows/nodejs.yml
Didn't seem to have any effect. Removing it since it's superfluous.
> Revert "Attempt to make tests run when changeset versions branch updated"

- .changeset/three-phones-appear.md
- packages/mongo-nav/src/org-nav/GovBanner.tsx
- yarn.lock
- Bug detected when Cloud overwrites MongoNav z-index from 0 to 12, which results in tooltip being hidden behind the OrgNav and ProjectNavs.
- Added `usePortal={false}` prop to both GovBanner tooltips to ensure that tooltip is always visible.
cc: @everag 
Before:
After:
> PD-768: GovBanner Bug Fix

- .changeset/good-maps-cheer.md
- packages/hooks/src/useEventListener.ts
- packages/hooks/src/usePoller.ts
- packages/hooks/src/useViewportSize.ts
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/user-menu/UserMenuTrigger.tsx
> Make MongoNav support server-side rendering

- .changeset/two-ravens-talk.md
- packages/portal/src/Portal.spec.tsx
- packages/portal/src/Portal.tsx
> Make Portal SSR-compatible

- packages/icon/scripts/build.ts
- storybook/preview-body.html
> Fix Storybook build error

- .changeset/chatty-ravens-provide.md
- packages/typography/src/Typography.tsx
- Quick PR to address bug raised in #leafygreen-ui 
> Spread rest props on all components in Typography package

- .changeset/proud-stingrays-return.md
- packages/mongo-nav/src/org-nav/GovBanner.tsx
> Update copy in GovBanner

- .changeset/stale-lizards-act.md
- packages/banner/src/Banner.spec.tsx
- packages/callout/src/Callout.spec.tsx
- packages/icon/src/Icon.spec.tsx
- packages/icon/src/createGlyphComponent.tsx
- packages/icon/src/template.ts
- packages/text-input/src/TextInput.spec.tsx
- packages/typography/src/Typography.spec.tsx
We are current passing the `title` attribute to SVG elements, which is not valid.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
We should be using the `title` element that's inside the SVG element.
> Fix icon titles

- .changeset/flat-bikes-reply.md
- package.json
- packages/checkbox/src/Checkbox.tsx
- packages/lib/src/IdAllocator.spec.ts
- packages/lib/src/IdAllocator.ts
- packages/lib/src/index.ts
- packages/radio-box-group/src/RadioBoxGroup.tsx
- packages/radio-group/src/RadioGroup.tsx
- packages/text-input/src/TextInput.tsx
- packages/toggle/src/Toggle.tsx
- packages/tooltip/src/Tooltip.tsx
- yarn.lock
> Add IdAllocator class to make ID generation deterministic

- .changeset/four-poets-whisper.md
- packages/hooks/README.md
- packages/hooks/src/hooks.spec.tsx
- packages/hooks/src/index.ts
- packages/hooks/src/usePrevious.ts
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.tsx
- packages/mongo-nav/src/mongo-select/selectHelpers.ts
- packages/popover/src/Popover.tsx
🎟 _Jira ticket:_ [Refactor `usePrevious` hook for use in multiple components](https://jira.mongodb.org/browse/PD-702)
> Move `usePrevious` hook to leafygreen library and update code to use it

- .changeset/warm-mirrors-arrive.md
- .eslintrc.js
- packages/code/src/Code.tsx
- packages/hooks/src/hooks.spec.tsx
- packages/hooks/src/index.ts
- packages/hooks/src/useEventListener.ts
- packages/hooks/src/useObjectDependency.ts
- packages/menu/src/Menu.tsx
- packages/mongo-nav/src/MongoNav.spec.tsx
- packages/mongo-nav/src/MongoNav.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.tsx
- packages/popover/src/Popover.tsx
- packages/syntax/src/Syntax.tsx
- packages/tabs/src/TabTitle.tsx
- packages/tooltip/src/Tooltip.tsx
This enables the React hooks linter and fixes the remaining warnings.
> Fix remaining React hooks lint warnings

- .changeset/rich-toes-sell.md
- packages/table/package.json
- packages/table/src/Row.tsx
- packages/tokens/src/Tokens.story.tsx
- Update idAllocator in Table
- Remove console log in Tokens
> Small Updates

- packages/table/src/Table.spec.tsx
> Fix console warning in Table test

- .changeset/silly-coins-attend.md
- packages/popover/src/Popover.tsx
🎟 _Jira ticket:_ [Popover behaves strangely in version 5.2.0](https://jira.mongodb.org/browse/PD-834)
> Fix Popover bug

- .changeset/shaggy-games-tickle.md
- packages/tokens/README.md
- packages/tokens/src/Tokens.story.tsx
- packages/tokens/src/spacing.ts
- Use numbers instead of strings. 
- Add as const to the spacing enum.
🎟 _Jira ticket:_ [PD-840](https://jira.mongodb.org/browse/PD-840)
> PD-840: Update spacing in tokens package 

- .changeset/cyan-beers-search.md
- .changeset/fluffy-gorillas-mate.md
- packages/icon/src/glyphs/X.svg
- packages/modal/src/Modal.story.tsx
- packages/modal/src/Modal.tsx
Updated Modal with some stylistic changes aftering QAing with Rob
> Update modal appearance and X icon

- .changeset/brave-maps-work.md
- packages/table/README.md
- packages/table/src/Table.spec.tsx
- packages/table/src/Table.story.tsx
- packages/table/src/TableHead.tsx
Updates Table documentation to represent default usage of `columns` prop. Additionally, now allows `<HeaderRow />` to be passed to `columns` prop
🎟 _Jira ticket:_ [PD-841](https://jira.mongodb.org/browse/PD-841)
> PD-841: Updates table documentation and fixes bug in table

- website/pages/index.tsx
> hello world test

- website/auth_providers/api-key.json
- website/config.json
- website/pages/index.tsx
- Adds Realm config to website
> Adds realm config to website

- website/config.json
- Ran a command to autogenerate the config.json, but callout in the docs says there are certain fields to remove. Trying again.
> Fix Realm Config

- package.json
> Suppress Storybook version update

- storybook/webpack.config.js
> Fix Storybook build

- .changeset/strange-chicken-destroy.md
- packages/box/package.json
- packages/button/package.json
- packages/hooks/package.json
- packages/mongo-nav/package.json
- packages/pipeline/package.json
- packages/popover/package.json
- packages/tabs/package.json
- packages/toast/package.json
- packages/tooltip/package.json
- yarn.lock
> Pin lodash version to latest to include fix for prototype pollution attack vulnerability

- .changeset/three-horses-help.md
- packages/inline-definition/package.json
- packages/marketing-modal/package.json
- packages/toast/package.json
> Fix package bundle paths

- .changeset/nasty-crabs-reflect.md
- packages/toast/src/Toast.story.tsx
- packages/toast/src/Toast.tsx
- packages/toast/src/index.ts
Small patch change to export the Toast variants!
> Export toast variants

- package.json
- yarn.lock
The last update was around ~6 months ago.
> Update browsers list

- .changeset/yellow-zebras-lie.md
- packages/side-nav/README.md
- packages/side-nav/src/SideNav.spec.tsx
- packages/side-nav/src/SideNavGroup.tsx
Adds defaultCollapsable prop to SideNavGroup
🎟 _Jira ticket:_ [PD-876](https://jira.mongodb.org/browse/PD-876)
> PD-876: Adds initialCollapsed prop to SideNavGroup

- .gitattributes
https://github.com/github/linguist/#generated-code
> Suppress generated files in diffs

- .changeset/cold-geese-crash.md
- packages/tabs/package.json
- packages/tabs/src/TabTitle.tsx
- packages/tabs/tsconfig.json
- storybook/preview-head.html
- website/styles/globals.tsx
- Updates Akzidenz Medium definition in storybook and website
- Properly sets font-family in TabTitle
- Adds fallback fonts in TabTitle
🎟 _Jira ticket:_ [PD-877](https://jira.mongodb.org/browse/PD-877)
> PD-877: Fixes TabTitle font-family

- .changeset/forty-seahorses-jam.md
- build.tsconfig.json
> Build Tabs types

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- package.json
> PD-911: Add engines to package.json

- .github/workflows/release.yml
> Updates to v14 in release yaml

- .changeset/twelve-carrots-speak.md
- packages/tokens/README.md
- packages/tokens/src/breakpoints.ts
- packages/tokens/src/index.ts
- Adds breakpoints to tokens package (precursor to building this into the provider and will help standardize bps across website)
> Adds breakpoints to tokens package

- .changeset/green-jokes-look.md
- packages/syntax/src/Syntax.tsx
Fixes an issue where line highlights don't span the entire line.
> Fix line highlighting issue

- .changeset/selfish-rabbits-repeat.md
- package.json
- package.tsconfig.json
> Fix UMD for publishing

- .changeset/calm-jokes-sing.md
- packages/lib/src/index.spec.ts
- packages/lib/src/index.ts
> Add enforceExhaustive helper to lib

- packages/button/README.md
Adds docs for the `glyph` Button prop.
> Add undocumented button prop

- .changeset/fluffy-seals-drum.md
- packages/typography/src/Typography.story.tsx
- packages/typography/src/Typography.tsx
I noticed when updating the Copyable branch to use the latest version of the typography package that it wasn't overriding the border color of `<InlineDefinition />` anymore because the border moved to the inside `<span />`. Looking into it I also noticed that the hover and focus states didn't seem to match what's shown in the design spec for [PD-832](https://jira.mongodb.org/browse/PD-832). This PR addresses the visual discrepancy and removes the `<span />`.
> Fixes inline code focus and hover state

- .changeset/poor-masks-sip.md
- packages/table/src/Cell.tsx
- packages/table/src/styles.tsx
- website/components/CodeDocs.tsx
- website/components/Grid.tsx
- website/components/Header.tsx
- website/components/PropTable.tsx
- website/components/navigation/MobileNavigation.tsx
- website/components/navigation/MobileNavigationGroup.tsx
- website/components/navigation/Navigation.tsx
- Feedback from weekly design Q/A session with Rob
> Style Updates to MongoDB.design

- website/components/CodeDocs.tsx
- website/components/Grid.tsx
- website/components/navigation/Navigation.tsx
> quick fixes

- packages/table/src/styles.tsx
Updates the table cell styles to use `box-sizing`
> change box-style to box-sizing

- .changeset/big-boxes-fold.md
- packages/text-input/README.md
- packages/text-input/src/TextInput.story.tsx
- packages/text-input/src/TextInput.tsx
- Adds darkMode to Input Component
- Style QA'd with Rob
🎟 _Jira ticket:_ [PD-931](https://jira.mongodb.org/browse/PD-931)
> PD-931: Adds darkMode to Input Component

- .changeset/fair-frogs-try.md
> Adds Changeset to Box fix

- website/package.json
- yarn.lock
> Upgrade next

- .changeset/grumpy-bees-fly.md
- .changeset/warm-tomatoes-poke.md
- packages/menu/src/Menu.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
> Fix menu scrollbars

- .changeset/six-berries-lick.md
- packages/typography/README.md
- packages/typography/src/FormElements.tsx
- packages/typography/src/Typography.story.tsx
- packages/typography/src/index.ts
> Adds Label and Description components to Typography package

- .changeset/weak-fireants-walk.md
- packages/typography/src/Typography.tsx
> Forward rest props to code element in InlineDefinition

- .changeset/rude-guests-compete.md
- .changeset/two-colts-shake.md
- package.json
- packages/lib/package.json
- packages/text-area/package.json
- scripts/package-builder.js
Unlike React, there shouldn't be any issues if there are multiple versions of prop-types installed. There may also be some repos that don't directly need prop-types. Making this dependency explicit will resolve these repos having a missing peer dependency. Holding off on splitting out the utility/helper code the package until there's a significant risk of inflating bundle sizes.
> Make "prop-types" an explicit dependency

- .changeset/giant-apples-smell.md
- packages/card/src/Card.tsx
- packages/mongo-nav/src/helpers/InteractionRingWrapper.tsx
- packages/mongo-nav/src/helpers/OrgNavLink.tsx
- packages/mongo-nav/src/mongo-select/Input.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/radio-group/src/Radio.tsx
- packages/text-area/src/TextArea.tsx
- packages/text-input/src/TextInput.tsx
- packages/typography/src/Link.tsx
- yarn.lock
> Updates #9DD0E7 to uiColors.blue.light1

- website/components/CodeDocs.tsx
Formats changelog
🎟 _Jira ticket:_ [PD-925](https://jira.mongodb.org/browse/PD-925)
> PD-925: Formats changelog

- .changeset/fair-parrots-shop.md
- packages/tabs/src/TabTitle.tsx
- packages/tabs/src/Tabs.story.tsx
🎟 _Jira ticket:_ [PD-923](https://jira.mongodb.org/browse/PD-923)
> PD-923: Adds pressed state to tabs component

- packages/logo/README.md
- packages/text-area/README.md
These were previously addressed in PD-788 PR
> Small Readme Updates to TextArea and Logo

- website/pages/_getComponentResources.tsx
Small tweaks to this file; without which we can't deploy!
> _getComponentResource Patch

- .changeset/blue-seas-heal.md
- packages/text-area/README.md
- packages/text-area/src/TextArea.spec.tsx
- packages/text-area/src/TextArea.tsx
changes where className is spread
> TextArea patch

- website/next.config.js
> Enable Realm to understand static routes without .html suffix

- website/package.json
- website/pages/component/palette/example.tsx
Makes Palette Example hex codes copyable in website
> Makes Palette Example hex codes copyable

- .changeset/big-books-watch.md
> Adds changeset for MongoNav updates

- website/components/navigation/Navigation.tsx
- website/pages/component/palette/example.tsx
- Makes interaction ring cleaner on Palette live example 
- Pushes down components in side nav
- Removes guidelines from list of things to iterate from to create side nav as we don't have material for that yet
> Polishing website

- .changeset/lemon-ways-design.md
- packages/mongo-nav/src/MongoNav.story.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
🎟 _Jira ticket:_ ["more" menu renders behind MongoNav when a z-index is set on the navigation](https://jira.mongodb.org/browse/PD-976)
> Do not portal MongoNav OrgNav more menu

- .changeset/forty-rules-laugh.md
- packages/marketing-modal/src/MarketingModal.tsx
> Fix Marketing modal button

- .changeset/honest-trees-share.md
- packages/button/src/Button.tsx
> Fix XSmall Button text casing

- .changeset/clever-deers-deliver.md
- packages/button/src/Button.tsx
- packages/tooltip/src/Tooltip.story.tsx
> Make Button work better with Popover and Tooltip

- .changeset/tricky-buses-notice.md
- packages/interaction-ring/src/InteractionRing.spec.tsx
- packages/interaction-ring/src/InteractionRing.tsx
🎟 _Jira ticket:_ [TextInput does not fire onFocus and onBlur](https://jira.mongodb.org/browse/PD-993)
> Always call onBlur and onFocus of Interaction ring wrapped components

- .changeset/metal-cups-switch.md
- packages/mongo-nav/README.md
- packages/mongo-nav/src/MongoNav.story.tsx
- packages/mongo-nav/src/data.ts
- packages/mongo-nav/src/types.ts
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
We're officially deprecating 2FA in Cloud in favor of the recently released Account MFA. To show this, we are a) advertising the new feature in the UserMenu and b) renaming and hiding the "Legacy 2FA" menu item for users that do not have it set up, since they will no longer be able to enroll in this functionality.
🎟 _Jira ticket:_ [PD-943](https://jira.mongodb.org/browse/PD-943)
Invision Link for changes: https://mongodb.invisionapp.com/share/H8XIP6KRVFM#/screens/422003152
Screenshot:
> PD-943: Update UserMenu for Account MFA

- .changeset/dull-tomatoes-sin.md
- packages/radio-group/src/Radio.tsx
> PD-989: Sets cursor: pointer on Radio labels

- .changeset/early-melons-brake.md
- packages/text-input/src/TextInput.tsx
> PD-1001, PD-10003: Text input updates

- website/components/navigation/MobileNavigation.tsx
- website/pages/component/typography/example.tsx
- Makes typography href local (to better demonstrate arrow behavior)
- Better aligns hamburger menu on tablet
> Adds more polish to mongodb.design

- .changeset/modern-donuts-grab.md
- packages/text-input/src/TextInput.tsx
> Fix border on disabled TextInput component with autoComplete content

- .changeset/config.json
- .github/pull_request_template.md
- .github/workflows/release.yml
- README.md
Update actions and documentation to reflect the change from "master" to "main".
🎟 _Jira ticket:_ [Rename "master" branch to "main"](https://jira.mongodb.org/browse/PD-750)
> PD-750: Rename "master" branch to "main"

- .changeset/few-books-accept.md
- packages/popover/src/Popover.tsx
- packages/tooltip/src/Tooltip.spec.tsx
> Fix Popover transition in when not using a portal

- package.json
- website/package.json
- yarn.lock
> Update TypeScript to 4.1

- .changeset/young-pens-wash.md
- packages/table/src/Cell.tsx
- packages/table/src/HeaderRow.tsx
- packages/table/src/Row.spec.tsx
- packages/table/src/Row.tsx
- packages/table/src/TableHead.tsx
- packages/table/src/TableHeader.tsx
https://jira.mongodb.org/browse/PD-1072
https://jira.mongodb.org/browse/PD-1073
> Fix Table aria attributes

- .changeset/light-windows-nail.md
- packages/toast/README.md
- packages/toast/src/Toast.spec.tsx
- packages/toast/src/Toast.tsx
https://jira.mongodb.org/browse/PD-1079
> Add aria-live to Toast

- .changeset/light-windows-nail.md
Toast has not had a major release yet, so any breaking changings prior to the real initial release should be minor
> Make Toast changeset minor

- .changeset/silent-numbers-punch.md
- website/components/CodeDocs.tsx
- website/layouts/ComponentLayout.tsx
- website/pages/component/tabs/example.tsx
> Adds accessible labels to LGUI Tabs component in website

- .changeset/fair-brooms-remember.md
- packages/toast/src/Toast.tsx
> Fix toast imports

- website/utils/renderer.ts
> Import extractCritical from LGUI Emotion Server

- .changeset/tall-houses-search.md
- packages/tooltip/package.json
> Fix tooltip dependency on icon

- website/components/CodeDocs.tsx
- website/components/ComingSoon.tsx
- website/components/News.tsx
- website/components/PropTable.tsx
- website/components/live-example/LiveExample.tsx
- website/components/navigation/Navigation.tsx
- website/layouts/BaseLayout.tsx
- website/layouts/ComponentLayout.tsx
- website/layouts/Footer.tsx
- website/pages/component/banner/guidelines.mdx
- website/pages/component/confirmation-modal/example.tsx
- website/pages/component/logo/example.tsx
- website/pages/component/marketing-modal/example.tsx
- website/pages/component/modal/example.tsx
- website/pages/component/palette/example.tsx
- website/pages/component/popover/example.tsx
- website/pages/component/radio-box-group/example.tsx
- website/pages/component/radio-group/example.tsx
- website/pages/component/select/example.tsx
- website/pages/component/toast/example.tsx
- website/pages/component/toggle/example.tsx
- website/pages/component/tooltip/example.tsx
- website/pages/index.tsx
- website/styles/constants.ts
- website/utils/figmaLinks.ts
- website/utils/styleConstants.ts
- website/utils/types.ts
- Finally adds Figma links to components
- Adds type for Components
- Creates variables for sizes used on XLarge and Large desktop
- Fixes bug on home page 
- Cleans up mobile
> Website Bugs

- website/package.json
> Disable Next.js telemetry

- .changeset/swift-socks-listen.md
- packages/tabs/src/Tabs.spec.tsx
- packages/tabs/src/Tabs.tsx
Fixes bug where props were being overwritten rather than cloned in Tab
> Properly spreads properties in Tab

- .changeset/plenty-mails-peel.md
- packages/popover/src/Popover.story.tsx
- packages/popover/src/Popover.tsx
- website/pages/component/popover/example.tsx
> Fix popover examples when not using Portal

- .changeset/stupid-candles-refuse.md
- packages/mongo-nav/src/mongo-select/OrgSelect.spec.tsx
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.spec.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.tsx
- packages/mongo-nav/src/org-nav/OrgNav.spec.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.spec.tsx
- packages/mongo-nav/src/project-nav/ProjectNav.tsx
- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenuTrigger.tsx
🎟 _Jira ticket:_ [PD-1039](https://jira.mongodb.org/browse/PD-1039)
> PD-1039: Sets "aria-expand" property on buttons across MongNav

- .changeset/dull-bears-carry.md
- .changeset/nasty-ties-chew.md
- packages/icon/src/glyphCommon.ts
- packages/select/README.md
- packages/select/src/MenuButton.tsx
🎟 _Jira ticket:_ [PD-1057](https://jira.mongodb.org/browse/PD-1057)
> PD-1057: Sets ARIA role presentation on the caret in Select

- .changeset/healthy-pumas-hope.md
- packages/code/src/Code.tsx
Previously, the copy button was causing form submissions when within a form. This fixes that issue.
🎟 _Jira ticket:_ [Prevent default behavior of copy button in Code component](https://jira.mongodb.org/browse/PD-1112)
> PD-1112: Prevent accidental form submissions in Code

- website/components/live-example/Knobs.tsx
- website/layouts/ComponentLayout.tsx
> Adds opengraph title to component pages and makes toggle default size on mobile and tablet

- website/layouts/ComponentLayout.tsx
- website/pages/_app.tsx
- website/utils/metaTagKey.ts
> Add keys to og:titles to help Next.js prioritize

- .changeset/funny-lizards-kick.md
- packages/tooltip/src/Tooltip.tsx
- packages/tooltip/src/tooltipUtils.tsx
A quick win to improve the visual consistency between our Tooltip component and our Figma library. Also fixes a bug with the tooltip displaying a border between the notch and main area of the tooltip.
> Tooltip style consistency updates

- website/pages/component/banner/guidelines.mdx
- website/pages/component/toast/guidelines.mdx
- website/pages/component/toast/guidelines.tsx
🎟 _Jira ticket:_ [PD-1121](https://jira.mongodb.org/browse/PD-1121)
> PD-1121: Adds Toast guidelines to website

- packages/mongo-nav/src/user-menu/UserMenu.spec.tsx
- packages/mongo-nav/src/user-menu/UserMenu.tsx
> Fixes Forums link in UserMenu

- website/components/News.tsx
- website/pages/index.tsx
- website/utils/componentData.ts
> Website Updates: Thumbnails, Descriptions, Apostrophe

- .changeset/wet-pianos-divide.md
- packages/mongo-nav/src/mongo-select/OrgSelect.tsx
- packages/mongo-nav/src/mongo-select/ProjectSelect.tsx
- packages/mongo-nav/src/org-nav/OrgNav.tsx
- packages/mongo-nav/src/user-menu/UserMenuTrigger.tsx
🎟 _Jira ticket:_ [PD-1056](https://jira.mongodb.org/browse/PD-1056)
> PD-1056: Makes Icons accessible in MongoNav

- .changeset/four-walls-obey.md
- packages/palette/src/ui-colors.less
- packages/palette/src/uiColors.ts
🎟 _Jira ticket:_ [PD-1124](https://jira.mongodb.org/browse/PD-1124)
> PD-1124: Updates uiColors.gray.base

- .changeset/itchy-maps-refuse.md
- packages/a11y/README.md
- packages/a11y/package.json
- packages/a11y/src/A11y.spec.tsx
- packages/a11y/src/VisuallyHidden.tsx
- packages/a11y/src/index.ts
- packages/a11y/src/useAccessibleForm.ts
- packages/a11y/tsconfig.json
Initial release of a11y package
> Creates a11y package

- .changeset/lazy-sheep-do.md
- packages/typography/src/Link.tsx
- yarn.lock
> Adds rel prop to Link component by default when href is external

- website/components/live-example/Knobs.tsx
- website/components/navigation/MobileNavigation.tsx
- website/pages/component/toast/guidelines.mdx
> PD-1189: Adds pointer to Navigation in Mobile/Tablet, Sets width of Select dropdown

- .changeset/quick-pears-tan.md
- packages/text-input/src/TextInput.spec.tsx
- packages/text-input/src/TextInput.tsx
> Fixes console warning in TextInput component

- .changeset/pretty-brooms-attack.md
- packages/box/package.json
- packages/button/package.json
- packages/hooks/package.json
- packages/mongo-nav/package.json
- packages/pipeline/package.json
- packages/popover/package.json
- packages/table/package.json
- packages/toast/package.json
- packages/tooltip/package.json
- yarn.lock
🎟 _Jira ticket:_ [PD-1219](https://jira.mongodb.org/browse/PD-1219)
> PD-1219: Updates lodash verison from 4.17.20 to 4.17.21

- .changeset/tough-wasps-pump.md
- packages/callout/README.md
- packages/callout/package.json
- packages/callout/src/Callout.story.tsx
- packages/callout/src/Callout.tsx
- packages/callout/tsconfig.json
- website/pages/component/callout/example.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-837](https://jira.mongodb.org/browse/PD-837)
> PD-837: Adds baseFontSize prop to Callout component

- .github/workflows/release.yml
- package.json
> Version Script Naming Update

- .changeset/eighty-glasses-pay.md
- packages/code/src/renderingPlugin.tsx
> Provides callback to sort() function in Syntax renderingPlugin

- .changeset/shy-spoons-beg.md
- packages/radio-box-group/src/RadioBox.tsx
> PD-1224: Updates border-radius on RadioBox

- website/pages/component/menu/guidelines.mdx
- website/pages/component/menu/guidelines.tsx
> PD-1223: Adds guidelines for Menu component to .design

- .github/pull_request_template.md
Quick update to the PR template
> Add testing section to PR template

- website/pages/component/icon/guidelines.mdx
- website/pages/component/icon/guidelines.tsx
🎟 _Jira ticket:_ [PD-1247](https://jira.mongodb.org/browse/PD-1247)
> PD-1247: Adds icon guidelines to .design

- website/layouts/BaseLayout.tsx
- website/pages/index.tsx
A few small fixes for .design:
- Fixes issue where page wouldn't scroll on mobile.
- Fixes issue where homepage grid items would lose their image aspect ratio.
- Applies shadow to hover overline labels to improve readability.
> Fixes website scrolling issue on mobile

- .changeset/happy-points-count.md
- packages/select/README.md
- packages/select/src/MenuButton.tsx
- packages/select/src/Select.spec.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-1070](https://jira.mongodb.org/browse/PD-1070)
> PD-1070: rm role=combobox from Select component

- .github/workflows/release.yml
- README.md
- Working CI run here: https://github.com/brookescarlett/leafygreen-ui/runs/2151667718
> Update release workflow

- .changeset/purple-tips-double.md
- packages/button/src/Button.tsx
> Updates padding in Button component

- package.json
- yarn.lock
> Update gh-pages dep

- .changeset/dry-gifts-melt.md
- packages/typography/src/Typography.tsx
> PD-1280: Update line-height in H3 component

- .github/workflows/release.yml
> Add ts:build to release workflow

- .changeset/weak-planets-judge.md
> Update packages that were released without .d.ts files

- .changeset/spicy-badgers-shout.md
- packages/table/README.md
- packages/table/src/DarkModeContext.tsx
- packages/table/src/Row.tsx
- packages/table/src/Table.story.tsx
- packages/table/src/Table.tsx
- packages/table/src/TableHeader.tsx
- website/pages/component/table/example.tsx
🎟 _Jira ticket:_ [PD-822](https://jira.mongodb.org/browse/PD-822)
> PD-822: Adds darkmode prop to table component

- website/pages/component/code/example.tsx
Adds `showLineNumbers` prop to `Code` component's example tab on mongodb.design.
Tested locally with `yarn dev`
> Add showLineNumbers prop to Code example tab

- .changeset/spotty-zoos-hear.md
- packages/text-input/src/TextInput.tsx
> Checks for existence of either `label` or `aria-labelledby` props, rather than requiring both, before logging a warning to the console

- .changeset/giant-eagles-decide.md
> With changeset

- .changeset/thick-pillows-repeat.md
- packages/select/src/Option.tsx
- packages/select/src/styleSets.ts
> PD-1055: Update focus state in Select component for improved contrast ratio

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
🎟 _Jira ticket:_ [PD-1289](https://jira.mongodb.org/browse/PD-1289)
> PD-1289: Improve private subrepo workflow support

- .changeset/silly-pants-hang.md
- packages/table/src/Row.tsx
- packages/table/src/Table.spec.tsx
> Ensures that cells with a value of 0 render properly in the table

- .changeset/lovely-comics-buy.md
- packages/tooltip/src/Tooltip.spec.tsx
- packages/tooltip/src/Tooltip.tsx
- website/pages/component/tooltip/example.tsx
🎟 _Jira ticket:_ [PD-1142](https://jira.mongodb.org/browse/PD-1142)
> PD-1142: Allows Tooltips to contain interactive content

- .changeset/eighty-boats-float.md
- packages/button/src/styles.ts
🎟 _Jira ticket:_ [PD-1319](https://jira.mongodb.org/browse/PD-1319)
> PD-1319: Explicitly set color on focused buttons

- .changeset/thirty-walls-jump.md
- packages/icon-button/src/IconButton.tsx
> PD-838: Transitions color in IconButton component

- .changeset/weak-deers-sell.md
- packages/menu/src/MenuItem.tsx
- packages/menu/src/SubMenu.tsx
🎟 _Jira ticket:_ [PD-1036](https://jira.mongodb.org/browse/PD-1036)
> PD-1036: Update inactive menu item icon color from base to dark1

- .changeset/brown-bikes-promise.md
- packages/menu/src/MenuItem.tsx
- packages/menu/src/SubMenu.tsx
> Adds `role="presentation"` to glyphs rendered to the left of menuitems and submenus 

- .changeset/funny-bulldogs-jump.md
- packages/table/src/Row.tsx
> Adds darkMode to dep array in useMemo in Row component

- packages/confirmation-modal/README.md
> Fix text in confirmation modal readme

- .changeset/funny-mugs-wait.md
- packages/callout/src/Callout.spec.tsx
- packages/callout/src/Callout.tsx
> PD-1371: Hides decorative image in Callout component

- website/pages/component/code/example.tsx
🎟 _Jira ticket:_ [PD-1346](https://jira.mongodb.org/browse/PD-1346)
> PD-1346: Adds highlight line functionality to code example

- .changeset/tiny-days-flow.md
- packages/text-input/src/TextInput.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-1350](https://jira.mongodb.org/browse/PD-1350)
> PD-1350: Updates interaction ring color on hover

- packages/text-input/src/TextInput.spec.tsx
- packages/text-input/src/TextInput.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-1352](https://jira.mongodb.org/browse/PD-1352)
> PD-1352: Allows supplying just an aria-label when type is search

- .changeset/five-mails-remember.md
- packages/confirmation-modal/README.md
- packages/confirmation-modal/src/ConfirmationModal.story.tsx
- packages/confirmation-modal/src/ConfirmationModal.tsx
- packages/marketing-modal/README.md
- packages/marketing-modal/src/MarketingModal.story.tsx
- packages/marketing-modal/src/MarketingModal.tsx
- packages/modal/README.md
- packages/modal/src/Footer.tsx
- packages/modal/src/Modal.story.tsx
- packages/modal/src/Modal.tsx
- website/pages/component/code/example.tsx
- website/pages/component/confirmation-modal/example.tsx
- website/pages/component/marketing-modal/example.tsx
- website/pages/component/modal/example.tsx
- yarn.lock
🎟 _Jira ticket:_ [PD-1335](https://jira.mongodb.org/browse/PD-1335)
- [] I have added tests that prove my fix is effective or that my feature works
> PD-1353: Adds dark mode to modals

- .changeset/stale-lizards-unite.md
- packages/button/src/Button.tsx
> PD-1378: Center text within buttons

- packages/button/UPGRADE.md
> Updates Button upgrade guide

- packages/button/UPGRADE.md
> Moves design upgrade guidelines to proper section

- .changeset/purple-pillows-accept.md
- packages/radio-group/src/RadioGroup.tsx
> PD-1417: Add xsmall to valid proptypes in RadioGroup

- .changeset/curly-pens-brush.md
- packages/radio-box-group/src/RadioBox.tsx
🎟 _Jira ticket:_ [PD-1363](https://jira.mongodb.org/browse/PD-1363)
> PD-1363: Fixes issue where not all RadioBox components were being properly filled

- .changeset/tidy-beans-call.md
- packages/select/src/Option.tsx
> PD-1413: Fixes reference in Select component

- storybook/config.js
> Update pointer with fixed docs icon in UserMenu

- .changeset/great-news-admire.md
- .changeset/purple-dragons-complain.md
> Adds changesets for idAllocator PR

- .changeset/lovely-carpets-tell.md
- packages/select/src/Option.tsx
- website/components/navigation/Navigation.tsx
- website/layouts/BaseLayout.tsx
- website/layouts/FoundationLayout.tsx
- website/pages/_app.tsx
- website/pages/component/banner/guidelines.mdx
- website/pages/component/callout/guidelines.mdx
- website/pages/component/checkbox/guidelines.mdx
- website/pages/component/checkbox/guidelines.tsx
- website/pages/component/code/guidelines.mdx
- website/pages/component/confirmation-modal/guidelines.mdx
- website/pages/component/confirmation-modal/guidelines.tsx
- website/pages/component/icon/guidelines.mdx
- website/pages/component/marketing-modal/guidelines.mdx
- website/pages/component/marketing-modal/guidelines.tsx
- website/pages/component/menu/guidelines.mdx
- website/pages/component/modal/guidelines.mdx
- website/pages/component/table/guidelines.mdx
- website/pages/component/text-input/guidelines.mdx
- website/pages/component/toast/guidelines.mdx
- website/pages/component/tooltip/guidelines.mdx
- website/pages/component/typography/guidelines.mdx
- website/pages/component/typography/guidelines.tsx
- website/pages/foundation/grid.mdx
- website/pages/foundation/icon-creation.mdx
> Adds Guidelines

- .changeset/short-lemons-try.md
> Add missing changeset

- .changeset/strange-swans-fail.md
Updates banner string in MongoNav from "Cloud" to "Atlas"
🎟 _Jira ticket:_ [PD-1445](https://jira.mongodb.org/browse/PD-1445)
> PD 1445 Update MongoNav banner string

- .changeset/dull-lemons-crash.md
- packages/typography/src/Link.spec.tsx
- packages/typography/src/Link.tsx
- packages/typography/src/Typography.story.tsx
- website/pages/component/typography/example.tsx
Fixes the Link component to behave as a native anchor tag when a passed a relative `href` prop
🎟 _Jira ticket:_ [PD-1405](https://jira.mongodb.org/browse/PD-1405)
In Storybook, choose the 2nd "Link href" option. Alternatively, pass an `href` string that _does not_ begin with `http://` (or `https://`) to a `Link` component.
> PD-1405: Fixes Link component for relative href

- .changeset/lazy-flowers-share.md
- packages/radio-box-group/src/RadioBox.tsx
- packages/radio-box-group/src/RadioBoxGroup.spec.tsx
Issues stemming from `RadioBox` `id` allocation caused all buttons in a group to have identical ids. This PR fixes this issue 
🎟 _Jira ticket:_ [PD-1443](https://jira.mongodb.org/browse/PD-1443)
Run Storybook locally, navigate to the "Radio Box Group" story and refresh the page. Clicking a box should now trigger it to be checked.
> PD-1443 fix radio box group regression

- .changeset/rotten-pots-pretend.md
- packages/callout/src/Callout.tsx
Updates Callout background color to white
🎟 _Jira ticket:_ [PD-1457t](https://jira.mongodb.org/browse/PD-1457)
> PD-1457 Updates Callout bg color

- .changeset/bright-zebras-tap.md
🎟 _Jira ticket:_ [PD-1466](https://jira.mongodb.org/browse/PD-1466)
> PD-1466: Update support link

- package.json
- yarn.lock
Updates lodash types in dev Deps
🎟 _Jira ticket:_ [PD-1470](https://jira.mongodb.org/browse/PD-1470)
> Upgrades @types/lodash

- .changeset/quick-donkeys-eat.md
- packages/tooltip/src/Tooltip.spec.tsx
- packages/tooltip/src/Tooltip.tsx
Fixes a bug where event handlers passed into a Tooltip trigger were not called with the correct event object (or at all)
🎟 _Jira ticket:_ [PD-1390](https://jira.mongodb.org/browse/PD-1390)
Add an `onClick`, `onMouseEnter`, `onMouseLeave`, `onFocus`, or `onBlur` event handler to the `trigger` element of a Tooltip. These functions should run with the correct `event` in local scope.
> PD-1390 tooltip trigger on click

- .changeset/real-kids-dress.md
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.story.tsx
- packages/button/src/Button.tsx
Fixes a bug where a Button with an `href` and `disabled=true` would still navigate.
🎟 _Jira ticket:_ [PD-1419](https://jira.mongodb.org/browse/PD-1419)
In Storybook, set the `disabled` prop to true, and set the `href` prop to anything other than `undefined`. Clicking the button should not navigate.
> PD-1419 Ensures disabled links don't navigate

- packages/icon/src/glyphs/index.ts
> PD-1439 Fix minus icon

- .changeset/nice-trains-pretend.md
- packages/typography/README.md
- packages/typography/src/Typography.story.tsx
- packages/typography/src/Typography.tsx
Updates the appearance of our InlineCode component to reflect [changes made to the Figma component](https://www.figma.com/file/4h2VwjCuJUbeZ7hzD2J1rq/LeafyGreen-Design-System?node-id=3060%3A18064), and adds dark mode support.
🎟 _Jira ticket:_ [Implement update to inline code appearance: Dev](https://jira.mongodb.org/browse/PD-1527)
- Check that the storybook implementation of InlineCode matches the [Figma specification](https://www.figma.com/file/4h2VwjCuJUbeZ7hzD2J1rq/LeafyGreen-Design-System?node-id=3060%3A18064), including hover and focus states.
- Use the darkMode checkbox in the storybook knobs to enable darkMode, and check that the darkMode InlineCode implementation matches Figma as well.
> PD-1527: InlineCode appearance update and dark mode support

- packages/interaction-ring/src/InteractionRing.tsx
The InteractionRing component was applying some default styles to the children passed to it that were largely unused, and causing issues when TextArea and TextInput were used together.
🎟 _Jira ticket:_ [PD-1540](https://jira.mongodb.org/browse/PD-1540)
- [] Bugfix (non-breaking change which fixes an issue)
> PD-1540: Removes problematic styles from InteractionRing component

- README.md
Just fixing a broken link in the README.md.
> Updating README.md to fix a broken link

- .github/workflows/nodejs.yml
> Removes Mongonav references

- packages/select/README.md
Fixes a small error in the documented types for Select options.
> Fix README for Select option

- .changeset/slimy-moose-travel.md
- packages/radio-group/package.json
> PD-1581 Adds Hooks dependency to Radio Group

- scripts/package-builder.js
> Error handling in create-package

- .changeset/giant-cows-fold.md
- packages/lib/src/index.ts
> Console once functions

- website/components/navigation/MobileNavigation.tsx
Quick fix removing the "=" character being rendered in the .design navigation.
https://mongodb.slack.com/archives/CFFA5BS79/p1635885638060600
> Remove = character being rendered in the .design navigation

- .changeset/chatty-squids-design.md
- packages/segmented-control/package.json
> PD-1661 Bump lib & typography versions

- .changeset/wise-wolves-rest.md
- packages/select/src/Select.spec.tsx
- packages/select/src/Select.tsx
🎟 _Jira ticket:_ 
- [PD-1638](https://jira.mongodb.org/browse/PD-1638)
- [PD-1362](https://jira.mongodb.org/browse/PD-1362)
Test with the following story: 
```js
.add('Tab test', () => {
return (
<LeafygreenProvider>
<div
className={css`
display: block;
`}
>
<Select
label="Label"
description="Description"
placeholder="Placeholder"
name="Name"
size={Size.Default}
defaultValue="cat"
>
<Option value="dog">Dog</Option>
<Option value="cat">Cat</Option>
<OptionGroup label="Less common">
<Option value="hamster">Hamster</Option>
<Option value="parrot">Parrot</Option>
</OptionGroup>
</Select>
<TextInput
label="Email"
description="Enter your email below"
placeholder="your.email@example.com"
/>
<TextInput
label="Password"
description="Enter your email below"
placeholder="your.email@example.com"
/> …
```
> [PD-1638, PD-1362] Fixes Select keyboard navigation

- .changeset/shiny-sloths-joke.md
- packages/expandable-card/package.json
> PD-1694 Upgrade `lib` dep in expandable card

- README.md
I removed the section on working with Git Submodules and updated the node version to be less than 17.0.0.
> Remove submodules and update node version in README

- .changeset/poor-sloths-own.md
- packages/palette/README.md
- packages/palette/UPGRADE.md
- packages/palette/package.json
- packages/palette/src/index.ts
- packages/palette/src/palette.less
- packages/palette/src/palette.spec.ts
- packages/palette/src/palette.story.tsx
- packages/palette/src/palette.ts
- storybook/main.js
- storybook/webpack.config.js
- website/pages/component/palette/example.tsx
This PR adds a new `palette.ts` and `palette.less` file reflecting the new palette being used for the brand updates.
🎟 _Jira ticket:_ [Update palette colors in LG UI](https://jira.mongodb.org/browse/PD-1714)
> PD-1714: Update colors in palette to reflect brand refresh

- build.tsconfig.json
> PD-1717 Update build.tsconfig.json

- packages/form-footer/README.md
- website/pages/component/form-footer/example.tsx
> PD-1700 Fixes name of cancelButtonText prop

- .changeset/new-zebras-drive.md
- packages/interaction-ring/src/InteractionRing.tsx
🎟 _Jira ticket:_ [PD-1707](https://jira.mongodb.org/browse/PD-1707)
> PD-1707 Refresh Interaction Ring

- .changeset/tender-shrimps-flash.md
- packages/toggle/src/Toggle.tsx
The toggle element is currently a `<button>` element without a `type` attribute. The HTML default is `submit`, which means any `<Toggle>` rendered inside a form will submit that form when it's clicked.
🎟 _Jira ticket:_ [PD-1731](https://jira.mongodb.org/browse/PD-1731)
> PD-1731: Add button type to Toggle button

- storybook/preview-head.html
- website/styles/globals.tsx
> Adds new fonts to Storybook config and website

- .changeset/lovely-pianos-pump.md
- packages/banner/src/Banner.tsx
🎟 _Jira ticket:_ [PD-1709](https://jira.mongodb.org/browse/PD-1709)
> PD-1709: Refresh Banner

- .changeset/config.json
- .changeset/mean-rice-exercise.md
- packages/leafygreen-provider/src/TypographyContext.tsx
- packages/tokens/src/fontFamilies.ts
- packages/typography/src/FormElements.tsx
- packages/typography/src/Link.tsx
- packages/typography/src/Typography.story.tsx
- packages/typography/src/Typography.tsx
- packages/typography/src/styles.tsx
> PD-1710 Refresh typography

- website/pages/component/combobox/example.tsx
> Fix Combobox website example

- packages/palette/README.md
🎟 _Jira ticket:_ [Add documentation for .less palette variables for easy reference](https://jira.mongodb.org/browse/PD-1736)
> PD-1736: Add .less variable documentation to Palette README

- .changeset/sixty-windows-listen.md
- packages/button/src/Button.tsx
- packages/button/src/ButtonIcon.tsx
- packages/button/src/styles.ts
- packages/button/src/types.ts
> PD-1707 Refresh button

- packages/radio-box-group/package.json
- packages/radio-box-group/src/RadioBox.tsx
- packages/radio-box-group/tsconfig.json
> PD-1707 Refresh radio box group

- .changeset/heavy-planes-pump.md
- packages/toast/src/Toast.spec.tsx
- packages/toast/src/Toast.tsx
- packages/toast/src/ToastProgressBar.tsx
- packages/typography/src/styles.tsx
🎟 _Jira ticket:_ [PD-1709](https://jira.mongodb.org/browse/PD-1709)
> PD-1709: Refresh Toast

- packages/banner/package.json
- packages/banner/src/Banner.tsx
- packages/banner/tsconfig.json
This is a continuation of this: [#PR1092](https://github.com/mongodb/leafygreen-ui/pull/1092). These are the hover styles that were missing from that initial PR and since this is part of that PR I am not including a changeset.
🎟 _Jira ticket:_ [PD-1709](https://jira.mongodb.org/browse/[PD-1709])
> PD-1709: Refresh Banner Hover

- .changeset/five-poems-do.md
- packages/hooks/README.md
- packages/hooks/src/useForwardedRef.tsx
> Documents hooks updates

- packages/palette/src/palette.ts
> Update gray dark 3, #21313C -> #1C2D38

- .changeset/friendly-eggs-smash.md
- packages/tabs/src/TabTitle.tsx
- packages/tabs/src/Tabs.story.tsx
- packages/tabs/src/Tabs.tsx
> PD-1708 Group 2: refresh tabs

- .changeset/gentle-tools-invent.md
- packages/inline-definition/README.md
- packages/inline-definition/src/InlineDefinition.tsx
> [PD-1710, PD-1787] Group 4:  refresh inline definition

- packages/combobox/src/Chip.tsx
- packages/combobox/src/Combobox.spec.tsx
- packages/combobox/src/Combobox.story.tsx
- packages/combobox/src/Combobox.styles.ts
> Adds long text support

- packages/combobox/src/Combobox.spec.tsx
- packages/combobox/src/Combobox.tsx
> PD-1785 - Fix combobox focus/blur

- .changeset/fair-panthers-repair.md
- packages/radio-group/package.json
- packages/radio-group/src/Radio.tsx
- packages/radio-group/tsconfig.json
🎟 _Jira ticket:_ [PD-1712](https://jira.mongodb.org/browse/PD-1712)
> PD-1712: Refresh radio group

- packages/stepper/src/EllipseStep.tsx
- packages/stepper/src/NewStep.tsx
- packages/stepper/src/NewStepper.tsx
- packages/stepper/src/StepIcon.tsx
- packages/stepper/src/types.ts
> [DRAFT] Pd 1820 temp

- .changeset/bright-cherries-destroy.md
- packages/toggle/package.json
- packages/toggle/src/Toggle.tsx
- packages/toggle/tsconfig.json
🎟 _Jira ticket:_ [PD-1712](https://jira.mongodb.org/browse/PD-1712)
> PD-1712: Refresh toggle

- storybook/preview-head.html
- website/styles/globals.tsx
> Remove bold and light Euclid font-face

- packages/combobox/README.md
> Update Combobox README.md

- website/updates/2021-09-29-segmented-control.md
- website/updates/2021-11-02-forms.md
- website/updates/2022-01-19-combobox.md
- yarn.lock
> Adds new news

- packages/button/CHANGELOG.md
> Clarifies Button 13.0.1 changelog

- .changeset/hip-plants-unite.md
- packages/text-input/package.json
- packages/text-input/tsconfig.json
Adds the `@leafygreen-ui/tokens` dependency to the `text-input` package.
> Add tokens dependency to text-input

- .changeset/dirty-carpets-fold.md
- packages/lib/src/createUniqueClassName/index.ts
> Publish createUniqueClassName

- .github/pull_request_template.md
> Adds Feedback levels to PR template

- babel.config.js
- storybook/webpack.config.js
🎟 _Jira ticket:_ [PD-1948](https://jira.mongodb.org/browse/PD-1948)
> Resolves new storybook issue

- .changeset/funny-wasps-share.md
- packages/lib/src/createUniqueClassName/createUniqueClassName.spec.ts
- packages/lib/src/createUniqueClassName/index.ts
🎟 _Jira ticket:_ [PD-1915](https://jira.mongodb.org/browse/PD-1915)
> PD-1915: createUniqueClassName Prefix

- .changeset/happy-fishes-agree.md
- packages/typography/src/Typography.tsx
> changing h3 font-weight to 600

- .changeset/serious-readers-sing.md
- packages/expandable-card/package.json
- packages/expandable-card/src/ExpandableCard.tsx
🎟 _Jira ticket:_ [PD-1965](https://jira.mongodb.org/browse/PD-1965)
> PD-1965: Expandable Card Styles + Dependencies

- .changeset/config.json
- .github/workflows/release.yml
Updates the `changesets` action reference
> Fix action branch

- website/utils/componentData.ts
🎟 _Jira ticket:_ [PD-1913](https://jira.mongodb.org/browse/PD-1913)
> PD-1913: Updating Figma links and adding missing component data

- website/pages/component/confirmation-modal/example.tsx
🎟 _Jira ticket:_ [PD-1960](https://jira.mongodb.org/browse/PD-1960)
> PD-1960: Website - Adding variant knob to Confirmation Modal

- .changeset/unlucky-islands-joke.md
- packages/expandable-card/package.json
🎟 _Jira ticket:_ [PD-1965](https://jira.mongodb.org/browse/PD-1965)
> PD-1965: Updating package versions on Expandable Card 

- .changeset/khaki-cats-matter.md
- packages/form-footer/package.json
🎟 _Jira ticket:_ [PD-1828](https://jira.mongodb.org/browse/PD-1828)
> PD-1828: Updating package versions on Form Footer

- website/pages/component/confirmation-modal/example.tsx
> PD 1960: Website - Confirmation Modal variant knob build:ts fix

- .changeset/eighty-eyes-sort.md
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.tsx
- packages/button/src/styles.ts
- packages/button/src/types.ts
🎟 _Jira ticket:_ [PD-1992](https://jira.mongodb.org/browse/PD-1992)
> PD-1992: Restoring as prop override to Button component

- .changeset/purple-pillows-try.md
- packages/table/src/Row.tsx
> Removing cursor:not-allowed on disabled Rows

- .changeset/bright-cameras-sell.md
- packages/checkbox/src/Checkbox.tsx
When working with the new Checkbox, I noticed (similar to [with Modal](https://github.com/mongodb/leafygreen-ui/pull/1189)) that it seems like we need to re-initiate a stacking context to prevent z-index from leaking out unintentionally ([like so](https://jira.mongodb.org/browse/CLOUDP-121326))
🎟 _Jira ticket:_ (Super small so didn't bother to file a PD, but happy to)
Checkboxes shouldn't stick out over things.
> Create new stacking context for Checkbox

- website/components/navigation/Navigation.tsx
- website/pages/foundation/refresh-guide.mdx
🎟 _Jira ticket:_ [PD-1988](https://jira.mongodb.org/browse/PD-1988)
> PD-1988: Temp page for brand guidance on .design

- scripts/slackbot.js
Updates the Slackbot channel to `#leafygreen-ui-releases`
> Update slackbot channel

- .changeset/sixty-elephants-allow.md
- packages/confirmation-modal/package.json
- packages/side-nav/package.json
- packages/side-nav/src/SideNav.story.tsx
- packages/side-nav/src/SideNavItem/CollapsedSideNavItem.tsx
> Fixes SideNav visual bugs

- .changeset/silent-snails-invent.md
- packages/expandable-card/tsconfig.json
> Fixes Expandable Card TS build

- .changeset/stale-horses-bathe.md
- packages/checkbox/src/Checkbox.tsx
🎟 _Jira ticket:_ [PD-2069](https://jira.mongodb.org/browse/PD-2069)
> PD-2069: Update the alignment of the checkbox label when there are multiple lines

- .changeset/rich-islands-cross.md
- .changeset/sixty-elephants-allow.md
- packages/combobox/package.json
- packages/combobox/tsconfig.json
> Update combobox dependencies

- .changeset/spotty-forks-march.md
- packages/palette/src/palette.less
- packages/palette/src/palette.spec.ts
- packages/palette/src/palette.ts
🎟 _Jira ticket:_ [PD-2064](https://jira.mongodb.org/browse/PD-2064)
> PD-2064: Palette - gray dark 4

- .changeset/warm-socks-occur.md
- packages/button/src/ButtonIcon.tsx
🎟 _Jira ticket:_ [PD-2074](https://jira.mongodb.org/browse/PD-2074)
> PD-2074: Changing disabled button icon color

- .changeset/eight-humans-tell.md
- packages/portal/tsconfig.json
- packages/tooltip/src/Tooltip.story.tsx
- packages/tooltip/src/Tooltip.tsx
- packages/typography/src/index.ts
🎟 _Jira ticket:_ [PD-2071](https://jira.mongodb.org/browse/PD-2071)
> PD-2071: Refresh tooltip darkmode

- .changeset/blue-donuts-give.md
- packages/combobox/src/Combobox.styles.ts
- packages/combobox/src/Combobox.tsx
- packages/hooks/src/useAvailableSpace.ts
- packages/menu/src/Menu.tsx
- packages/select/src/ListMenu.tsx
> Menu max height 0 bug

- .changeset/mean-steaks-sip.md
- packages/logo/src/utils.ts
🎟 _Jira ticket:_ [PD-2102](https://jira.mongodb.org/browse/PD-2102)
> PD-2102: SupportedColorsMap update

- .changeset/wet-jeans-greet.md
- packages/text-input/package.json
- packages/text-input/src/style.ts
- packages/text-input/tsconfig.json
- yarn.lock
🎟 _Jira ticket:_ [PD-2092](https://jira.mongodb.org/browse/PD-2092)
> PD-2092: text input darkmode updates

- .storybook/manager-head.html
- .storybook/preview-head.html
- website/styles/globals.tsx
`bold` alias defaults to 700 in Chrome, Safari, FF & Edge
> Removes `bold` from font-face declaration

- .changeset/modern-emus-happen.md
- packages/typography/src/Disclaimer.tsx
🎟 _Jira ticket:_ [PD-2012](https://jira.mongodb.org/browse/PD-2012)
> PD-2012: Disclaimer style updates

- website/pages/foundation/refresh-guide.mdx
🎟 _Jira ticket:_ [PD-2133](https://jira.mongodb.org/browse/PD-2133)
> PD-2133: update refresh guideline href

- .changeset/eighty-colts-draw.md
- packages/card/src/Card.tsx
🎟 _Jira ticket:_ [PD-2165](https://jira.mongodb.org/browse/PD-2165)
> PD-2165: Refresh card

- .changeset/early-apricots-divide.md
- packages/menu/src/styles.ts
Removes a flicker when opening a new subMenu
🎟 _Jira ticket:_ [PD-2119](https://jira.mongodb.org/browse/PD-2119)
- Open the Sub Menu example Story
- Click the chevron to expand "Menu item 2"
- Note the active wedge no longer flickers (compare to current live demo)
> PD-2119 menu active state flicker

- .changeset/old-grapes-melt.md
- packages/text-area/src/styles.ts
🎟 _Jira ticket:_ [PD-2178](https://jira.mongodb.org/browse/[PD-2178])
Removed z-index because it didn't seem necessary and it was causing stacking issues.
> PD-2178: Textarea z-index

- website/pages/component/callout/guidelines.mdx
- website/pages/foundation/accessibility.mdx
- website/pages/foundation/forms.mdx
🎟 _Jira ticket:_ [Rename 2 image assets in `Foundations/A11y`](https://jira.mongodb.org/browse/PD-1899)
🎟 _Jira ticket:_ [Fix typo on .design](https://jira.mongodb.org/browse/PD-2042)
🎟 _Jira ticket:_ [Visual bug on Callout design guidelines](https://jira.mongodb.org/browse/PD-2153)
> PD-2153, PD-2042, PD-1899: Fix small content issues in .design

- .changeset/nervous-deers-cheat.md
- packages/copyable/package.json
- packages/copyable/src/Copyable.tsx
🎟 _Jira ticket:_ [PD-2166](https://jira.mongodb.org/browse/[PD-2166])
> PD-2166: Refresh Copyable

- .changeset/three-mayflies-smell.md
- packages/select/src/ListMenu.tsx
- packages/select/src/MenuButton.tsx
- packages/select/src/Option.tsx
- packages/select/src/OptionGroup.tsx
- packages/select/src/Select.spec.tsx
- packages/select/src/Select.story.tsx
- packages/select/src/Select.tsx
- packages/select/src/SelectContext.tsx
- packages/select/src/index.ts
- packages/select/src/styleSets.ts
- packages/select/src/types.ts
Passes through all valid attributes to Select, Option, and OptionGroup
🎟 _Jira ticket:_ [PD-1996](https://jira.mongodb.org/browse/PD-1996)
Add a `data-*` attribute to the Select, Option and/or OptionGroup in any story. Note that it is applied in the DOM
> PD-1996 spread rest on select

- .changeset/nasty-turtles-type.md
- packages/tabs/src/TabTitle.tsx
- packages/tabs/src/Tabs.story.tsx
- packages/tabs/src/Tabs.tsx
> PD-2170: Refresh Tabs

- website/layouts/BaseLayout.tsx
- website/layouts/ComponentLayout.tsx
- website/layouts/FoundationLayout.tsx
Updates Base font size of the website to 13
🎟 _Jira ticket:_ [PD-2085](https://jira.mongodb.org/browse/PD-2085)
> PD-2085 MongoDB.design base font size

- .github/workflows/release.yml
- scripts/slackbot.js
Publishing Storybook/Website sometimes fails. We should run the slackbot before these steps.
Also removes step related to submodules
> Run slackbot immediately after publish

- packages/tabs/README.md
> PD-1966: Tabs documentation for NextJS Links

- packages/select/src/types.ts
> PD-2188: onChange arg doc updated for Select

- .changeset/fifty-radios-tap.md
- packages/menu/src/Menu.tsx
Prevents page scrolling on arrow key press
🎟 _Jira ticket:_ [PD-1775](https://jira.mongodb.org/browse/PD-1775)
> PD-1775 menu arrow key behavior

- .changeset/calm-carrots-return.md
- .changeset/fifty-radios-tap.md
- packages/menu/src/FocusableMenuItem.tsx
- packages/menu/src/Menu.story.tsx
- packages/menu/src/Menu.tsx
- packages/menu/src/MenuContext.tsx
- packages/menu/src/MenuItem.tsx
- packages/menu/src/MenuSeparator.tsx
- packages/menu/src/SubMenu.tsx
- packages/menu/src/styles.ts
- packages/menu/src/types.ts
- website/pages/component/menu/example.tsx
🎟 _Jira ticket:_ [PD-2168](https://jira.mongodb.org/browse/PD-2168), [PD-2194](https://jira.mongodb.org/browse/PD-2194)
> PD-2168, PD-2149: Refresh Menu

- packages/tabs/src/TabTitle.tsx
> fix to add back the ellipsis

- website/pages/_app.tsx
- website/pages/component/button/guidelines.mdx
- website/styles/globals.tsx
> PD-2060, 2047: Website UI Fixes

- .changeset/eight-sheep-tan.md
- packages/table/package.json
> Remove checkbox dependency

- .changeset/calm-carrots-return.md
- .changeset/eighty-colts-draw.md
- .changeset/gorgeous-doors-whisper.md
- packages/card/package.json
- packages/card/src/Card.tsx
- packages/card/tsconfig.json
- packages/inline-definition/package.json
- packages/inline-definition/src/InlineDefinition.tsx
- packages/inline-definition/tsconfig.json
- packages/tabs/src/TabTitle.tsx
- packages/tabs/src/Tabs.tsx
> adding darkmode context

- .changeset/nervous-deers-cheat.md
- packages/copyable/package.json
- packages/copyable/src/Copyable.tsx
- packages/copyable/tsconfig.json
> Update copyable to use basefontsize

- .changeset/weak-meals-remain.md
The latest release didn't properly build `leafygreen-provider`, and dropped `useDarkMode` from exports. Running `yarn build` locally builds it correctly. Hoping a new patch release will resolve this.
🎟 _Jira ticket:_ [PD-2280](https://jira.mongodb.org/browse/PD-2280)
> PD-2280 Fix bad provider build 

- .changeset/silent-windows-sell.md
Similar issue to #1362 
🎟 _Jira ticket:_ [PD-2246](https://jira.mongodb.org/browse/PD-2246)
> PD-2246 export `getTheme` from lib

- .changeset/metal-adults-switch.md
- packages/leafygreen-provider/src/LeafyGreenContext.tsx
Looks like using `PropTypes.instanceOf(HTMLElement)` breaks SSR. Using `PropTypes.elementType` seems to resolve this issue.
🎟 _Jira ticket:_ [PD-2284](https://jira.mongodb.org/browse/PD-2284)
> PD-2284 html element not defined

- .changeset/proud-weeks-check.md
- packages/palette/src/palette.less
- packages/palette/src/palette.ts
🎟 _Jira ticket:_ [PD-2206](https://jira.mongodb.org/browse/PD-2206)
> PD-2206: Update red light1 to #FF6960

- .changeset/late-hotels-hear.md
- packages/menu/src/styles.ts
🎟 _Jira ticket:_ [PD-2253](https://jira.mongodb.org/browse/PD-2253)
> PD-2253: Fix background color appearing when clicking on a disabled menu item

- .changeset/bright-dodos-smile.md
- packages/tabs/src/TabTitle.tsx
> Add missing unit to TabTitle font size

- .changeset/thirty-chicken-itch.md
- packages/menu/package.json
- packages/menu/src/Menu.tsx
While working on PD-1969 I realized that Menu is missing dependencies
🎟 _Jira ticket:_ [PD-2320](https://jira.mongodb.org/browse/PD-2320)
> PD-2320 Missing menu dependencies

- .changeset/honest-lions-wave.md
- packages/combobox/src/Chip.tsx
- packages/combobox/src/Combobox.styles.ts
- packages/combobox/src/Combobox.tsx
- packages/combobox/src/Combobox.types.ts
Some minor style fixes I caught while working on a major change. These should be in their own release before deprecating `expand-x`
🎟 _Jira ticket:_ N/A (pre-work for #1377 )
> Fix combobox styles

- .changeset/stale-wombats-push.md
- packages/button/src/ButtonIcon.tsx
- packages/button/src/styles.ts
🎟 _Jira ticket:_ [PD-2244](https://jira.mongodb.org/browse/PD-2244)
🎟 _Jira ticket:_ [PD-2221](https://jira.mongodb.org/browse/PD-2221)
> PD-2244, PD-2221: Button color updates

- .changeset/rotten-donuts-visit.md
- packages/expandable-card/package.json
- packages/expandable-card/src/ExpandableCard.tsx
- packages/expandable-card/src/styles.ts
- packages/expandable-card/tsconfig.json
- yarn.lock
🎟 _Jira ticket:_ [PD-2335](https://jira.mongodb.org/browse/PD-2335)
> PD-2335: Refresh expandable card

- .changeset/dull-eggs-lie.md
- packages/checkbox/package.json
> Checkbox: add missing dependencies

- packages/lib/src/createUniqueClassName/__snapshots__/createUniqueClassName.spec.ts.snap
- packages/lib/src/createUniqueClassName/createUniqueClassName.spec.ts
- packages/lib/src/createUniqueClassName/index.ts
- packages/lib/src/createUniqueClassName/testComponent.tsx
Instead of using a random UUID, we generate a predictable, incremental digit that is appended to the className 
Eg. `lg-ui-0001`
🎟 _Jira ticket:_ [PD-2179](https://jira.mongodb.org/browse/PD-2179)
> PD-2179 deterministic unique class names

- .changeset/thirty-tips-camp.md
- packages/text-input/src/TextInput.story.tsx
- packages/text-input/src/TextInput.tsx
- packages/text-input/src/style.ts
- stories/forms/SampleForm.stories.tsx
- [] Bugfix (non-breaking change which fixes an issue)
I've created a `Form/Sample Forms` Storybook folder to help keep track of these form elements' visualizations.
> PD-2345: TextInput - padding without label or description

- .changeset/red-dolphins-kneel.md
- packages/button/package.json
- packages/button/src/Button.spec.tsx
- packages/button/src/Button.tsx
- packages/button/src/ButtonContent.tsx
- packages/button/src/types.ts
- yarn.lock
Uses the pattern defined in `Tabs` and adds docs to explain use if `Link` wrapper
🎟 _Jira ticket:_ [PD-2246](https://jira.mongodb.org/browse/PD-2246)
> PD-2246 Support NextJS Link in Button

- .changeset/healthy-dancers-end.md
- packages/checkbox/src/Checkbox.style.ts
🎟 _Jira ticket:_ [PD-2343](https://jira.mongodb.org/browse/PD-2343)
> PD-2343: Checkbox darkMode disabled text color

- .changeset/odd-planes-explode.md
- packages/menu/src/Menu.tsx
🎟 _Jira ticket:_ [PD-2337](https://jira.mongodb.org/browse/PD-2337)
> PD-2337: Menu - unique key warning fix

- package.json
- packages/button/src/types.ts
- scripts/parse-tsdocs.ts
- yarn.lock
> Deprecate expandable box type

- .changeset/rude-tables-pay.md
- packages/code/package.json
- yarn.lock
> Code: Highlight.js version lock

- packages/combobox/src/Combobox.tsx
🎟 _Jira ticket:_ [PD-2420](https://jira.mongodb.org/browse/PD-2420)
> PD-2420: Combobox margin-top

- package.json
- scripts/slackbot.ts
Adds documentation to Slackbot to make manually running easier.
> Slackbot documentation & TS

- .changeset/eight-colts-worry.md
- packages/table/package.json
- packages/table/src/Row.tsx
- packages/table/src/useSSR.ts
- rollup.config.js
- scripts/jestSSRSetup.js
- yarn.lock
Removes external `use-ssr` package
🎟 _Jira ticket:_ [PD-2448 ](https://jira.mongodb.org/browse/PD-2448 )
> PD-2448 Remove use-ssr package

- .github/workflows/release.yml
- packages/testing-lib/CHANGELOG.md
- packages/testing-lib/package.json
- scripts/slackbot.ts
Fixes issues with deploys
- Rolls back testing-lib version
- Removes `Dispatch` step (but retains test dispatch job)
- Updates Slackbot
> Fix deploys

- .github/workflows/nodejs.yml
- package.json
- scripts/build.ts
- scripts/test.ts
- scripts/utils/getAllPackageNames.ts
- scripts/utils/getGitDiff.ts
- scripts/utils/getPackageDependencies.ts
> Adds custom Test script

- packages/table/CHANGELOG.md
> Update table 5.0.3 changelog

- package.json
- scripts/unlink.sh
> Creates unlink script

- website/package.json
- yarn.lock
> Upgrades eslint version in website

- .changeset/itchy-jobs-appear.md
- .changeset/swift-buses-know.md
- packages/combobox/package.json
- packages/combobox/src/Combobox.spec.tsx
- packages/combobox/src/Combobox.tsx
- packages/combobox/src/ComboboxTestUtils.tsx
- packages/leafygreen-provider/src/UsingKeyboardContext.spec.tsx
Ensures the combobox does not open on initial focus. The menu should only open when clicked, or a relevant key is pressed when the input is focused
🎟 _Jira ticket:_ [PD-2321](https://jira.mongodb.org/browse/PD-2321)
> PD-2321 Combobox initial focus

- .changeset/itchy-jobs-appear.md
- .changeset/swift-buses-know.md
- .changeset/ten-keys-share.md
- package.json
- packages/combobox/package.json
- packages/combobox/src/Combobox.spec.tsx
- packages/combobox/src/Combobox.story.tsx
- packages/combobox/src/Combobox.tsx
- packages/combobox/src/Combobox.types.ts
- packages/combobox/src/ComboboxContext.tsx
- packages/combobox/src/ComboboxGroup.tsx
- packages/combobox/src/ComboboxOption.tsx
- packages/combobox/src/ComboboxTestUtils.tsx
- packages/leafygreen-provider/src/UsingKeyboardContext.spec.tsx
- scripts/proptypes.ts
Adds PropTypes to Combobox.
Also, adds a quick script for generating propTypes from tsdoc
🎟 _Jira ticket:_ [PD-2451](https://jira.mongodb.org/browse/PD-2451)
> PD-2451 Add prop types to Combobox

- .github/workflows/release.yml
> Repository Dispatch event update

- .changeset/tricky-beans-deliver.md
- packages/code/src/LanguageSwitcher.tsx
> Pd 2427 code placeholder color

- .changeset/happy-hounds-hope.md
- babel.config.js
- package.json
- rollup.config.js
- yarn.lock
Our packages will not build if `@leafygreen/emotion@4.0.2` or greater is installed. This is because this package listed `@emotion/react` as a dependency, which was also an implicit dependency of all other packages.
This packages updates the rollup & babel configs to remove this implicit dependency.
> Removes `@emotion/react` is not included in builds

- .changeset/shaggy-waves-whisper.md
- packages/badge/package.json
- packages/banner/package.json
- packages/expandable-card/package.json
- packages/select/package.json
- packages/side-nav/package.json
- packages/toast/package.json
Noticed that some components were using exact versions.
> Dependency range fix

- .changeset/breezy-trains-relax.md
- packages/button/src/ButtonIcon.tsx
🎟 _Jira ticket:_ [LG-2528](https://jira.mongodb.org/browse/LG-2528)
> LG-2528: ButtonIcon color when Button is disabled

- .changeset/pretty-comics-act.md
- packages/toggle/package.json
- packages/toggle/src/Toggle.story.tsx
- packages/toggle/src/Toggle.tsx
- packages/toggle/src/index.ts
- packages/toggle/src/styles.ts
- packages/toggle/src/types.ts
- packages/toggle/tsconfig.json
🎟 _Jira ticket:_ [LG-2501](https://jira.mongodb.org/browse/LG-2501)
> LG-2501: Refresh toggle

- .changeset/nice-bees-hope.md
- packages/radio-box-group/package.json
- packages/radio-box-group/src/RadioBox.styles.ts
- packages/radio-box-group/src/RadioBox.tsx
- packages/radio-box-group/src/RadioBoxGroup.spec.tsx
- packages/radio-box-group/src/RadioBoxGroup.story.tsx
- packages/radio-box-group/src/RadioBoxGroup.styles.ts
- packages/radio-box-group/src/RadioBoxGroup.tsx
- packages/radio-box-group/src/Size.ts
- packages/radio-box-group/src/context.ts
- packages/radio-box-group/src/index.ts
- packages/radio-box-group/src/types.ts
- packages/radio-box-group/tsconfig.json
- website/pages/component/radio-box-group/example.tsx
🎟 _Jira ticket:_ [LG-2505](https://jira.mongodb.org/browse/LG-2505)
> LG-2505: Refresh radio box group

- website/.babelrc
- website/package.json
- yarn.lock
> Adds @emotion/babel-preset-css-prop

- .changeset/olive-timers-film.md
- packages/segmented-control/src/SegmentedControl.spec.tsx
- packages/segmented-control/src/SegmentedControl.story.tsx
- packages/segmented-control/src/SegmentedControl.styles.ts
- packages/segmented-control/src/SegmentedControl.tsx
- packages/segmented-control/src/SegmentedControlContext.tsx
- packages/segmented-control/src/SegmentedControlOption.styles.ts
- packages/segmented-control/src/SegmentedControlOption.tsx
- packages/segmented-control/src/index.ts
- packages/segmented-control/src/types.ts
🎟 _Jira ticket:_ [LG-2504](https://jira.mongodb.org/browse/LG-2504)
🎟 _Jira ticket:_ [LG-2487](https://jira.mongodb.org/browse/LG-2487)
🎟 _Jira ticket:_ [LG-2557](https://jira.mongodb.org/browse/LG-2557)
> LG-2504, LG-2487, LG-2557: Refresh segmented control

- .changeset/flat-carrots-deny.md
- packages/logo/src/AtlasNavGraphic.tsx
- packages/logo/src/Logo.spec.tsx
- packages/logo/src/Logo.story.tsx
- packages/logo/src/Logo.tsx
- packages/logo/src/index.ts
Renames `AtlasLogo` (incorrect) to `AtlasNavGraphic`
🎟 _Jira ticket:_ [LG-2546](https://jira.mongodb.org/browse/LG-2546)
Depended on by: https://github.com/10gen/leafygreen-ui-private/pull/50
> LG-2546 Rename `AtlasNavGraphic`

- .changeset/funny-grapes-itch.md
- packages/table/package.json
- packages/table/src/Cell.tsx
- packages/table/src/FontSizeContext.tsx
- packages/table/src/NestedRow.tsx
- packages/table/src/Row.tsx
- packages/table/src/Table.tsx
- packages/table/src/TableHeader.tsx
- packages/table/src/styles.tsx
- packages/table/tsconfig.json
‼️***Note:*** **There are currently a few bugs which I will not address since Sean will be working on a revamped `Table` in the upcoming weeks.**
🎟 _Jira ticket:_ [LG-2555](https://jira.mongodb.org/browse/LG-2555)
> LG-2555: Refresh table

- .changeset/poor-ladybugs-wink.md
- package.json
- packages/button/package.json
- packages/card/package.json
- packages/code/package.json
- packages/combobox/package.json
- packages/copyable/package.json
- packages/form-footer/package.json
- packages/modal/package.json
- packages/segmented-control/package.json
- packages/side-nav/package.json
- packages/table/package.json
- packages/tooltip/package.json
- yarn.lock
Adds `polished` as an explicit dependency to:
'@leafygreen-ui/button': patch
'@leafygreen-ui/card': patch
'@leafygreen-ui/code': patch
'@leafygreen-ui/combobox': patch
'@leafygreen-ui/copyable': patch
'@leafygreen-ui/form-footer': patch
'@leafygreen-ui/modal': patch
'@leafygreen-ui/segmented-control': patch
'@leafygreen-ui/side-nav': patch
'@leafygreen-ui/table': patch
'@leafygreen-ui/tooltip': patch
> Adds polished as component dependencies

- .changeset/curvy-fans-pretend.md
- packages/icon-button/src/IconButton.tsx
- packages/icon-button/src/types.ts
Allows IconButton component to accept tabIndex prop
🎟 _Jira ticket:_ [LG-1670](https://jira.mongodb.org/browse/LG-1670)
> Allows IconButton component to accept tabIndex prop

- .changeset/thick-glasses-report.md
- packages/code/src/Syntax.tsx
🎟 _Jira ticket:_ [LG-2698](https://jira.mongodb.org/browse/LG-2698)
> LG-2698: Code - fix for stretched numbered cells

- .changeset/shiny-tigers-kneel.md
- packages/text-input/src/style.ts
🎟 _Jira ticket:_ [LG-2713](https://jira.mongodb.org/browse/LG-2713)
> LG-2713: Fixes broken animation on TextInput component

- packages/leafygreen-provider/README.md
🎟 _Jira ticket:_ [LG-2739](https://jira.mongodb.org/browse/LG-2739)
> LG-2739: Add documentation on DarkModeProvider

- .changeset/cuddly-points-lay.md
- packages/code/src/Code.tsx
- packages/code/src/LanguageSwitcher.tsx
🎟 _Jira ticket:_ [LG-2703](https://jira.mongodb.org/browse/LG-2703)
The reason the language selector would not open initially on load when clicked was because of `useUsingKeyboardContext`.
Since the default for the keyboard provider was `true`, whenever a `keydown` would occur the state would update and that would cause the `code` component to re-render. Because of the re-render the dropdown would not open. I decided to remove the hook and switch to `focus-visible`. It's essentially the same exact thing without any additional re-renders.
6. Missing core …
> LG-2703: language select on click

- .changeset/weak-lemons-count.md
- packages/side-nav/src/SideNav.story.tsx
Updates SideNav story. Fixes [No. 8](https://docs.google.com/document/d/1zds271-DF_vmsF4-yy7jjV20jvpEtpTsSPIxf5w7xo4/edit)
> LG-2728 update sidenav story

- website/pages/component/icon/example.tsx
- website/pages/component/palette/example.tsx
> Remove InteractionRing component imports from website

- .changeset/odd-mice-knock.md
- .changeset/soft-bulldogs-warn.md
- packages/code/src/types.ts
- packages/expandable-card/src/ExpandableCard.story.tsx
- Adds TSDoc to `Code`
- Sets a default story for `ExpandableCard`
Resolves [No. 17 & 18](https://docs.google.com/document/d/1zds271-DF_vmsF4-yy7jjV20jvpEtpTsSPIxf5w7xo4/edit)
> LG-2738 code expandablecard docs

- .changeset/fair-years-train.md
- packages/hooks/src/index.ts
- packages/hooks/src/useBackdropClick.ts
Isolates `useBackropClick` hook. 
Used in `SearchInput` and `Tooltip`
> Hook: useBackdropClick

- .changeset/pretty-mangos-shout.md
- packages/popover/package.json
- packages/popover/src/Popover.story.tsx
Updates Popover story to use LG Button
> Popover story

- .changeset/cuddly-trainers-behave.md
- packages/guide-cue/src/index.ts
🎟 _Jira ticket:_ [LG-2795](https://jira.mongodb.org/browse/LG-2795)
> LG-2795: remove TooltipContent export from index.ts

- .changeset/six-melons-play.md
- packages/button/src/Button/Button.styles.ts
- packages/button/src/Button/Button.tsx
- packages/icon-button/src/IconButton.tsx
- packages/icon-button/src/styles.tsx
- packages/menu/src/MenuItem.tsx
- packages/menu/src/SubMenu.tsx
- packages/menu/src/styles.ts
- packages/radio-box-group/src/RadioBox.styles.ts
- packages/radio-box-group/src/RadioBox.tsx
- packages/select/src/MenuButton.tsx
- packages/select/src/Option.tsx
- packages/tabs/src/TabTitle.tsx
- packages/typography/src/InlineCode/InlineCode.styles.ts
- packages/typography/src/InlineCode/InlineCode.tsx
Part one of a two part PR. This PR removes useUsingKeyboardContext from Button,  IconButton, RadioBoxGroup, Tabs, and InlineCode. Tested all components in Storybook!
🎟 _Jira ticket:_ [LG-2786](https://jira.mongodb.org/browse/LG-2786)
🎟 _Jira ticket:_ [LG-2788](https://jira.mongodb.org/browse/LG-2788)
🎟 _Jira ticket:_ [LG-2790](https://jira.mongodb.org/browse/LG-2790)
🎟 _Jira ticket:_ [LG-2791](https://jira.mongodb.org/browse/LG-2791)
🎟 _Jira ticket:_ [LG-2792](https://jira.mongodb.org/browse/LG-2792)
🎟 _Jira ticket:_ [LG-2794](https://jira.mongodb.org/browse/LG-2794)
🎟 _Jira ticket:_ [LG-2813](https://jira.mongodb.org/browse/LG-2813) …
> Removes useUsingKeyboardContext in favor of focus-visible (Pt. 1)

- .changeset/dry-ways-kiss.md
- .storybook/manager-head.html
- .storybook/preview-head.html
- packages/tokens/src/fontFamilies.ts
- website/pages/component/tokens/example.tsx
- website/styles/globals.tsx
🎟 _Jira ticket:_ [LG-2766](https://jira.mongodb.org/browse/LG-2766)
> LG-2766: remove Akzidenz

- .changeset/odd-lies-sing.md
- packages/checkbox/src/Check/index.tsx
- packages/checkbox/src/Checkbox.style.ts
- packages/checkbox/src/Checkbox.tsx
- Rms useUsingKeyboard from Checkbox component in favor of `&:focus-visible`
🎟 _Jira ticket:_ [LG-2787](https://jira.mongodb.org/browse/LG-2787)
> LG-2787: Rms useUsingKeyboard from Checkbox component

- .changeset/lucky-mirrors-act.md
- packages/text-area/package.json
- packages/text-area/src/TextArea.story.tsx
Removes `lgProviderBaseFontSize` prop from Basic story
> Updates basic TextArea story

- .changeset/strange-bags-protect.md
- package.json
- packages/a11y/package.json
- packages/badge/package.json
- packages/button/package.json
- packages/callout/package.json
- packages/card/package.json
- packages/checkbox/package.json
- packages/code/package.json
- packages/copyable/package.json
- packages/expandable-card/package.json
- packages/guide-cue/package.json
- packages/icon-button/package.json
- packages/leafygreen-provider/package.json
- packages/logo/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/pagination/package.json
- packages/radio-group/package.json
- packages/search-input/package.json
- packages/segmented-control/package.json
- packages/select/package.json
- packages/side-nav/package.json
- packages/stepper/package.json
- packages/table/package.json
- packages/text-input/package.json
- packages/toggle/package.json
- packages/tooltip/package.json
- packages/typography/package.json
- yarn.lock
> Updates lib across components

- .changeset/khaki-beans-wait.md
- packages/text-area/src/TextArea/TextArea.tsx
🎟 _Jira ticket:_ [LG-2855](https://jira.mongodb.org/browse/LG-2855)
> LG-2855: TextArea typography elements respect baseFontSize prop

- .changeset/wild-rules-explode.md
- packages/typography/src/H1/H1.tsx
- packages/typography/src/H2/H2.tsx
Erroneously spreading "as" onto DOM element in h1 and h2 components
> Fixes bug in h1 and h2 components

- .changeset/breezy-dingos-deliver.md
- .changeset/fluffy-jobs-tickle.md
- packages/lib/src/storybook/StoryMeta.ts
- packages/pagination/src/Pagination.story.tsx
🎟 _Jira ticket:_ [LG-2919](https://jira.mongodb.org/browse/LG-2919)
> LG-2919 fix pagination live example

- .github/pull_request_template.md
Removes infrequently used sections in the PR template in hopes of decluttering PR descriptions
N/A
> Removes sections from PR template

- .changeset/young-tigers-sparkle.md
- packages/password-input/src/PasswordInput/PasswordInput.spec.tsx
- packages/password-input/src/PasswordToggle/PasswordToggle.tsx
Prevents forms form being submitted when clicked
🎟 _Jira ticket:_ [LG-2929](https://jira.mongodb.org/browse/LG-2929)
> LG-2929 PasswordInput toggle button type

- .changeset/neat-geese-nail.md
- packages/pagination/src/Pagination/Pagination.styles.ts
- packages/pagination/src/Pagination/Pagination.tsx
🎟 _Jira ticket:_ [LG-3028](https://jira.mongodb.org/browse/LG-3028)
> LG-3028: Pagination select width

- .changeset/dry-rockets-retire.md
- DEVELOPER.md
- packages/table/CHANGELOG.md
- packages/table/src/Table/Table.tsx
- packages/table/src/TableV10/Row.tsx
- packages/table/src/TableV10/Table.tsx
- packages/table/src/TableV10/TableHeader.tsx
- packages/table/src/V11Adapter/V11Adapter.spec.tsx
- scripts/utils/tsDocParser.ts
> LG-3075: Fix Code Docs for Table

- .changeset/large-trainers-melt.md
- packages/palette/src/Palette.story.tsx
🎟 _Jira ticket:_ [LG-2905](https://jira.mongodb.org/browse/LG-2905)
Previous:
New:
> LG-2905: Palette story styles

- .changeset/beige-meals-perform.md
- packages/confirmation-modal/src/ConfirmationModal/types.ts
- packages/marketing-modal/src/MarketingModal/types.ts
Rm size prop from ConfirmationModal and MarketingModal components
🎟 _Jira ticket:_ [LG-3095](https://jira.mongodb.org/browse/LG-3095)
> LG-3095: Rm size prop from ConfirmationModal and MarketingModal components

- packages/menu/src/SubMenu/SubMenu.spec.tsx
(I don't know how we didn't catch this sooner?)
> Fixes flakey Menu test

- packages/a11y/src/A11y.spec.tsx
- packages/button/src/Button/Button.spec.tsx
- packages/button/src/Button/index.tsx
- packages/icon/src/Icon.spec.tsx
- packages/pagination/src/Pagination/Pagination.spec.tsx
- packages/segmented-control/src/SegmentedControl/SegmentedControl.spec.tsx
- packages/text-input/src/TextInput/TextInput.spec.tsx
- packages/tooltip/src/Tooltip.spec.tsx
> Cleans up console warnings and errors across test suties

- .changeset/breezy-bees-juggle.md
- packages/toggle/src/Toggle/styles.ts
🎟 _Jira ticket:_ [LG-3157](https://jira.mongodb.org/browse/LG-3157)
> LG-3157: Changes Toggle XSmall width

- .changeset/config.json
- packages/testing-lib/package.json
- Rolls back `testing-lib` package.json version
- Adds `testing-lib` to changeset ignore
> Changeset config

- .changeset/polite-eyes-hammer.md
- packages/toggle/src/Toggle/styles.ts
Before:
After:
🎟 _Jira ticket:_ [LG-3226](https://jira.mongodb.org/browse/LG-3226)
> LG-3226: Fixes Toggle components xsmall, active

- .changeset/sweet-cameras-fly.md
- packages/combobox/src/Chip/Chip.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/combobox/src/ComboboxContext/ComboboxContext.tsx
Before:
After:
🎟 _Jira ticket:_ [Lg-3197](https://jira.mongodb.org/browse/Lg-3197)
> Lg-3197: Sends popoverZindex to Combobox Chips

- packages/loading-indicator/package.json
- packages/loading-indicator/src/BlobLoader/BlobLoader.stories.tsx
- packages/loading-indicator/src/LoadingIndicator.story.tsx
- packages/loading-indicator/src/Spinner/Spinner.stories.tsx
> Update story file format in loading-indicator

- .changeset/pink-radios-grab.md
- packages/typography/src/InlineCode/InlineCode.types.ts
- packages/typography/src/Link/Link.types.ts
🎟 _Jira ticket:_ [LG-3193](https://jira.mongodb.org/browse/LG-3193)
> LinkProps fix

- .changeset/mean-wombats-retire.md
- packages/menu/src/Menu.spec.tsx
- packages/menu/src/Menu/Menu.tsx
🎟 _Jira ticket:_ [LG-3193](https://jira.mongodb.org/browse/LG-3193)
> LG-3193: Clicking on a MenuItem closes the Menu

- packages/code/package.json
- packages/combobox/package.json
- packages/confirmation-modal/package.json
- packages/copyable/package.json
- packages/empty-state/package.json
- packages/form-footer/package.json
- packages/guide-cue/package.json
- packages/marketing-modal/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/number-input/package.json
- packages/popover/package.json
- packages/segmented-control/package.json
- packages/select/package.json
- packages/split-button/package.json
- packages/tabs/package.json
- packages/toast/package.json
- packages/tooltip/package.json
> Rollback Button version 20.1.0 in packages

- .changeset/swift-emus-call.md
- packages/code/package.json
- packages/combobox/package.json
- packages/confirmation-modal/package.json
- packages/copyable/package.json
- packages/empty-state/package.json
- packages/form-footer/package.json
- packages/guide-cue/package.json
- packages/marketing-modal/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/number-input/package.json
- packages/popover/package.json
- packages/segmented-control/package.json
- packages/select/package.json
- packages/split-button/package.json
- packages/tabs/package.json
- packages/toast/package.json
- packages/tooltip/package.json
> Bump Button dependencies to 20.1.1

- .changeset/config.json
- .changeset/sixty-colts-travel.md
- packages/testing-lib/package.json
🎟 _Jira ticket:_ [LG-3302](https://jira.mongodb.org/browse/LG-3302)
> LG-3302: Publish @leafygreen-ui/testing-lib

- packages/combobox/src/Combobox/Combobox.spec.tsx
> Adds Combobox tests

- .github/workflows/release.yml
- package.json
> Fixes release script

- packages/form-footer/src/FormFooter.tsx
- yarn.lock
> fix formfooter TS error

- packages/table/src/TableV10/Cell.tsx
- packages/table/src/TableV10/Row.tsx
- packages/table/src/TableV10/Table.tsx
> fix table ts

- packages/side-nav/src/SideNavGroup/SideNavGroup.tsx
- packages/side-nav/src/SideNavGroup/SideNavGroup.types.ts
- packages/side-nav/src/SideNavItem/SideNavItem.tsx
- packages/side-nav/src/SideNavItem/SideNavItem.types.ts
> revert changes to isComponentGlyph inside sideNav

- .changeset/strange-mirrors-destroy.md
- packages/code/src/renderingPlugin/renderingPlugin.tsx
> LG-3249: Updates code highlight color

- .changeset/cyan-cycles-count.md
- packages/stepper/src/Stepper.story.tsx
🎟 _Jira ticket:_ [LG-3291](https://jira.mongodb.org/browse/LG-3291)
> LG-3291: Adds `darkMode` to Stepper storybook

- .changeset/afraid-numbers-double.md
- packages/stepper/src/Stepper.tsx
🎟 _Jira ticket:_ [LG-3291](https://jira.mongodb.org/browse/LG-3291)
> LG-3291: Stepper component reads darkMode value from Provider

- .github/workflows/pr.yml
- .github/workflows/release.yml
Removes obsolete tasks & breaks up CI workflow into multiple jobs
> Updates Release CI

- .changeset/ten-papayas-compare.md
- tools/storybook/main.ts
- tools/storybook/package.json
- yarn.lock
Updates storybook `main` config.
Prevents Storybook from building nested `.story` files inside a package's `node_modules`
> Updates stories main config

- .github/workflows/release.yml
Ensures the repo is checked out before the slackbot notification runs
> Checkout repo before Slackbot

- packages/icon/src/generated/List.tsx
- packages/icon/src/generated/Return.tsx
- packages/icon/src/generated/Sparkle.tsx
- Runs `yarn build`
- Fixes incorrect icon builds
> Rebuild icons

- .github/workflows/release.yml
- tools/storybook/main.ts
Installs packages before running `lg slackbot`
No changeset needed
> Fixes slackbot CI

- .changeset/selfish-buses-crash.md
- tools/build/config/rollup.config.mjs
- tools/build/package.json
- yarn.lock
Adds missing dependency `glob` to build package
> Missing build dependency

- .changeset/lucky-pugs-obey.md
Adds missing changeset from #1875
> PR-1875 missing changeset

- .changeset/seven-tomatoes-sit.md
- packages/expandable-card/src/ExpandableCard/ExpandableCard.styles.ts
🎟 _Jira ticket:_ [LG-3502](https://jira.mongodb.org/browse/LG-3502)
> LG-3502: ExpandableCard in dark mode

- .changeset/red-pens-knock.md
- .changeset/sharp-timers-lick.md
- packages/code/src/CustomSelectMenuButton/CustomSelectMenuButton.tsx
- packages/code/src/CustomSelectMenuButton/index.ts
- packages/code/src/LanguageSwitcher/LanguageSwitcher.styles.ts
- packages/code/src/LanguageSwitcher/LanguageSwitcher.tsx
- packages/number-input/src/CustomSelectMenuButton/CustomSelectMenuButton.tsx
- packages/number-input/src/CustomSelectMenuButton/index.ts
- packages/number-input/src/UnitSelect/UnitSelect.tsx
- packages/number-input/src/UnitSelectButton/UnitSelectButton.tsx
- packages/number-input/src/UnitSelectButton/UnitSelectButton.types.ts
- packages/select/src/MenuButton.tsx
- packages/select/src/types.ts
- yarn.lock
> React18 select internal props

- package.json
> Fix create script

- packages/typography/README.md
> Fixes Typography Table

- .changeset/polite-beds-hear.md
- packages/logo/src/index.ts
- packages/logo/src/utils.ts
🎟 _Jira ticket:_ [LG-3510](https://jira.mongodb.org/browse/LG-3510)
> LG-3510: export `SupportedColors` from index

- packages/button/src/Button/Button.spec.tsx
Adds `legacyBehavior` to test. Creates new test for new behavior
No changeset neded
> Adds NextLink legacyBehavior test

- .github/workflows/react17.yml
- tools/cli/src/index.ts
- tools/test/config/react17/jest.config.js
- tools/test/config/react17/mocks/svgTransformer.js
- tools/test/config/react17/setup.js
- tools/test/src/index.ts
- Adds React17 jest config to `@lg-tools/test`
- Adds `--react17` flag to `lg test` command
- Creates React 17 CI workflow to run tests in that environment
🎟 _Jira ticket:_ [LG-3540](https://jira.mongodb.org/browse/LG-3540)
> React 17 CI tests [LG-3540]

- .changeset/weak-carrots-divide.md
- packages/typography/src/Error/Error.styles.ts
- packages/typography/src/Error/Error.tsx
Updates `Error` component to read from TypographyProvider to set font size
> Error message font size

- packages/tooltip/src/Tooltip.story.tsx
Speed up Chromatic runs on Safari for generated Tooltip stories
> Break-up generated Tooltip stories

- .changeset/light-pots-doubt.md
- packages/icon-button/src/styles.tsx
🎟 _Jira ticket:_ [LG-3558](https://jira.mongodb.org/browse/LG-3558)
> LG-3558: Updates icon button color

- .changeset/lemon-ducks-smell.md
- .changeset/light-pots-doubt.md
- packages/icon-button/src/styles.tsx
- packages/table/README.md
- packages/table/src/Table.story.tsx
- packages/table/src/useLeafyGreenTable/useLeafyGreenTable.tsx
🎟 _Jira ticket:_ [LG-3361](https://jira.mongodb.org/browse/LG-3361)
> LG-3361: Allow Table to be selectable without header checkbox

- .changeset/long-peas-exercise.md
- .changeset/tasty-ways-sit.md
- packages/combobox/src/Chip/Chip.tsx
- packages/combobox/src/Combobox/Combobox.spec.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/combobox/src/utils/flattenChildren.tsx
- packages/lib/src/index.ts
- packages/menu/src/Menu/Menu.tsx
- packages/search-input/src/SearchInput/SearchInput.tsx
- packages/select/src/Select.spec.tsx
- packages/select/src/Select.tsx
- packages/side-nav/src/SideNav/SideNav.tsx
- packages/split-button/src/Menu/Menu.tsx
- packages/tabs/src/Tabs.spec.tsx
- packages/tabs/src/Tabs/Tabs.tsx
- packages/toast/src/ToastContainer/ToastContainer.tsx
> Changes to check for an event's key not keyCode

- .changeset/tasty-oranges-develop.md
- packages/table/README.md
- packages/table/src/V11Adapter/V11Adapter.tsx
- packages/table/src/V11Adapter/V11Adapter.types.ts
- packages/table/src/V11Adapter/processColumns.tsx
- packages/table/src/V11Adapter/processData.tsx
> LG-3538: Table Adapter TS Fixes

- .changeset/sharp-doors-cover.md
- packages/radio-group/src/Radio/Radio.styles.ts
- packages/radio-group/src/Radio/Radio.tsx
- packages/radio-group/src/RadioGroup.story.tsx
🎟 _Jira ticket:_ [LG-3570](https://jira.mongodb.org/browse/LG-3570)
> LG-3570: radioGroup disabled cursor

- .changeset/witty-crabs-begin.md
- packages/popover/src/Popover.spec.tsx
- packages/popover/src/Popover.tsx
Adds forwardRef to Popover
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3601
> Popover ref [LG-3601]

- package.json
- yarn.lock
> LG-3626: add types/react resolution

- .github/workflows/release.yml
> `node-gyp` on release CI

- .changeset/strange-hounds-press.md
- packages/badge/src/Badge/styles.ts
🎟 _Jira ticket:_ [LG-3640](https://jira.mongodb.org/browse/LG-3640)
> LG-3640: Badge dark mode adjustment

- .changeset/spicy-lies-design.md
- packages/typography/src/H1/H1.styles.ts
- packages/typography/src/H2/H2.styles.ts
> Typography updates in dark mode

- .changeset/lovely-cherries-beam.md
- packages/side-nav/src/CollapsedSideNavItem/CollapedSideNavItem.styles.ts
- packages/side-nav/src/SideNavGroupCollapsed/SideNavGroupCollapsed.styles.ts
- packages/side-nav/src/SideNavGroupHeader/SideNavGroupHeader.styles.ts
🎟 _Jira ticket:_ [LG-3639](https://jira.mongodb.org/browse/LG-3639)
> LG-3639: SideNav dark mode updates 

- .changeset/stupid-mayflies-push.md
- packages/tabs/src/TabTitle/TabTitle.styles.ts
🎟 _Jira ticket:_ [LG-3641](https://jira.mongodb.org/browse/LG-3641)
> LG-3641: Tab dark mode updates

- packages/tabs/src/Tabs.story.tsx
> Add tab test

- .github/workflows/pr.yml
- .github/workflows/react17.yml
- .github/workflows/release.yml
- .github/workflows/sizeDiff.yml
> Update to actions/checkout@v3

- .changeset/lovely-cherries-beam.md
- .changeset/spicy-lies-design.md
- .changeset/strange-hounds-press.md
- .changeset/stupid-mayflies-push.md
- packages/badge/src/Badge/styles.ts
- packages/side-nav/src/CollapsedSideNavItem/CollapedSideNavItem.styles.ts
- packages/side-nav/src/SideNavGroupCollapsed/SideNavGroupCollapsed.styles.ts
- packages/side-nav/src/SideNavGroupHeader/SideNavGroupHeader.styles.ts
- packages/tabs/src/TabTitle/TabTitle.styles.ts
- packages/tabs/src/Tabs.story.tsx
- packages/typography/src/H1/H1.styles.ts
- packages/typography/src/H2/H2.styles.ts
> Dark Mode Adjustments Integration Branch - Green adjustments

- .changeset/perfect-bears-study.md
- packages/button/src/types.ts
Assigns Button Size as const to improve intellisense
https://mongodb.slack.com/archives/CFFA5BS79/p1696528129126939
> Update button size type

- .changeset/shy-mails-prove.md
- packages/icon-button/src/styles.tsx
> Fixes IconButton color in light mode

- packages/date-picker/src/Calendar/CalendarGrid/CalendarGrid.styles.ts
- packages/date-picker/src/Calendar/CalendarGrid/CalendarGrid.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.styles.ts
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/index.tsx
[Update Date Picker Month and Year Select width](https://jira.mongodb.org/browse/LG-3675)
[Date Picker menu spacing](https://jira.mongodb.org/browse/LG-3676)
> LG-3675, LG-3676: Date Picker select width and menu width

- packages/date-picker/src/DateInput/DateInputBox/DateInputBox.styles.ts
- packages/date-picker/src/DateInput/DateInputBox/DateInputBox.tsx
> LG-3680: date picker disabled styles

- packages/empty-state/src/FeaturesEmptyState/FeaturesEmptyState.spec.tsx
- packages/empty-state/src/FeaturesEmptyState/FeaturesEmptyState.story.tsx
- packages/empty-state/src/example-graphics/index.tsx
- packages/empty-state/src/example-graphics/svg.d.ts
- packages/empty-state/tsconfig.json
- typings/images.d.ts
> cleanup EmptyState tests

- packages/date-picker/src/DateInput/DateFormField/DateFormField.tsx
> LG-3686: date picker add size prop to FormField

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> LG-3696: dp menu toggle

- .changeset/quick-teachers-dream.md
- packages/text-input/package.json
- packages/text-input/src/TextInput/TextInput.tsx
- packages/text-input/tsconfig.json
> Updates to TextInput

- .changeset/little-cherries-dream.md
- packages/table/README.md
🎟 _Jira ticket:_ [LG-3650](https://jira.mongodb.org/browse/LG-3650)
> LG-3650: Update Table README with TanStack reference

- .changeset/afraid-squids-hide.md
- package.json
- tools/build/package.json
- tools/lint/package.json
- yarn.lock
> Resolving @babel/traverse issues

- .changeset/cyan-geese-judge.md
- packages/typography/README.md
🎟 _Jira ticket:_ [[LG-2975](https://jira.mongodb.org/browse/[name-of-ticket])](https://jira.mongodb.org/browse/LG-2975)
> Label documentation

- .github/workflows/release.yml
- package.json
- yarn.lock
🎟 _Jira ticket:_ [LG-3780](https://jira.mongodb.org/browse/LG-3780)
🎟 _Jira ticket:_ [LG-3610](https://jira.mongodb.org/browse/LG-3610)
🎟 _Jira ticket:_ [LG-2907](https://jira.mongodb.org/browse/LG-2907)
> LG-3780, 3610, 2907: Github Actions updates / fixes

- .github/workflows/release.yml
> Dispatch payload as JSON

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.tsx
- packages/date-picker/src/shared/components/Calendar/CalendarCell/CalendarCell.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
> Date Picker [LG-3792] adds tests

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerComponent/DatePickerComponent.tsx
- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.tsx
- packages/date-picker/src/DatePicker/SingleDateContext/SingleDateContext.tsx
- packages/date-picker/src/DatePicker/SingleDateContext/SingleDateContext.types.ts
[LG-3759](https://jira.mongodb.org/browse/LG-3759) - Focus should remain on segment when clicked
> DatePicker: [LG-3759] Focus correct element when menu opens

- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.spec.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
- packages/date-picker/src/shared/utils/getSegmentMaxLength/getSegmentMaxLength.spec.ts
- packages/date-picker/src/shared/utils/getSegmentMaxLength/index.ts
- packages/date-picker/src/shared/utils/index.ts
🎟 _Jira ticket:_ [LG-3770](https://jira.mongodb.org/browse/[LG-3770])
> Date Picker[LG-3770] add maxLength

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.tsx
- packages/date-picker/src/shared/utils/addDaysUTC/addDaysUTC.spec.ts
- packages/date-picker/src/shared/utils/addDaysUTC/index.ts
- packages/date-picker/src/shared/utils/index.ts
> Date Picker [LG-3773]: Daylight time cell focus

- packages/date-picker/src/DatePicker/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.tsx
> Date Picker [LG-3767] Modal bugs

- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
> Date Picker [LG -3806, LG-3808] Consume LeafyGreenProvider

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerComponent/DatePickerComponent.tsx
🎟 _Jira ticket:_ [LG-3804](https://jira.mongodb.org/browse/LG-3804)
> Date Picker [LG-3804] - No scrolling on up/down arrow

- packages/date-picker/src/DatePicker/SingleDateContext/SingleDateContext.tsx
- packages/date-picker/src/shared/components/DateInput/DateFormField/DateFormField.tsx
🎟 _Jira ticket:_ [LG-3837](https://jira.mongodb.org/browse/LG-3837)
> Date Picker [LG-3837] Calendar iconButton focus

- packages/date-picker/src/DatePicker/DatePicker.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
- packages/date-picker/src/shared/components/DatePickerContext/DatePickerContext.spec.tsx
- packages/date-picker/src/shared/components/DatePickerContext/DatePickerContext.tsx
- packages/date-picker/src/shared/components/DatePickerContext/DatePickerContext.utils.ts
- packages/date-picker/src/shared/types.ts
- packages/date-picker/src/shared/utils/getAutoComplete/getAutoComplete.spec.ts
- packages/date-picker/src/shared/utils/getAutoComplete/index.ts
- packages/date-picker/src/shared/utils/index.ts
🎟 _Jira ticket:_ [LG-3811](https://jira.mongodb.org/browse/LG-3811)
> Date Picker [LG-3811] autocomplete

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.testutils.tsx
- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.stories.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.tsx
- packages/date-picker/src/shared/utils/isValidValueForSegment/index.ts
- packages/date-picker/src/shared/utils/isValidValueForSegment/isValidValueForSegment.spec.ts
- packages/date-picker/src/shared/utils/newDateFromSegments/newDateFromSegments.spec.ts
[After setting a value, deleting chars from the year input sets it to 1919 or 1920](https://jira.mongodb.org/browse/LG-3847)
> Date picker [LG-3847] Restrict year input auto-format

- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.stories.tsx
- packages/date-picker/src/DatePicker/utils/getRelativeSegment/getRelativeSegment.spec.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.spec.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.stories.tsx
- packages/date-picker/src/shared/utils/testutils.ts
> Fix Chromatic failures

- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.tsx
> Date Picker [LG-3826] Calendar month menu jump

- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.styles.ts
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/utils/getMonthOptions/getMonthOptions.spec.ts
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/utils/getMonthOptions/index.ts
🎟 _Jira ticket:_ [LG-3838](https://jira.mongodb.org/browse/LG-3838)
> Date Picker [LG-3838] truncate selects

- packages/date-picker/src/shared/components/Calendar/CalendarCell/CalendarCell.styles.ts
> Date Picker [LG-3849, LG-3850] focus state z-index

- packages/date-picker/src/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePickerInput/DatePickerInput.stories.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.stories.tsx
- packages/date-picker/src/shared/components/Calendar/CalendarCell/CalendarCell.stories.tsx
- packages/date-picker/src/shared/components/Calendar/CalendarGrid/CalendarGrid.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateFormField/DateFormField.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputBox/DateInputBox.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.stories.tsx
- packages/date-picker/src/shared/components/DateInput/DateInputSegment/DateInputSegment.tsx
- packages/date-picker/src/shared/context/SharedDatePickerContext.utils.ts
- packages/date-picker/src/shared/testutils/getProviderPropsFromStoryContext/index.ts
> Date Picker chromatic fixes

- .changeset/famous-olives-suffer.md
- packages/text-area/src/TextArea/TextArea.tsx
> Textarea: Correctly pass aria-labelledby

- packages/date-picker/src/shared/components/DateInput/DateFormField/DateFormField.tsx
🎟 _Jira ticket:_ [LG-3865](https://jira.mongodb.org/browse/LG-3865)
> Date Picker [LG-3865] move menu position

- .changeset/gorgeous-rabbits-notice.md
- packages/date-picker/src/shared/components/Calendar/CalendarCell/CalendarCell.styles.ts
🎟 _Jira ticket:_ [LG-3821](https://jira.mongodb.org/browse/LG-3821)
> LG-3821: date picker cell transition

- .changeset/stale-dryers-unite.md
- packages/date-picker/README.md
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePicker.tsx
- packages/date-picker/src/DatePicker/DatePickerContent/DatePickerContent.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.tsx
- packages/date-picker/src/shared/context/SharedDatePickerContext.types.ts
- packages/date-picker/src/shared/context/SharedDatePickerContext.utils.ts
- packages/date-picker/src/shared/context/index.ts
- packages/date-picker/src/shared/types/BaseDatePickerProps.types.ts
🎟 _Jira ticket:_ [LG-3930](https://jira.mongodb.org/browse/LG-3930)
> LG-3930: Date Picker extend popover props

- package.json
Adds `init17` script to make locally testing in r17 environments easier.
Script is copied from current r17 github workflow
> Adds init17 script

- .changeset/odd-rabbits-deliver.md
- packages/button/src/Button.story.tsx
- packages/button/src/Button/Button.styles.ts
Fixes disabled state styling when a button is focused or active
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3942
> LG-3942 Disabled button active state styles

- .changeset/violet-buckets-lick.md
- packages/tokens/src/Tokens.story.tsx
- packages/tokens/src/space.ts
- packages/tokens/src/spacing.ts
> Adds new spacing tokens in service of Variables work

- .changeset/smart-rockets-warn.md
- packages/date-picker/src/DatePicker.stories.tsx
- packages/date-picker/src/DatePicker/DatePicker.spec.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenu.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/DatePickerMenuHeader/DatePickerMenuHeader.tsx
- packages/date-picker/src/DatePicker/DatePickerMenu/utils/getNewHighlight/getNewHighlight.spec.ts
- packages/date-picker/src/DatePicker/DatePickerMenu/utils/getNewHighlight/index.ts
🎟 _Jira ticket:_ [LG-3857](https://jira.mongodb.org/browse/LG-3857)
> LG-3857: Date Picker Correct focus state when navigating to current select month

- package.json
Adds `jest --clearCache` to `yarn clean` script. Ensures usage of newest builds & tests
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3913
> LG-3913 Adds `jest --clearCache` to `yarn clean` script

- .changeset/sweet-tomatoes-decide.md
- packages/form-field/src/FormField/FormField.styles.ts
- packages/tokens/src/spacing.ts
Update FormField to use new spacing tokens
> Update FormField to use new spacing tokens

- .changeset/serious-bats-peel.md
- packages/loading-indicator/package.json
- packages/loading-indicator/src/PageLoader/PageLoader.tsx
- packages/loading-indicator/src/Spinner/Spinner.tsx
- packages/loading-indicator/src/constants.ts
- yarn.lock
- Updates `react-lottie-player@^1.5.6`
- Adds `runExpressions: false` to Lottie config to prevent arbitrary code execution.
🎟 _Jira ticket:_ https://jira.mongodb.org/browse/LG-3979
> Prevent `eval` in lottie player

- .changeset/gentle-monkeys-grin.md
- packages/checkbox/src/Check/index.tsx
- packages/checkbox/src/Checkbox/Checkbox.spec.tsx
- packages/checkbox/src/Checkbox/Checkbox.style.ts
- packages/checkbox/src/Checkbox/Checkbox.tsx
- packages/checkbox/src/Checkbox/Checkbox.types.ts
- packages/checkbox/src/Checkbox/index.ts
- packages/checkbox/src/LegacyCheck.tsx
- packages/checkbox/src/index.ts
🎟 _Jira ticket:_ [LG-1525](https://jira.mongodb.org/browse/LG-1525)
🎟 _Jira ticket:_ [LG-2625](https://jira.mongodb.org/browse/LG-2625)
> Checkbox Component now responds to baseFontSize prop

- .changeset/quick-eggs-kneel.md
- packages/typography/package.json
> bumps `Tokens` dependency in `Typography`

- .changeset/rich-dancers-cry.md
- packages/code/src/index.ts
- Exports `Panel` component
🎟 _Jira ticket:_ [LG-4076](https://jira.mongodb.org/browse/LG-4076)
> LG-4076: Export Panel from Code package

- .changeset/spotty-cooks-change.md
- packages/table/package.json
- packages/table/src/index.ts
- yarn.lock
[LG-3360](https://jira.mongodb.org/browse/LG-3360)
[LG-4063](https://jira.mongodb.org/browse/LG-4063)
> Tanstack upgrade/exports

- .changeset/thick-bees-bow.md
- packages/tokens/src/color/color.ts
- packages/tokens/src/color/color.types.ts
- packages/tokens/src/color/darkModeColors.ts
- packages/tokens/src/color/lightModeColors.ts
> Removes types from color tokens

- chat/avatar/package.json
- chat/chat-window/package.json
- chat/input-bar/package.json
- chat/leafygreen-chat-provider/package.json
- chat/lg-markdown/package.json
- chat/message-feed/package.json
- chat/message-feedback/package.json
- chat/message-rating/package.json
- chat/message/package.json
- chat/title-bar/package.json
> Publish config public

- .changeset/few-rings-promise.md
- packages/code/src/CopyButton/CopyButton.spec.tsx
- fixes broken tests
🎟 _Jira ticket:_ [LG-3915](https://jira.mongodb.org/browse/LG-3915)
> LG-3915: Fix CopyButton test mock

- .changeset/popular-islands-smile.md
- packages/expandable-card/README.md
- packages/expandable-card/src/ExpandableCard/ExpandableCard.types.ts
🎟 _Jira ticket:_ [4095](https://jira.mongodb.org/browse/4095)
> LG-4095: Improve ExpandableCard title prop type

- .changeset/afraid-shoes-laugh.md
- packages/chip/package.json
> Fix failing main

- .changeset/chatty-chefs-itch.md
- packages/expandable-card/src/ExpandableCard/ExpandableCard.tsx
- yarn.lock
🎟 _Jira ticket:_ [LG-4113](https://jira.mongodb.org/browse/LG-4113)
> LG-4113: Wrap `description` value content  in `div` not `p` tag

- .changeset/little-pets-grow.md
- packages/select/src/Select/Select.tsx
> Fix description propType in Select component

- packages/form-field/CHANGELOG.md
> Fix form field changelog

- .changeset/two-chefs-argue.md
> Add changeset

- .github/workflows/pr.yml
- .github/workflows/release.yml
Related Docs:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> Run CI PR workflow on Merge Groups

- packages/emotion/README.md
> Update `emotion` README.md

- .changeset/chilled-bobcats-yawn.md
- packages/tokens/src/color/color.types.ts
- packages/tokens/src/color/darkModeColors.ts
- packages/tokens/src/color/lightModeColors.ts
🎟 _Jira ticket:_ [LG-4089](https://jira.mongodb.org/browse/LG-4089)
> LG-4089: Adds Link tokens

- .changeset/nervous-suits-thank.md
- chat/avatar/src/Avatar.stories.tsx
Adds generated stories for Chat Avatar
> Adds generated stories for Chat Avatar

- packages/tabs/src/Tabs/Tabs.styles.ts
- packages/tabs/src/Tabs/Tabs.tsx
- packages/tabs/src/Tabs/index.ts
- packages/tabs/src/index.ts
- adds and exports class names for tab list and tab panels container elements
🎟 _Jira ticket:_ [LG-2938](https://jira.mongodb.org/browse/LG-2938)
> LG-2938: add and export tabs elements class names

- .changeset/smooth-lemons-call.md
- packages/stepper/src/Stepper.stories.tsx
> Stepper defaults

- .vscode/settings.json
> Prefer relative import path style for auto imports

- DEVELOPER.md
- STYLEGUIDE.md
Adds a section on avoiding `cloneElement`
> Styleguide updates

- packages/tabs/src/TabTitle/TabTitle.styles.ts
🎟 _Jira ticket:_ [LG-3270](https://jira.mongodb.org/browse/LG-3270)
> LG-3270: fixed tab title height

- packages/tabs/package.json
- packages/tabs/src/TabTitle/TabTitle.tsx
- packages/tabs/src/TabTitle/TabTitle.types.ts
- packages/tabs/src/Tabs.stories.tsx
- packages/tabs/src/Tabs/Tabs.tsx
- packages/tabs/src/Tabs/Tabs.types.ts
- packages/tabs/tsconfig.json
- yarn.lock
- add `@leafygreen-ui/polymorphic` dependency to tabs package
- in `TabTitle` component, migrate from `Box` to `InferredPolymorphic`
- remove `@leafygreen-ui/box` dependency from tabs package
Will make final changeset after all tabs changes are merged to integration branch
🎟 _Jira ticket:_ [LG-2728](https://jira.mongodb.org/browse/LG-2728)
> LG-2728: migrate from Box to Polymorphic in tabs package

- .changeset/fresh-beans-rush.md
- chat/message/package.json
Publish a new version of `@lg-chat/message` that applies the import fix from https://github.com/mongodb/leafygreen-ui/pull/2353
> Fix import from rich-links

- .changeset/pretty-carrots-shout.md
- packages/icon/src/Icon.stories.tsx
> Rename "AllIcons" to "LiveExample" for proper rendering on .design

- .changeset/empty-carrots-sing.md
- packages/typography/src/H1/H1.styles.ts
> LG-4316: Updates H1 line height from 62 to 64px

- .changeset/few-pugs-raise.md
- packages/chip/src/DismissButton/DismissButton.tsx
🎟 _Jira ticket:_ [LG-4300](https://jira.mongodb.org/browse/LG-4300)
> LG-4300: Updates dismiss button to include `type="button"` so that component dismissal does not submit forms

- .gitignore
- packages/testing-lib/package.json
- packages/testing-lib/src/waitForTransition/waitForTransition.spec.tsx
- yarn.lock
- removes `Transition` component from test suite
- adds explicit `transition` property to test component
> resolve r17 tests

- .changeset/beige-eels-tap.md
- packages/typography/src/Link/shared.styles.ts
Changes link focus styles from focus to focus-visible
🎟 _Jira ticket:_ [LG-4228](https://jira.mongodb.org/browse/LG-4228)
> LG-4228: Update link focus state styles

- .changeset/stale-cheetahs-smell.md
- packages/typography/src/InlineCode/InlineCode.styles.ts
🎟 _Jira ticket:_ [LG-4349](https://jira.mongodb.org/browse/[LG-4349)
> LG-4349: Updates background color of InlineCode component

- .changeset/proud-radios-fold.md
- packages/select/src/Option/Option.tsx
🎟 _Jira ticket:_ [LG-4367](https://jira.mongodb.org/browse/LG-4367)
> LG-4367: select disabled option regression

- .changeset/orange-humans-admire.md
- packages/input-option/src/InputOption/InputOption.style.ts
> Adds back `display: block` property, which is important!

- .changeset/cyan-humans-add.md
- packages/avatar/package.json
- packages/avatar/src/Avatar.stories.tsx
> Avatar updates

- .changeset/angry-roses-share.md
- packages/palette/src/Palette.stories.tsx
> Updates Palette story for .design

- package.json
- tools/build/package.json
- turbo.json
- yarn.lock
> Upgrades turbo to 2.0.6

- packages/descendants/src/Highlight/Highlight.stories.tsx
No changelog.
Updates Grid Highlight story
> Update highlight grid story

- .changeset/nine-goats-reply.md
- chat/fixed-chat-window/src/ChatTrigger/ChatTrigger.tsx
🎟 _Jira ticket:_ [EAI-470](https://jira.mongodb.org/browse/EAI-470)
> EAI-470: Fix dark mode sparkle color on ChatTrigger

- .github/CODEOWNERS
- README.md
> Did we add a code reviewer?

- .changeset/clever-hotels-report.md
- chat/rich-links/src/RichLink/RichLink.stories.tsx
- chat/rich-links/src/RichLink/richLinkVariants.ts
🎟 _Jira ticket:_ [(EAI-522) [LG] Add Article as rich link variant](https://jira.mongodb.org/browse/EAI-522)
> (EAI-522) [LG] Add Article as rich link variant

- .changeset/ninety-chefs-cry.md
- chat/message/src/index.ts
> Export MessageLinks from @lg-chat/message

- .changeset/warm-chicken-speak.md
- packages/combobox/CHANGELOG.md
- packages/combobox/package.json
- packages/menu/CHANGELOG.md
- packages/menu/package.json
- packages/search-input/CHANGELOG.md
- packages/search-input/package.json
- packages/select/CHANGELOG.md
- packages/select/package.json
> Updates `hooks` version in `menu`, `combobox`, `searchInput`, and `select`

- .changeset/cuddly-beans-raise.md
- charts/core/README.md
- charts/core/src/Grid/Grid.tsx
- charts/core/src/Grid/Grid.types.ts
- charts/core/src/Grid/config/index.ts
- charts/core/src/Grid/config/useGridOptions.ts
- charts/core/src/Grid/index.ts
- charts/core/src/index.ts
- Adds `Grid` component to `@lg-charts/core`
🎟 _Jira ticket:_ [LG-4618](https://jira.mongodb.org/browse/LG-4618)
- Check `LineChart` component usage in storybook.
> LG-4618: Add Grid component

- .changeset/silent-badgers-hammer.md
- charts/core/src/Chart/Chart.spec.tsx
- charts/core/src/Chart/Chart.tsx
> Fix bad import in charts

- DEVELOPER.md
Adds a guide in `DEVELOPER.md` for using Verdaccio
> Adds Verdaccio docs to `DEVELOPER.md`

- packages/checkbox/README.md
Updates the link.
Double check the link
> Fix example link in `Checkbox` README

- .changeset/three-zebras-sin.md
- tools/slackbot/package.json
- tools/slackbot/src/release-bot/release-bot.ts
- yarn.lock
Updates `@lg-tools/slackbot` with missing `dotenv` dependency
> Add missing dotenv dep

- packages/date-utils/src/getDaysInUTCMonth/getDaysInUTCMonth.spec.ts
From @kraenhansen:
>  I got this failure when running tests locally.
> I suspect this is because `Date` objects constructed from numeric values will depend on the computers locale settings: I'm on a computer with locale set as "Danish / Denmark".
> Make tests locale independent (#2592)

- .changeset/tame-panthers-knock.md
- packages/split-button/src/Menu/Menu.tsx
- packages/split-button/src/SplitButton/SplitButton.spec.tsx
> LG-4714: Fix using `SplitButton` as a managed component (#2596)

- packages/table/README.md
- packages/table/src/Table.Interactions.stories.tsx
- packages/table/src/Table.stories.tsx
- packages/table/src/Table/TableWithVS.stories.tsx
- packages/table/src/utils/makeData.testutils.tsx
- tools/storybook-addon/package.json
- yarn.lock
> Table snapshot changes

- .changeset/title-bar-import.md
- chat/title-bar/src/TitleBar/TitleBar.tsx
Fixes broken import of `ChatAvatarVariant`
> Fix import in Chat Title Bar

- .changeset/lucky-berries-rush.md
> Remove table from changeset(lucky-berries-rush.md)

- .changeset/eleven-lies-travel.md
- packages/empty-state/src/BasicEmptyState/BasicEmptyState.styles.ts
🎟 _Jira ticket:_ [LG-4763:](https://jira.mongodb.org/browse/LG-4763)
> LG-4763: Update max-width in Empty State component

- packages/icon/README.md
🎟 _Jira ticket:_ [LG-4782](https://jira.mongodb.org/browse/LG-4782)
> LG-4782: Update Icon docs

- .changeset/big-drinks-thank.md
> Downgrade SplitButton's changeset from major to minor

- packages/button/README.md
🎟 _Jira ticket:_ [LG-4653](https://jira.mongodb.org/browse/LG-4653)
> LG-4653: Updates button read me to better describe loading props

- .changeset/thirty-actors-beg.md
- packages/gallery-indicator/README.md
- packages/gallery-indicator/package.json
- packages/gallery-indicator/src/GalleryIndicator.stories.tsx
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.spec.tsx
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.styles.ts
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.tsx
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.types.ts
- packages/gallery-indicator/src/GalleryIndicator/index.ts
- packages/gallery-indicator/src/constants.ts
- packages/gallery-indicator/src/index.ts
- packages/gallery-indicator/src/utils/getTestUtils/getTestUtils.spec.tsx
- packages/gallery-indicator/src/utils/getTestUtils/getTestUtils.ts
- packages/gallery-indicator/src/utils/getTestUtils/getTestUtils.types.ts
- packages/gallery-indicator/tsconfig.json
- packages/table/src/utils/makeData.testutils.tsx
- pnpm-lock.yaml
🎟 _Jira ticket:_ [LG-4876](https://jira.mongodb.org/browse/LG-4876)
> LG-4876: adds `GalleryIndicator` package

- .changeset/thirty-actors-beg.md
- packages/gallery-indicator/package.json
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.spec.tsx
- packages/gallery-indicator/src/GalleryIndicator/GalleryIndicator.tsx
- packages/gallery-indicator/src/constants.ts
- packages/gallery-indicator/src/index.ts
- packages/gallery-indicator/src/utils/getTestUtils/getTestUtils.ts
> GalleryIndicator LGIDS to LGIDs

- packages/code/src/Code.stories.tsx
- packages/code/src/Code/Code.tsx
- packages/code/src/Code/utils/getHorizontalScrollbarHeight.ts
- packages/code/src/Code/utils/hasMultipleLines.ts
- packages/code/src/Code/utils/index.ts
> Code cleanup

- packages/code/src/Code.stories.tsx
- packages/code/src/Code/Code.spec.tsx
> `Code` loading story fix

- package.json
Stop opening browser when starting storybook
- Run `pnpm run start`
> Stop opening browser when starting storybook

- .changeset/pink-moons-heal.md
- packages/gallery-indicator/src/GalleryIndicator.stories.tsx
> add one more argType

- .changeset/shiny-dots-fry.md
- packages/loading-indicator/src/LoadingIndicator.stories.tsx
> LG-3286: loading indicator live example

- DEVELOPER.md
> Update verdaccio section in DEVELOPER.md

- .changeset/metal-cougars-develop.md
- packages/checkbox/src/Checkbox/Checkbox.tsx
- packages/checkbox/src/Checkbox/Checkbox.types.ts
🎟 _Jira ticket:_ [LG-4894](https://jira.mongodb.org/browse/LG-4894)
> LG-4894: Checkbox component now accepts a forwarded ref

- .changeset/silly-goats-study.md
- packages/confirmation-modal/src/ConfirmationModal/ConfirmationModal.spec.tsx
- packages/modal/package.json
- packages/modal/src/Modal/Modal.spec.tsx
- packages/modal/src/Modal/Modal.types.ts
- packages/modal/src/Modal/ModalView.tsx
- packages/modal/src/constants.ts
- packages/modal/src/index.ts
- packages/modal/src/utils/getTestUtils.spec.tsx
- packages/modal/src/utils/getTestUtils.ts
- packages/modal/src/utils/getTestUtils.types.ts
- packages/modal/src/utils/index.ts
- packages/modal/tsconfig.json
- pnpm-lock.yaml
> Adds getTestUtils to Modal component

- .changeset/cuddly-wolves-melt.md
- charts/colors/package.json
> Make lg-charts/colors public

- .env.example
> Creates .env.example

- chat/message-rating/src/MessageRating/MessageRating.styles.ts
- chat/message-rating/src/RadioButton/RadioButton.styles.ts
- Make Chat feedback component buttons smaller
🎟 _Jira ticket:_ [LG-4256](https://jira.mongodb.org/browse/LG-4256)
- Check in storybook
> LG-4256: Make Chat feedback component buttons smaller

- .changeset/emotion-nonce.md
- packages/emotion/package.json
- packages/emotion/scripts/prebuild.ts
- packages/emotion/scripts/tsconfig.json
- packages/emotion/src/emotion.ts
- packages/emotion/src/version.ts
- pnpm-lock.yaml
Adds `nonce` property to debug and ensure consistent versions
> Emotion versioning

- .changeset/eleven-wolves-retire.md
- .changeset/quick-pans-stare.md
- chat/input-bar/src/InputBar/InputBar.tsx
- packages/code/src/CopyButton/CopyButton.tsx
- packages/combobox/src/Combobox/Combobox.tsx
- packages/date-picker/src/DatePicker/DatePickerContent/DatePickerContent.tsx
- packages/hooks/src/useBackdropClick.ts
- packages/search-input/src/SearchInput/SearchInput.tsx
- packages/split-button/src/Menu/Menu.tsx
- packages/toast/src/ToastContainer/ToastContainer.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
> Use latest version of `useBackdropClick`

- .changeset/meta-get-package-root.md
- tools/meta/src/getPackageRoot/getPackageRoot.spec.ts
- tools/meta/src/getPackageRoot/index.ts
- tools/meta/src/index.ts
Adds `getPackageRoot` utility that returns the full path to a given package dir
> Adds `getPackageRoot` utility

- .changeset/shaggy-pens-mate.md
- packages/text-input/src/TextInput.stories.tsx
- packages/text-input/src/TextInput/TextInput.spec.tsx
- packages/text-input/src/TextInput/TextInput.tsx
🎟 _Jira ticket:_ [LG-5063](https://jira.mongodb.org/browse/LG-5063)
> LG-5063: Add support for `defaultValue` property

- apps/chatbot-server/packages/server/src/index.ts
> Cleanup Branch

- .changeset/chatty-berries-pay.md
- packages/table/src/Table/Table.types.ts
> Update `shouldTruncate` default value in Table TSDoc

- charts/core/src/Chart/config/getDefaultChartOptions.ts
- charts/core/src/ChartTooltip/ChartTooltip.tsx
- charts/core/src/constants.ts
Commonly used default settings moved to constants file for better maintainability.
🎟 _Jira ticket:_ [LG-5093](https://jira.mongodb.org/browse/LG-5093)
> LG-5093: refactor common charts default settings into constants file

- packages/drawer/src/DrawerToolbarLayout/DrawerToolbarLayout.interactions.stories.tsx
- packages/toolbar/src/Toolbar.stories.tsx
> Add faker seed to prevent snapshots from changing

- tools/create/src/templates/component/src/Component/component.index.template.ts
- tools/create/src/templates/component/src/index.template.ts
- tools/storybook-decorators/src/decorators/PropCombinations/README.md
1. Updates story decorators README to reflect correct parameter name
2. Modifies `create-package` template to explicitly export prop type definitions using `export type` syntax (avoid error on `pnpm build` before any code is written)
> chore: update outdated docs and create-package template

- .changeset/tricky-shoes-share.md
- packages/code/package.json
- pnpm-lock.yaml
> Adds missing `build` dependency from Code package

- chat/chat-disclaimer/README.md
- chat/fixed-chat-window/README.md
- chat/message-feedback/README.md
- chat/message-prompts/README.md
Changes install directions to use `@lg-chat` instead of `@leafygreen-ui` for some chat packages
> update chat install directions

- .changeset/bumpy-dragons-decide.md
- packages/code/src/Code.stories.tsx
- packages/code/src/CopyButton/index.ts
- packages/code/src/index.ts
> Exports CopyButton from Code component

- packages/progress-bar/package.json
- packages/progress-bar/src/ProgressBar.interactions.stories.tsx
- packages/progress-bar/src/ProgressBar.stories.tsx
- packages/progress-bar/src/ProgressBar/ProgressBar.constants.ts
- packages/progress-bar/src/ProgressBar/ProgressBar.styles.ts
- packages/progress-bar/src/ProgressBar/ProgressBar.tsx
- packages/progress-bar/src/ProgressBar/ProgressBar.types.spec.tsx
- packages/progress-bar/src/ProgressBar/ProgressBar.types.ts
- packages/progress-bar/src/ProgressBar/ProgressBar.utils.tsx
- packages/progress-bar/src/constants.ts
- packages/progress-bar/tsconfig.json
- pnpm-lock.yaml
- shimmer and looping animation for determinate and indeterminate variants, respectively
- smooth opacity transition from indeterminate to determinate variants
- refactor storybook helper function to render dynamic changes to the progress bar after fixed timeouts
- create a constants file purely for styles due to its bulk
- create a general constants file
🎟 _Jira ticket:_ [LG-5316](https://jira.mongodb.org/browse/LG-5316)
> LG-5316: progress bar animations

- .changeset/cyan-spies-pump.md
- .storybook/preview.ts
- pnpm-lock.yaml
- tools/storybook-addon/package.json
- tools/storybook-addon/rollup.config.mjs
- tools/storybook-addon/src/main/index.ts
- tools/storybook-addon/src/preview/index.tsx
Base PR to get autodocs into the repo. Part one of migrating our docs off of .design :)
> Adds autodocs support to Storybook

- .changeset/cyan-spies-pump.md
Bad merge pipeline. This changeset got added twice!
> Rm duplicative changeset

- .changeset/new-knives-watch.md
- packages/tokens/src/shadows/addOverflowShadow.ts
> Overflow shadow light mode updates

- .changeset/quick-kids-attend.md
> Refactor(drawer): remove redundant resizable prop from documentation

- packages/drawer/src/DrawerToolbarLayout/DrawerWithToolbarWrapper/DrawerWithToolbarWrapper.styles.ts
This is a bug introduced with the resizable drawer work. The drawer's width was only as wide as the drawer content. This fix makes the width 100% of the container.
> style(DrawerWithToolbarWrapper): fix drawer width

- packages/menu/README.md
> Updates Menu Readme
